Dop 4340 1 homepage
mongodb/snooty pull request #1016
Opened 2024-02-20 16:27 UTC by mayaraman19

### Stories/Links:

DOP-NNNN

### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [ ] This PR does not introduce changes that should be reflected in the README

2024-02-22 14:41 UTC, mmeigs requested changes
Okay, these PRs are always so nit-picky to review, so sorry. And definitely check with design before you just take my opinion!!

- The left padding in the main four cards seems different in the design. This could also help for the text to fully stretch out in the max-width possibly. But the design seems to have two different padding-left amounts. Two of them are ~25px and two are ~29px. Your implementation is 32px. 
- I'm not sure if this falls into what @anabellabuckvar is working on, but the secondary heading "More ways to learn" has incorrect styling. (I'm guessing this is a different ticket, but thought I'd mention)
- Comment for docs-landing PR - Check with design and also with Sarah Lin? But the titles on the TOC are different from design. This can be changed in the `.. ia:` section in docs-landing `index.txt`
- The line-height value is incorrect in the text of the small cards at the bottom of the page, ie "Take Free Courses on MongoDB University"
- On mobile, in the larger four cards, the icon and text need to switch to column layout. One on top of the other.
- Oh, and one very very odd thing: in this staging link there is a TOC entry at the top that says "Docs Home"... shouldn't be there, and not really sure how it got there?! lol

2024-02-22 14:41 UTC, mmeigs commented on src/components/Card/index.js
> +    //min-width: 164px;
Should this be removed?

2024-02-22 14:41 UTC, mmeigs commented on src/components/Card/index.js
> +// new->old homepage redesign
Not totally sure what this comment means or adds to the code

2024-02-26 17:16 UTC, seungpark reviewed
minor comments below but overall looks great!

one minor thing i noticed is that the hero and text are not aligned very well. we set the height of the hero at different viewports and the `align-self: end` properties on the heading and paragraph make the margins vary when changing viewport.

for example:

![image](https://github.com/mongodb/snooty/assets/13054820/bf9e4d1a-80b6-44a7-9716-d3768cff18d1)

![image](https://github.com/mongodb/snooty/assets/13054820/13e4f0bf-4674-47c2-8495-0eb6d998623c)

we can take this in another issue, but perhaps we can make the hero image as a background-image property and have strict margins, not alignments, on the heading and paragraph elements.

2024-02-27 16:16 UTC, mayaraman19 commented on src/components/Card/CardGroup.js
> +    '' /*want first 4 cards on landing page to stay as one column, and not affect group of 3 cards (so hacky i'm sorry) */
without this part, when the viewport is a bit smaller the card groups become 2 x 2, but i want them to stay in one column regardless of viewport size

2024-02-27 20:10 UTC, mayaraman19 commented
I think I have addressed the comments - as for the header, this got approved by design, we didn't want to touch too many things in case the homepage gets changed again but I'm happy to create a separate ticket because I do think having set margins would be nice.

2024-02-27 21:05 UTC, seungpark commented on src/components/Card/CardGroup.js
> +    '' /*want first 4 cards on landing page to stay as one column, and not affect group of 3 cards (so hacky i'm sorry) */
oh, would we not want to honor the `columns` options here? seems a bit forced to force 2 columns based on viewport. we can possibly set a default to 2 to prevent regressions but can always favor the `column` option if available

2024-02-27 21:18 UTC, seungpark requested changes
largely LGTM! left a comment regarding:
1 - the column option to be respected
and 2 - the second set of card groups to have bigger icons

2024-02-27 21:18 UTC, seungpark commented on src/components/Card/index.js
> +    line-height: 24px;
(nit) to use theme here

2024-02-27 21:18 UTC, seungpark commented on src/components/Card/index.js
> +    width: ${theme.size.xlarge};
this overrides the width for the first set of cards, but on a minor note, the second icons seem smaller than design as well (design shows roughly 42-46px width):

![image](https://github.com/mongodb/snooty/assets/13054820/d8d3fe97-ee8e-4e72-8d7a-8f06fc811b54)

2024-02-27 21:58 UTC, mayaraman19 commented on src/components/Card/CardGroup.js
> +    '' /*want first 4 cards on landing page to stay as one column, and not affect group of 3 cards (so hacky i'm sorry) */
ok, changed it so on the landing page the column option is respected, but leaving the default for cardgroup as it was before to be 2 columns

2024-02-27 22:48 UTC, seungpark approved these changes
this LGTM!

should merge the content change also !

2024-02-27 23:11 UTC, merged