DOP-4450
mongodb/snooty pull request #1048
Opened 2024-03-25 20:57 UTC by caesarbell

### Stories/Links:

DOP-4450

### Current Behavior:

[Server Prod](https://www.mongodb.com/docs/manual/)

### Staging Links:

[Simplified Chinese staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/zh-cn/master/docs/caesarbell/manual/)
[Korean staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/ko-kr/master/docs/caesarbell/manual/)
[English staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/749fe69727251fd589dbedf30558ec188f2f5270/master/docs/caesarbell/manual/)

### Notes:

The ticket's ask is to use the following fonts for our Simplified Chinese and Korean sites.

[Noto Sans Simplified Chinese](https://fonts.google.com/noto/specimen/Noto+Sans+SC)
[Noto Sans Korean](https://fonts.google.com/noto/specimen/Noto+Sans+KR)

We won't be able to test the actual Koren and Simplified Chinese characters, as Smartling is not set up for our pre-prod environment. 

I have manually staged `zh-cn` and `ko-kr` to trigger the locale, so we can confirm the expected font is loaded and being applied to the side nav and the inner section of the document page (everything, excluding the nav and footer). 

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

2024-03-25 22:24 UTC, rayangler reviewed
Just one non-blocking concern/question.

Reminder to update the PR title to be more contextual

2024-03-25 22:49 UTC, rayangler commented on package.json
> +    "react-helmet": "^6.1.0",
Actually, looks like the Gatsby docs are outdated as well, so unsure if there's anything more up-to-date available... For what it's worth, we have existing examples for adding fonts through `@font-face` in our [css file](https://github.com/mongodb/snooty/blob/9a767ef2f4a5f73922e836549eb4b1f99bf34d6a/src/styles/mongodb-docs.css#L51) or [preview-layout file](https://github.com/mongodb/snooty/blob/9a767ef2f4a5f73922e836549eb4b1f99bf34d6a/src/layouts/preview-layout.js#L76), but unsure if it's as performant as the plugin 🤔

2024-03-25 22:51 UTC, rayangler commented on src/layouts/index.js
> +  }
(General question) This rule means we'll be overwriting any other font used, including for code blocks and anything wrapped in a `code` tag. Is that intentional?

2024-03-26 15:39 UTC, caesarbell commented on package.json
> +    "react-helmet": "^6.1.0",
@rayangler good question and I was a little sad to have to download `react-helmet`, but that is a direct dependency of `gatsby-omni-font-loader`. From Gatsby docs they had recommended that package, even their last update was 2 years ago. 

I can double check to see if I can find if there is another recommendation from Gatsby with the latest upgrade.

2024-03-26 15:41 UTC, caesarbell commented on src/layouts/index.js
> +  }
@rayangler yes, this rule was intentional to override everything in the side nav, and main page, everything, excluding the header and footer. 

My assumption would be everything would use the new font, but I can confirm to be certain. In short, this was intentional.

2024-03-26 17:27 UTC, caesarbell commented on package.json
> +    "react-helmet": "^6.1.0",
@rayangler when using `@font-face` it won't be as performant, as I did see that was an alternative from Gatsby and from our code examples. But with this, we lose out on some of the performant benefits, which Idk if it is worth moving away from the plugin. Thoughts?

2024-03-26 17:31 UTC, schmalliso commented on src/layouts/index.js
> +  }
We should only be using Noto Sans to replace Euclid Circular A and Value Serif (i.e. everything except code).

2024-03-26 17:57 UTC, rayangler commented on package.json
> +    "react-helmet": "^6.1.0",
Gotcha. My initial thought is that we can probably emulate what the plugin does on our end, but that might be more trouble than it's worth to port over and maintain. I'd also be curious as to how much of a performance boost we'll get with the plugin considering that the fonts are currently used client-side due to our limitation in determining if the static page is being translated by Smartling. I'm assuming it'd help even a tiny bit with preloading the fonts, so I guess that's okay.

That being said, let's stick with the plugin for now to see how it performs. The package situation isn't necessarily the end of the world. We can always change later if needed anyways. Thanks for looking into our possible options further!

2024-03-26 19:50 UTC, caesarbell commented on package.json
> +    "react-helmet": "^6.1.0",
Yeah, I am not finding a really good option from Gatsby, here are two they mentioned
- [typography.js](https://www.gatsbyjs.com/docs/using-typography-js/)
- [fontsource](https://www.gatsbyjs.com/docs/how-to/styling/using-web-fonts/#self-host-google-fonts-with-fontsource)

The two options we have, if we really want to avoid the two plugins installed are probably 

- `@font-face`
- making a PR directly to LeafyGreen Typography and Provider component to support these new fonts

I framed from the latter, because Noto Sans SC and KR are only for docs pages, and LG is used widely throughout MongoDB.

2024-03-26 19:51 UTC, caesarbell commented on src/layouts/index.js
> +  }
@schmalliso thank you for confirming. I will make these changes.

2024-03-28 14:03 UTC, seungpark approved these changes
this LGTM, sans a minor comment on the extra div id.

re the previous conversation of removing react helm, there seems to be a way to use local fonts as well if we upload the `woff` file in our static folder, which might be less subject to errors not on our end https://www.gatsbyjs.com/docs/how-to/styling/using-local-fonts/

2024-03-28 14:43 UTC, caesarbell commented
> this LGTM, sans a minor comment on the extra div id.
> 
> re the previous conversation of removing react helm, there seems to be a way to use local fonts as well if we upload the `woff` file in our static folder, which might be less subject to errors not on our end https://www.gatsbyjs.com/docs/how-to/styling/using-local-fonts/

@seungpark , I am not opposed to going this route, it does seem we will still have the ability to optimize for performance due to the use of pre-loading. 

@rayangler what are your thoughts?

2024-03-28 14:45 UTC, caesarbell commented on src/layouts/index.js
> +  #template-container *:not(:is(code, code *)) {
@seungpark good question, the reason for the new `div` with the id `#template-container`, is to lock down the font-family to just the side-nav and content of the page (i.e. everything, excluding the nav and footer). If we just apply the new style rule to the body, it will apply it to that nav and footer.

2024-03-28 15:09 UTC, rayangler commented
That is similar to what I was referring to when I mentioned using the `@font-face` and having the optimization logic ourselves (thanks for finding the docs link with a concrete example!). I'm okay with trying it out so that we don't have to rely on `react-helmet`.

I just remembered we [used to do it with Akzidenz](https://github.com/mongodb/snooty/commit/80fb81652d716f576c6b5f3bfe3046ed593649aa), minus the preloading.

2024-03-28 16:21 UTC, caesarbell commented on src/layouts/index.js
> +  #template-container *:not(:is(code, code *)) {
@seungpark, that isn't a bad idea, but with a slight different, could we just apply the style directly on the `<Template>` component and remove the newly created div with id. Thoughts?

2024-03-28 16:29 UTC, seungpark commented on src/layouts/index.js
> +  #template-container *:not(:is(code, code *)) {
works for me :+1: as long as the mentioned excluded stay excluded!

2024-03-28 17:35 UTC, caesarbell commented on src/layouts/index.js
> +  #template-container *:not(:is(code, code *)) {
For Noto Sans SC and KR, I have to convert them to `woff2`. Working on that now.

2024-03-29 19:08 UTC, seungpark requested changes
the font files were not included in the repository. also can you update the staging links once that is included

2024-03-29 19:08 UTC, seungpark commented on src/styles/mongodb-docs.css
> +  src: url(../../static/fonts/NotoSansSC-VariableFont_wght.woff2) format('woff2');
getting an error here when running `gatsby develop`:

```
Error: Can't resolve '../../static/fonts/NotoSansSC-VariableFont_wght.woff2' in '/Users/seung.park/Desktop/repositories/snooty/src/styles'
```

seems like the font files were not added

2024-03-29 19:46 UTC, caesarbell commented on src/styles/mongodb-docs.css
> +  src: url(../../static/fonts/NotoSansSC-VariableFont_wght.woff2) format('woff2');
@seungpark the staging links were updated with the latest changes.

2024-03-29 19:51 UTC, caesarbell commented on src/styles/mongodb-docs.css
> +  src: url(../../static/fonts/NotoSansSC-VariableFont_wght.woff2) format('woff2');
@seungpark , sorry about. I didn't realize it was being ignored. You should be good to try it.

2024-04-01 13:58 UTC, seungpark commented
seems like the font file is being hashed (on Gatsby's end) and being referred to as without the hash in the name, which results in two versions of the font being downloaded (see screenshot). based on [this comment](https://github.com/gatsbyjs/gatsby/issues/13074#issuecomment-479576307), we can preload the fonts using `import` statement. i branched off your branch and made some changes, and only seeing one font preloaded https://github.com/mongodb/snooty/compare/DOP-4450...DOP-4450-s

Also, other font sizes are <100kb while this one is >5MB. can we verify why this may be the case?

![image](https://github.com/mongodb/snooty/assets/13054820/38eeb2db-ed81-433c-b923-fd2606a10b0f)

2024-04-01 15:49 UTC, caesarbell commented
> seems like the font file is being hashed (on Gatsby's end) and being referred to as without the hash in the name, which results in two versions of the font being downloaded (see screenshot). based on [this comment](https://github.com/gatsbyjs/gatsby/issues/13074#issuecomment-479576307), we can preload the fonts using `import` statement. i branched off your branch and made some changes, and only seeing one font preloaded [DOP-4450...DOP-4450-s](https://github.com/mongodb/snooty/compare/DOP-4450...DOP-4450-s)
> 
> Also, other font sizes are <100kb while this one is >5MB. can we verify why this may be the case?
> 
> ![image](https://private-user-images.githubusercontent.com/13054820/318456015-38eeb2db-ed81-433c-b923-fd2606a10b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODMwOTksIm5iZiI6MTcxMTk4Mjc5OSwicGF0aCI6Ii8xMzA1NDgyMC8zMTg0NTYwMTUtMzhlZWIyZGItZWQ4MS00MzNjLWI5MjMtZmQyNjA2YTEwYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE0NDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZjMwYTUzNjFkMGRjODIxNDY1MGFjMWJlYWYwMTI4MzRiOTIxOTFhZDJkMzIxYzhiODBlZmJlMTZlMGQ1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YZv6JSS9w2FT5YxAydYiLeVhiqVd1sixjFlpBu_sW6Y)

Good catch on the fonts being loaded twice. I saw in your suggested change you applied the class name on the body, however, that would apply the rule to the entire body, which isn't the desired outcome. We only want to apply the style rule to elements on the page excluding the nav and footer.

2024-04-01 17:53 UTC, seungpark approved these changes
minor comments below but overall LGTM. would also try to limit the size of these font files as a follow up improvement

2024-04-01 17:53 UTC, seungpark commented on src/components/Sidenav/Sidenav.js
> +  #side-nav-1 * {
minor nitpick. we can add another styling const or rename this one as this does more than `disableScroll` now

2024-04-01 17:53 UTC, seungpark commented on src/components/DocumentBody.js
> +        styles={css`
can we put the css value in a function and call it from here for cleanliness

2024-04-01 21:03 UTC, rayangler approved these changes
Change look relatively fine to me, but +1 on the concern about size of font files. 3-7MB is a lot, but I don't recall the plugin having the same issues. We should definitely watch out for how that impacts prod

2024-04-01 21:32 UTC, merged