:art: DOP-4780 overrides the weblink-link any styles for dark mode
mongodb/snooty pull request #1149
Opened 2024-06-25 21:33 UTC by caesarbell

### Stories/Links:

DOP-4780

### Current Behavior:

[Docs Manual](https://www.mongodb.com/docs/manual/tutorial/install-mongodb-enterprise-on-red-hat-tarball/#platform-support)

### Staging Links:

[Staged: Docs Manaual](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/caesarbell/DOP-4780/tutorial/install-mongodb-enterprise-on-red-hat-tarball/index.html#footnote-oracle-linux)

### Notes:

- overrides the `-webkit-link` color and color for visited styles for dark mode

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

2024-06-25 21:35 UTC, caesarbell commented on src/components/Footnote/FootnoteReference.js
> +const refStyles = (darkMode) => css`
I opted for applying the dynamic styles within the static styles since we might not use the style props.

If this was premature, I can update the code to use the style props with CSS vars.

2024-06-26 12:32 UTC, seungpark requested changes
minor change below for using LG / emotion

2024-06-26 12:32 UTC, seungpark commented on src/components/Footnote/FootnoteReference.js
> +import { css } from '@emotion/react';
lets use the css / cx from '@leafygreen-ui/emotion' and move into classNames for consistency

2024-06-26 14:35 UTC, caesarbell commented on src/components/Footnote/FootnoteReference.js
> +import { css } from '@emotion/react';
@seungpark CMIIW, but `css / cx from '@leafygreen-ui/emotion'` doesn't work on non-LG components, so we would need to use `css @emotion/react` for non-LG components.

2024-06-26 14:44 UTC, caesarbell commented on src/components/Footnote/FootnoteReference.js
> +import { css } from '@emotion/react';
If you want to use the classnames we would probably need to do something like this 

```js
import { ClassNames } from '@emotion/react'
<ClassNames>
      {({ css, cx }) => (
        <div
          className={cx(
            'some-class',
            css`
              color: yellow;
            `
          )}
        />
      )}
    </ClassNames>
```

2024-06-26 15:01 UTC, seungpark commented on src/components/Footnote/FootnoteReference.js
> +import { css } from '@emotion/react';
i believe this works with className prop (not css prop) 

```
import { css, cx } from '@leafygreen-ui/emotion';
...



className={cx("footnote-reference header-buffer", refStyles(darkMode))}`
```

2024-06-28 15:10 UTC, mmeigs commented on src/components/Footnote/FootnoteReference.js
> +      className={cx('footnote-reference header-buffer', darkMode && refStyles)}
If you make this a ternary instead, emotion won't have to create a className for light mode.

``` 
className={cx('footnote-reference header-buffer', darkMode ? refStyles: '')}
```

2024-06-28 15:14 UTC, mmeigs commented on src/components/Footnote/FootnoteReference.js
> +      className={cx('footnote-reference header-buffer', darkMode && refStyles)}
You know what - I might be wrong. And anyway, this doesn't really matter. Leave it how it is!

2024-06-28 15:14 UTC, mmeigs approved these changes

2024-06-28 16:18 UTC, merged