initial commit - working page
mongodb/snooty pull request #1180
Opened 2024-07-30 14:28 UTC by mayaraman19

### Stories/Links:

DOP-NNNN

### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [ ] This PR does not introduce changes that should be reflected in the README

2024-08-09 15:53 UTC, mayaraman19 commented on src/components/DocumentBody.js
> +  // is used in useCanonicalUrl();
will create a ticket for this after this PR is reviewed/merged

2024-08-09 15:54 UTC, mayaraman19 commented on src/utils/get-complete-breadcrumb-data.js
>      : [homeCrumb, ...intermediateCrumbs, ...parents];
any advice on cleaning this up is much appreciated 😭

2024-08-14 14:03 UTC, mmeigs reviewed
On each page, we're saving the entirety of parentPaths and all the information to make breadcrumbs in session storage. What if we stored only the breadcrumbs for that page themselves? This would be a much smaller amount of info to store and to parse. 

I realize that would definitely change how the Breadcrumb components ingested that info on the FeatureNotAvailable template, though. Just a thought!

2024-08-14 14:03 UTC, mmeigs commented on src/templates/FeatureNotAvailable.js
> +              <Button onClick={click} variant="default">
I'm wondering if we can use the last breadcrumb as the reference rather than window.history? That would possibly solve the refresh issue.

2024-08-14 14:47 UTC, seungpark requested changes
nice work on the page! looks great and nice usage of session storage 👍 i think the url construction needs some rethinking since we are using a different build per project+version. perhaps we can build a path if user is only on `landing` but build a full URL otherwise.

2024-08-14 14:47 UTC, seungpark commented on src/utils/get-complete-breadcrumb-data.js
> +    let path = pageInfo ? getUrl(pageInfo.urlSlug, pageInfo.project, pageInfo.siteBasePrefix, '/') : '/';
[minor] can use const for here and the `path` in line 70

2024-08-14 14:47 UTC, seungpark commented on src/components/DocumentBody.js
> +    sessionStorage.clear();
would be cautious of clearing here. possibly better to clearItem. we also have browser-storage for sessionvalue

2024-08-14 14:47 UTC, seungpark commented on src/utils/get-complete-breadcrumb-data.js
> +      ? getUrl(pageInfo.urlSlug, pageInfo.project, pageInfo.siteBasePrefix, crumb.path)
this is a `path` property vs a distinct url property. in the Gatsby build, this will lead to relative paths instead of absolute. in the staging link provided, it is prepending to the current project's prefix. suggestion would be to use a `path` and a `url` property to distinguish the two? cc @mmeigs

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +  margin-top: 120px;
[minor nitpick] theme.size.xxlarge

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +      height: 180px;
[minor] would specify one [width] and leave the height at auto for natural ratio

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +      margin: ${theme.size.default} 48px ${theme.size.xlarge};
minor, 48px seems too big for side margins https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=7028-15272&t=oi9ZTo7uZWhdvznV-0

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +    overflow-x: auto;
i don't think we want a horizontal scroll here so we can remove

2024-08-14 14:47 UTC, seungpark commented on src/components/Breadcrumbs/index.js
> +  let queriedCrumbsHook = useBreadcrumbs();
[minor] can use const here if not reassigning

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +  color: ${darkMode ? 'white' : 'black'};
[minor] can we do this with css vars instead of prop? example [here ](https://github.com/mongodb/snooty/blob/main/src/components/Breadcrumbs/index.js#L13-L20)

2024-08-14 14:47 UTC, seungpark commented on src/templates/FeatureNotAvailable.js
> +    window.history.back();
was wondering how this button works but the breadcrumbs dont! sweet 👍

2024-08-19 16:55 UTC, mayaraman19 commented on src/templates/FeatureNotAvailable.js
> +      margin: ${theme.size.default} 48px ${theme.size.xlarge};
thanks for catching this!

2024-08-19 18:59 UTC, mayaraman19 commented on src/templates/FeatureNotAvailable.js
> +    overflow-x: auto;
i added this for consistency with [document template](https://github.com/mongodb/snooty/blob/main/src/templates/document.js#L22), but feel no strong opinion over removing vs keeping (it's useful for when individual breadcrumbs are a bit longer than page content but not long enough to collapse)

2024-08-20 16:02 UTC, mayaraman19 commented on src/utils/get-complete-breadcrumb-data.js
> +      ? getUrl(pageInfo.urlSlug, pageInfo.project, pageInfo.siteBasePrefix, crumb.path)
changed this, the paths are now being appended to "https://mongodb.com". these links don't work in staging unfortunately, but let me know what you think?

2024-08-20 16:57 UTC, mayaraman19 commented on src/templates/FeatureNotAvailable.js
> +              <Button onClick={click} variant="default">
going to wait on doing this until links have been straightened out!

2024-08-21 15:51 UTC, seungpark commented on src/components/DocumentBody.js
> +    sessionStorage.clear();
minor, meant these browser storage utils https://github.com/mongodb/snooty/blob/main/src/utils/browser-storage.js#L31-L55

2024-08-21 16:01 UTC, mmeigs reviewed
Thanks for the changes!!

I know it's so annoying, but could you use css vars for the button's background-color, color, and border-color? It's sad because each time we visit that page it will be a refresh, meaning that if in dark mode, there is ALWAYS that flash of light mode. Making theme css vars will get rid of that.

2024-08-21 17:48 UTC, mayaraman19 commented on src/templates/FeatureNotAvailable.js
> +  }
the figma calls for actual black. I can double check with design!

2024-08-21 17:56 UTC, seungpark commented on src/utils/get-complete-breadcrumb-data.js
> +      ? getUrl(pageInfo.urlSlug, pageInfo.project, pageInfo.siteBasePrefix, crumb.path)
i think this is coming from `snooty_<env>.navigation` so dev is not configured properly (baseUrl's point to `https://mongodb.com/docs`... we should probably test this in qa. also would be cool to be able to test in dev using `parserBranch` (?) from site-metadata, but this wouldn't bypass the stage testing

2024-08-21 18:36 UTC, mayaraman19 commented on src/templates/FeatureNotAvailable.js
> +
i didn't add border color because it is the same between light/dark!

2024-08-22 15:57 UTC, seungpark commented on src/utils/get-complete-breadcrumb-data.js
> +      ? getUrl(pageInfo.urlSlug, pageInfo.project, pageInfo.siteBasePrefix, crumb.path)
discussed offline. see https://jira.mongodb.org/browse/DOP-4951 for details

2024-08-22 15:59 UTC, seungpark approved these changes
approving to get this page out, but @mayaraman19 has graced us with some fast follows tickets (DOP-4950 DOP-4951) 🙌  refer to this PR for future work in those tickets

2024-08-22 16:23 UTC, merged

2024-08-23 19:23 UTC, cbush commented on src/components/DocumentBody.js
> +    };
Eslint can (should) be configured to error out on this and can also fix it automatically. I don't think it's a nit because static information can prevent bugs.