Dop 4991 dark announcement
mongodb/snooty pull request #1232
Opened 2024-09-11 19:36 UTC by mmeigs

### Stories/Links:

DOP-4991

### Current Behavior:

[Current Staging](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/)

### Staging Links:

Staging with Dark Mode Guide Cue (if preprd is deployed, the gif will not show up for now - manually inserted in S3)

### Notes:

[Figma](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=9108-17334&node-type=frame&t=YIvIFR40pZfCTA9w-0)
Requirements:
- Only show the guide cue in Desktop.
- If users dismiss the guide cue it should not appear again
- Show the guide cue to users the first time they open docs after dark mode is launched.
- If users click on the "X" button or interact with any other element of the page the guide cue should be dismissed. 
- Loop the GIF only twice
- If users navigate to a different page on docs we should dismiss the guide cue

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

2024-09-11 19:37 UTC, mmeigs commented on src/components/ActionBar/DarkModeGuideCue.js
> +  // const videoUrl = 'http://www.mongodb.com/docs/assets/darkModeGuideCue.mov';
Reminder to self: remove staging url before merging.

2024-09-11 19:37 UTC, mmeigs commented on src/components/ActionBar/DarkModeGuideCue.js
> +  // const videoUrl = 'http://www.mongodb.com/docs/assets/darkModeGuideCue.mov';
OR better yet, I will make it dependent on environment...

2024-09-12 20:07 UTC, seungpark requested changes
looks guhreat! few minor comments below but mostly preferences!

2024-09-12 20:57 UTC, mayaraman19 commented on src/components/ActionBar/DarkModeGuideCue.js
> +    font-size: 18px;
^

2024-09-12 21:29 UTC, rayangler reviewed
Just wanted to flag a few things

2024-09-12 21:29 UTC, rayangler commented on src/components/ActionBar/DarkModeGuideCue.js
> +      refEl={guideCueRef}
I don't really understand why, but it seems like the guide cue scrolls along with the rest of the page despite the `guideCueRef`. Could potentially lead to a user missing the cue if they go to a URL with a hash and scroll away immediately.

Not sure if it's worth the time to fix right now, but just wanted to flag it in case it's a blocker

2024-09-13 14:26 UTC, mmeigs commented on src/components/ActionBar/DarkModeGuideCue.js
> +  if (isMobile) return null;
Will add a check in useEffect for this! But I think in almost all cases, if a user is a mobile machine - that machine will never see the guide cue. But you're right, we are talking about developers, so it's the wild west out here!

2024-09-13 17:35 UTC, mmeigs commented on src/components/ActionBar/DarkModeGuideCue.js
> +          <h3>Announcing: Dark Mode 🌙</h3>
Agreed, would be good to have. Not going to block this just to have as much out for our release.

2024-09-13 18:55 UTC, rayangler reviewed
Looks good!

Just wanted to flag that this PR includes changes from other PRs/commits on `main`. This might diverge the history a bit. Just wanted to know if this is intentional? (If yes, happy to approve!)

2024-09-13 18:55 UTC, rayangler commented on src/components/ActionBar/DarkModeGuideCue.js
> +    if (darkModeAnnounced !== true) setIsOpen(true);
(Nit) Can simplify to `!darkModeAnnounced`

2024-09-17 21:46 UTC, seungpark commented on src/components/ActionBar/DarkModeGuideCue.js
> +          <h3>Announcing: Dark Mode 🌙</h3>
sorry @mmeigs this should've been `subtitle` but its fine the way its styled 👍

2024-09-17 21:58 UTC, seungpark reviewed
one minor comment and one functional comment below and the rest LGTM !

2024-09-17 21:58 UTC, seungpark commented on src/components/ActionBar/DarkModeDropdown.js
> +      <div ref={guideCueRef} className="guideCueRef">
minor. do we need the extra className?

2024-09-17 21:58 UTC, seungpark commented on src/components/ActionBar/DarkModeGuideCue.js
> +  useEffect(() => {
minor, might want to pass the `open` property from the dropdown, and have an effect on that to close this GuideCue if use opens the darkmode dropdown

2024-09-18 13:40 UTC, mmeigs commented on src/components/ActionBar/DarkModeGuideCue.js
> +  useEffect(() => {
Have you seen that as an issue? That click outside to open the dropdown should close the GuideCue!

2024-09-18 15:47 UTC, seungpark approved these changes
pretty!

2024-09-18 16:05 UTC, merged