DOP-5052: fixing link buffer's on mobile
mongodb/snooty pull request #1289
Opened 2024-10-21 17:59 UTC by biancalaube

### Stories/Links:

DOP-5052

### Current Behavior:

1. on the [$merge](https://www.mongodb.com/docs/manual/reference/operator/aggregation/merge/) page, the links in the field columns in the [syntax](https://www.mongodb.com/docs/manual/reference/operator/aggregation/merge/#syntax) table
2. [replSetGetStatus](https://www.mongodb.com/docs/manual/reference/command/replSetGetStatus/#mongodb-data-replSetGetStatus) page, some lines in the [output](https://www.mongodb.com/docs/manual/reference/command/replSetGetStatus/#output) section have this behavior as well (such as electionCandidateMetrics )

### Staging Links:

[merge page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/bianca.laube/DOP-5052/reference/operator/aggregation/merge/index.html)

[replSetGetStatus page](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/docs/bianca.laube/DOP-5052/reference/command/replSetGetStatus/index.html)

### Notes:
* I got rid of the buffer variable in Permalink since it was never used and always undefined when I was testing. No other file called Permalink and gave a buffer value.
* I tested locally with `banner-dev` and it seemed to work without changing any of the values, but feel free to check yourself
* Make sure the links work on mobile, tablet and full screen
* Check to make sure it didnt mess up other links

### README updates

- - [ ] This PR introduces changes that should be reflected in the README, and I have made those updates.
- - [x] This PR does not introduce changes that should be reflected in the README

2024-10-22 13:49 UTC, seungpark requested changes
see comments below!

2024-10-22 13:49 UTC, seungpark commented on src/components/Target.js
> +const HeaderBuffer = css`
[minor] we can name this styling with camelCase.

and similar comment as to above

2024-10-22 13:49 UTC, seungpark commented on src/components/Permalink.js
can we make the HeaderBuffer an inline element? this will attempt to capture the element it is already on the line with. ie.

```
export const HeaderBuffer = styled.div`
  margin-top: ${({ bufferSpace }) => bufferSpace};
  position: absolute;
  // Add a bit of padding to help headings be more accurately set as "active" on FF and Safari
  padding-bottom: 2px;
  display: inline;
`;
```

a bonus if we can make the parent element (`headingStyle`) `position: relative;` and add a `left: 0; top: 0;` to the HeaderBuffer (so when it wraps to another line, it still calculates the margin-top from the top of the parent element.

2024-10-22 13:49 UTC, seungpark commented on src/theme/docsTheme.js
> +  navbarScrollMobileOffset: '110px',
do we need another offset here? the actionbar is the same height on desktop and mobile

2024-10-22 13:49 UTC, seungpark commented on src/components/Target.js
> +  scroll-margin-top: 85px;
[minor] use the navbarScrollOffset value here

2024-10-22 15:18 UTC, biancalaube commented on src/components/Permalink.js
what exactly do you mean when you say make it an inline element, like should i change it from a styled div to a styled span ? or is there another way to make it an inline element

2024-10-22 15:29 UTC, biancalaube commented on src/components/Target.js
> +  scroll-margin-top: 85px;
thanks for that catch, fixed

2024-10-22 15:30 UTC, biancalaube commented on src/theme/docsTheme.js
> +  navbarScrollMobileOffset: '110px',
I think we do need an offset here, since it was using the 85px and it was still being hiding. I think its because the spacing is a little different in the mobile view on the paragraphs but basically it was using the 85px and it was still being hidden. I can try another way to fix the issue but Im unsure of what that would be.

2024-10-22 16:55 UTC, seungpark commented on src/theme/docsTheme.js
> +  navbarScrollMobileOffset: '110px',
i believe the comment above will alleviate that, since it will go from the top of the element and count, instead of wrapping another line

2024-10-22 19:50 UTC, seungpark reviewed
minor points: 1) can we update the docstheme so that navbar has more buffer space (dont need to add another, but we can increase the existing)

and 2) update the staging link pls! it is still on an old commit

2024-10-22 20:32 UTC, biancalaube commented
@seungpark , change the offset to be 95px but let me know if you want something different, staging links should work now!

2024-10-23 13:51 UTC, seungpark approved these changes
this LGTM!

2024-10-23 14:13 UTC, merged