DOP-931: Fix footnotes and footnote references
mongodb/snooty pull request #279
Opened 2020-09-04 01:41 UTC by mango-db

[DOP-931](https://jira.mongodb.org/browse/DOP-931). [Datalake with added footnotes](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-931/datalake/cgoecknerwald/DOP-931/).

2020-09-15 21:20 UTC, mango-db commented
Please note that the reason why the [current drivers' footnotes](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/cgoecknerwald/DOP-931/java/#mongodb-compatibility) are failing is because [the rST](https://github.com/mongodb/docs-ecosystem/blob/master/source/includes/language-compatibility-table-java.rst) is [incorrect](https://docutils.sourceforge.io/docs/user/rst/quickref.html#footnotes).

2020-09-28 14:50 UTC, mango-db commented
## Updated staging:

- [Drivers -- with named footnotes](https://docs-mongodborg-staging.corp.mongodb.com/DOP-931/drivers/cgoecknerwald/DOP-931/)
- [Drivers -- as is](https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/cgoecknerwald/DOP-931/
)
- [Datalake -- with added footnotes](https://docs-mongodborg-staging.corp.mongodb.com/DOP-931/datalake/cgoecknerwald/DOP-931/
)
- [Manual -- as is]()

2020-09-28 17:34 UTC, sophstad requested changes
In the first drivers staging link, I wasn't able to find a reference to footnote 2. Maybe it was just a mistake in the rST but wanted to flag!

2020-09-28 17:34 UTC, sophstad commented on src/components/Footnote.js
> +  const footnoteReferenceNodes = footnoteReferences.map(_ => (
Use of an underscore to ignore a variable is a Python-specific feature, meaning that this code is mapping the list of footnote references and assigning each reference to a variable named `_`.

Since we're never _using_ that variable `_`, I believe that associating multiple references with a single (named) footnote would not work. This isn't something that is crucial to support, but we should probably remove this mapping entirely so as not to suggest that each footnote reference is being linked to in the footnote.

2020-09-28 17:34 UTC, sophstad commented on src/components/FootnoteReference.js
> +  let ref = refname || id.replace('id', '');
[nit] The value of `ref` is never modified, so we can use `const`.
```suggestion
  const ref = refname || id.replace('id', '');
```

2020-09-28 17:34 UTC, sophstad commented on src/layouts/index.js
> +        footnote.id = '' + (index + 1);
Assuming the intent of the concatenation here was to make `footnote.id` into a string, a template literal may be clearer:
```suggestion
        footnote.id = `${index + 1}`;
```

2020-09-28 17:34 UTC, sophstad commented on src/layouts/index.js
> +    return 'id' + (index + 1);
[nit] Another nice opportunity to use a template literal:
```suggestion
    return `id${index + 1}`;
```

2020-09-29 18:34 UTC, sophstad approved these changes
Woohoo!!! Just one non-blocking comment 💯

2020-09-29 18:34 UTC, sophstad commented on src/components/Footnote.js
> +            <>
[nit] I don't think these fragments are necessary? These nodes are enclosed in `<td>` tags.

2020-09-29 19:07 UTC, mango-db commented on src/components/Footnote.js
> +            <>
Thanks for catching that!

2020-09-29 19:10 UTC, merged