Footnote-context: refresh footnotes before every render
mongodb/snooty pull request #292
Opened 2020-10-06 06:26 UTC by mango-db

Currently, footnotes were not being updated when navigating between sub-pages. (Example: try navigating from [/index](https://docs-mongodbcom-staging.corp.mongodb.com/footnotes-misc/datalake/cgoecknerwald/footnote-caching/) to [/reference](https://docs-mongodbcom-staging.corp.mongodb.com/footnotes-misc/datalake/cgoecknerwald/footnote-caching/reference) while watching the `footnotes` object logged to console -- see that it doesn't change until you refresh.)

While this change will cause additional calls to `getPageNodes` (formerly `preprocessPageNodes`), this additional computation is necessary to keep footnotes up-to-date while a user navigates.

## Staging
- [Datalake /index](https://docs-mongodborg-staging.corp.mongodb.com/footnotes-misc/datalake/cgoecknerwald/footnote-context/)
- [Datalake /reference](https://docs-mongodbcom-staging.corp.mongodb.com/footnotes-misc/datalake/cgoecknerwald/footnote-context/reference)
- [Datalake /administration](https://docs-mongodbcom-staging.corp.mongodb.com/footnotes-misc/datalake/cgoecknerwald/footnote-context/administration)
- [Drivers](https://docs-mongodborg-staging.corp.mongodb.com/master/drivers/cgoecknerwald/footnote-context/java)
- [Manual](https://docs-mongodborg-staging.corp.mongodb.com/master/manual/cgoecknerwald/footnote-context/)

2020-10-06 12:53 UTC, sophstad commented on src/layouts/index.js
> +    const footnotes = this.getFootnotes(pageNodes);
I'm not sure that these operations belong in the [`render()`](https://reactjs.org/docs/react-component.html#render) method, as they are somewhat computationally expensive; have you tried using [`componentDidUpdate()`](https://reactjs.org/docs/react-component.html#componentdidupdate)?

2020-10-06 12:53 UTC, sophstad commented on src/layouts/index.js
> +  getPageNodes = pageContext => {
What prompted this change? AFAICT, the bug could be fixed by running `preprocessPageNodes` upon route change.

2020-10-06 14:41 UTC, mango-db commented on src/layouts/index.js
> +    const footnotes = this.getFootnotes(pageNodes);
In this case, it seems that the` footnote`s within `pageNodes` are updating between page clicks, and `componentDidUpdate` runs too late in the lifecycle (i.e. after `render`) -- thus this implementation. As discussed, we will change this implementation to instantiate the footnote context provider at the page level rather than the layout level.

2020-10-07 15:56 UTC, mango-db commented
Staging has been updated to reflect changes.

2020-10-08 16:32 UTC, sophstad requested changes

2020-10-08 16:32 UTC, sophstad commented on src/components/DocumentBody.js
> +  const footnotes = getFootnotes(pageNodes);
This actually seems like a good opportunity to use a class component: we can call these only once in the `constructor()` and avoid the computational expense of calling them on every re-render, as is happening now.

2020-10-08 16:32 UTC, sophstad commented on src/components/DocumentBody.js
> +  };
I think we can move all of these functions outside the component since they do not rely on any `props` or other variables defined by the class.

2020-10-13 17:12 UTC, mango-db commented
Staging has been updated to reflect changes

2020-10-14 14:43 UTC, sophstad approved these changes

2020-10-14 15:54 UTC, merged