DOP-1544: Add Segment analytics
mongodb/snooty pull request #298
Opened 2020-10-14 20:54 UTC by mango-db

[DOP-1544](https://jira.mongodb.org/browse/DOP-1544).

2020-10-15 14:01 UTC, jestapinski reviewed
Looks good! Obviously I don't have as much context but I see the values being appropriately passed on the network tab. I'll defer to Sophie for the final LGTM

2020-10-15 22:02 UTC, sophstad requested changes

2020-10-15 22:02 UTC, sophstad commented on src/components/TabSelectors.js
> +                newValue: value,
These field names feel a bit vague to me — how about `languageInitial` and `languageSelected`?
```suggestion
                languageInitial: activeTabs[name],
                languageSelected: value,
```

2020-10-16 14:37 UTC, sophstad approved these changes

2020-10-16 14:47 UTC, merged