DOP-1604: Allow code blocks to render with caption
mongodb/snooty pull request #299
Opened 2020-10-15 15:30 UTC by rayangler

[[DOP-1604](https://jira.mongodb.org/browse/DOP-1604)]
[[Realms Staging /android/mongodb](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/raymundrodriguez/DOP-1604/android/mongodb)]

This PR introduces the inclusion of captions to code blocks. `caption` options are handled as strings. Code blocks now use `showWindowChrome`.

2020-10-15 18:33 UTC, sophstad requested changes
The A/C for this ticket definitely could have been more clear, but the goal is to show the caption in LeafyGreen's "chrome window" text, if it's specified. But so far so good—lemme know if I can clarify anything for you!

2020-10-15 18:33 UTC, sophstad commented on src/components/Code.js
> +          {caption}
Just flagging: once [this](https://github.com/mongodb/snooty-parser/pull/242#discussion_r505615068) is implemented, we'll probably need to use a `ComponentFactory` here to render the caption.

2020-10-15 18:33 UTC, sophstad commented on src/components/Code.js
> +  nodeData: { copyable, caption, emphasize_lines: emphasizeLines, lang = 'none', linenos, value },
Did you encounter a bug without this default `none` for `lang`? I recently changed this component to handle that in `getLanguage()`, so wondering if you're seeing something weird!

2020-10-15 18:33 UTC, sophstad commented on src/components/Code.js
> +      {caption && (
The ticket was definitely unclear about this, but we actually want to render the caption as the component's [`chromeTitle`](https://github.com/mongodb/leafygreen-ui/tree/master/packages/code#properties)`, if it exists!

2020-10-15 18:33 UTC, sophstad commented on src/components/Code.js
> +        showWindowChrome={true}
We only want this property to be `true` if a caption is specified.

2020-10-15 19:05 UTC, rayangler commented on src/components/Code.js
> +  nodeData: { copyable, caption, emphasize_lines: emphasizeLines, lang = 'none', linenos, value },
Ah, my mistake! I accidentally left `lang = 'none'` because of a merge conflict. I'll fix this

2020-10-15 19:05 UTC, rayangler commented on src/components/Code.js
> +      {caption && (
Oh, gotcha. Will change

2020-10-16 18:02 UTC, rayangler commented
With the recent [comment](https://jira.mongodb.org/browse/DOP-1639?focusedCommentId=3448465&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3448465) on DOP-1639, it seems like we do not need to worry about breaking the caption down into individual components. Captions are just strings now.

2020-10-19 17:19 UTC, sophstad approved these changes

2020-10-19 17:27 UTC, merged