DOP-1545: Build 404 page
mongodb/snooty pull request #317
Opened 2020-11-10 17:49 UTC by rayangler

[[JIRA Ticket](https://jira.mongodb.org/browse/DOP-1545)]
[[Landing Staging: /404](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/DOP-1545/404/)]

This PR introduces the creation of a 404 page for docs-landing, found at the slug `/404`.

2020-11-10 17:53 UTC, rayangler commented on src/components/Footer.js
> +      {enableFeedback && <FeedbackFooter />}
Not sure if we needed feedback to be available on a 404 page so this was my idea of bypassing this. If there's a better way to do this or if we do need feedback, I can go ahead and change this!

2020-11-11 15:17 UTC, sophstad requested changes
Great work Raymund! I left a few comments.

Also, not sure if you've been run this past @allisonmui9, but you can send the staged site over/add her as a reviewer on here (mostly thinking of the mobile 404 page since that wasn't included in the designs) [but thanks for going the extra mile to ensure that this looks good on small screens as well!].

2020-11-11 15:17 UTC, sophstad commented on src/components/NotFound.js
> +const SupportButton = styled('a')`
[nit] I think this would be clearer if it were named `SupportLink`, since we aren't actually intending for it to function as a button.

2020-11-11 15:17 UTC, sophstad commented on gatsby-node.js
> +  if (page.path === '/dev-404-page/' && process.env.GATSBY_SITE === 'landing') {
Interesting, I don't see `dev-404-page` anywhere else in this PR—is it a Gatsby pattern?

2020-11-11 15:29 UTC, rayangler commented on src/components/Footer.js
> +      {enableFeedback && <FeedbackFooter />}
Haha, good call! I originally called it `disableFeedback` but was concerned about if it would need default props or not so I turned it into `enableFeedback` as a "safer" bet. Will change!

2020-11-11 15:36 UTC, rayangler commented on gatsby-node.js
> +  if (page.path === '/dev-404-page/' && process.env.GATSBY_SITE === 'landing') {
`dev-404-page` is Gatsby's default 404 page when in development. If you go to any non-existent page while in development, such as `/asdf`, it will show you the 404 page (which for some reason is named `dev-404-page`). Alternatively, you can reach the same page by going directly to `/404`.

2020-11-13 18:52 UTC, sophstad approved these changes
Just one request. Thanks, Raymund!

2020-11-13 18:52 UTC, sophstad commented on gatsby-node.js
> +};
For the sake of keeping code clean in production, I think it may be good to remove this—assuming you can still develop for the page by going to `/404`. Correct me if this isn't the case!

2020-11-13 19:39 UTC, rayangler commented on gatsby-node.js
> +};
Yes, that is correct! Done!

2020-11-13 19:39 UTC, merged