DOP-1748: OpenAPI component updates page hash
mongodb/snooty pull request #327
Opened 2020-12-14 22:20 UTC by sophstad

[DOP-1748] [[Realm Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/sophstad/DOP-1748/admin/api/v3#realm-administrator-apis)]
- Update page hash when an OpenAPI card is expanded
- If URL includes page hash on load, automatically expand this card

@nlarew Added you as a reviewer for acceptance testing! Thanks in advance 😄

2020-12-15 00:49 UTC, nlarew commented
@sophstad LGTM on those two bullets! Thank you!

I'm still seeing one more minor issue - `:ref:` roles that point to a given endpoint don't actually point to the endpoint when resolved.

Not sure if it's something we can handle on the frontend or if it would require a parser update too.

e.g. consider this rst:

```
Application ID
~~~~~~~~~~~~~~

To find your Application ID, make a request to the {+service-short+}
:ref:`get-/groups/{groupid}/apps` API endpoint.
```

That ref _does_ render as a link but points to the top of the admin API page (i.e. it doesn't include the ref target in the URL hash)
![image](https://user-images.githubusercontent.com/15657698/102153351-01df2980-3e45-11eb-92cb-299fb6b5c339.png)

![image](https://user-images.githubusercontent.com/15657698/102153434-2f2bd780-3e45-11eb-85e5-dd10389006b7.png)

2020-12-15 19:08 UTC, nlarew approved these changes

2020-12-22 22:16 UTC, mango-db requested changes
1. I'm not seeing consistent scroll behavior on smaller screens - the scroll is usually above the card by a significant amount. (Is this possibly a separate issue?)
2. The toggle for `/​auth/​providers/​{provider}/​login` isn't maintained upon refresh
3. Upon refresh, card expansion and scroll causes the excess page state updates - watch the Search box

2021-01-12 19:16 UTC, mango-db approved these changes
As discussed, #1 is a separate issue, and we were unable to reproduce #3! LGTM

2021-01-12 19:17 UTC, merged