DOP-1838: Update top menu/navbar
mongodb/snooty pull request #352
Opened 2021-02-16 20:38 UTC by rayangler

[[Jira Ticket](https://jira.mongodb.org/browse/DOP-1838)]
[[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-1838/)]

**Main changes:**
*New navbar design*
- Navbar should match design (check desktop and mobile sizes).
- Menu button should make sidebar TOC appear. Functionality and layout of sidebar may change when work on the new sidebar is done.
- Search icon/bar should function the same. Changes to its position on mobile were made so that navbar contents are spaced more evenly.

*Removed divs*
- Old nested divs from legacy for both the `document` and `ecosystem-index` layouts have been removed/updated. Staged site and live site should pretty much look the same.

*Removed unused constants*
- Constants in `constants.js` that had no references to them have been removed.

2021-02-17 16:09 UTC, sophstad requested changes
This is great work! I have a few notes mainly focused on avoiding some of the navbar-related headaches I've had to deal with in the past 😅 there is a surprising amount of CSS-related tech debt in these components and you've done a great job of working through it!

2021-02-17 16:09 UTC, sophstad commented on src/components/Navbar.js
> +  height: 45px;
As part of this work I think it would really behoove us to move away from a fixed height navbar with a corresponding top margin applied to the content container. This has been a headache in the past as we've seen the navbar cover up content and have to do some extra work to make banners look good. It's probably a good idea to go with a flex box applied to the entire page using `flex-direction: column;` to provide some more, well, flexibility. Devhub is using this approach to great effect [here](https://github.com/mongodb/devhub/blob/staging/src/components/dev-hub/layout.js#L61-L62)!

2021-02-17 16:09 UTC, sophstad commented on src/components/Navbar.js
> +  padding-left: 20px;
We can probably apply some standardized x-margins to the `NavbarContainer` to ensure things stay symmetrical. This could also allow us to remove the right padding on the search bar [here](https://github.com/mongodb/snooty/blob/master/src/components/Searchbar/CondensedSearchbar.js#L19).

2021-02-17 17:11 UTC, rayangler commented on src/templates/document.js
> +      <MainColumn>
The component itself doesn't offer much in terms of logic or functionality but I created it as a separate component to house the `main-column` class css for future use (i.e. after css refactoring). `MainColumn` is also used in `ecosystem-index` [here](https://github.com/mongodb/snooty/pull/352/files#diff-3cc54f2f1eec9f4ea14e7a865956ce36cf1727fae2d655019bae03da8ae26828R9). 

Should I maybe save the css for `main-column` as reusable css and import it to each of the two layouts? Or maybe revert the `MainColumn` used in `ecosystem-index` to just be a `div` with `main-column` class again? I'm interested to get your opinion on this!

2021-02-17 20:52 UTC, sophstad commented on src/templates/document.js
> +      <MainColumn>
Ah you make a great point about the ecosystem index template (which is [way more hardcoded than it should be, anyway](https://jira.mongodb.org/browse/DOP-929)...). I think therefore your implemented approach makes a lot of sense — as we flesh out the rest of the new nav, we may need to make style changes, at which point having `MainColumn` separated from legacy CSS will come in handy. Thanks for pointing that out!

2021-02-23 19:58 UTC, rayangler commented on src/components/Navbar.js
> +  height: 45px;
Created [DOP-2004](https://jira.mongodb.org/browse/DOP-2004) to handle the rearrangement of components and css for the new grid layout

2021-02-23 20:45 UTC, sophstad commented on src/components/Navbar.js
> +import { Logo } from '@leafygreen-ui/logo';
[nit] General rule of thumb is to put external libraries first in the list of imports... I wish our linter caught this! 😤

2021-02-23 20:45 UTC, sophstad commented on src/components/Navbar.js
> +  color: #616161;
[nit] Perhaps we should switch to a LeafyGreen color here! https://www.mongodb.design/component/palette/example/

2021-02-23 20:45 UTC, sophstad commented on src/components/Searchbar/CondensedSearchbar.js
>    position: absolute;
Is it possible to get rid of this altogether now that we are moving towards a non-fixed layout? Rogue `position` rules can always come back to bite ya 😩 or maybe this will become addressable in DOP-2004!

2021-02-23 20:45 UTC, sophstad commented on src/components/Searchbar/Searchbar.js
> +    ${({ isExpanded }) => !isExpanded && 'position: static;'}
Ditto

2021-02-23 20:45 UTC, sophstad commented on src/components/SidebarMobileMenuButton.js
> +  }
Can we use the new `display-none.js` util here?

2021-02-23 20:45 UTC, sophstad commented on src/templates/document.js
> +            }
Have you noticed these `print` rules having an impact on render? Perhaps worth making a concerted effort to make sure that printing our pages looks good at the end of this work rather than adding in rules ad hoc now.

2021-02-23 21:34 UTC, sophstad commented
One more thing: do we still need [either of these files](https://github.com/mongodb/snooty/blob/master/Makefile#L41-L42)?

2021-02-24 20:08 UTC, rayangler commented on src/templates/document.js
> +            }
Good point! I have removed the current print statements for now

2021-02-25 17:47 UTC, sophstad approved these changes
Nice work, LGTM! I left a few comments, mostly just to flag stuff that may be relevant to the grid implementation.

Also, should [this line](https://github.com/mongodb/snooty/blob/master/src/html.js#L37) be deleted?

2021-02-25 17:47 UTC, sophstad commented on src/components/Navbar.js
> +  position: fixed;
Another `position` rule 😤 perhaps another rule that will go away with CSS grid?

2021-02-25 17:47 UTC, sophstad commented on src/components/Navbar.js
> +  z-index: 9999;
This is probably something else we should get rid of with grid

2021-02-25 17:47 UTC, sophstad commented on src/components/Searchbar/ExpandedSearchbar.js
> +  display: flex;
Something to keep in mind when you start working on grid stuff: Would it preferable to use a grid approach here too? I am wary of mixing two approaches so at least something to think about!

2021-02-25 17:47 UTC, sophstad commented on src/components/Searchbar/SearchTextInput.js
> +  // color: ${uiColors.gray.dark3};
Intentional?

2021-02-25 17:47 UTC, sophstad commented on src/components/Searchbar/SearchTextInput.js
> +    // color: ${uiColors.gray.dark1};
Ditto

2021-02-25 18:02 UTC, rayangler commented on src/components/Navbar.js
> +  position: fixed;
Yup, I kept this `position` here to keep the navbar up fixed at the top while scrolling. I hope to remove this when I get the grid layout working properly

2021-02-25 18:05 UTC, rayangler commented on src/components/Searchbar/ExpandedSearchbar.js
> +  display: flex;
I'm not too sure yet tbh. We could certainly opt to transition into using `grid` instead of `flex` for certain things. However, my understanding was that `flex` was very good for one-dimensional layouts (such as this horizontal searchbar) while `grid` is very useful for two-dimensional layouts.

2021-02-25 18:05 UTC, rayangler commented on src/components/Searchbar/SearchTextInput.js
> +  // color: ${uiColors.gray.dark3};
Definitely not intentional. Thanks for catching!

2021-02-25 18:07 UTC, rayangler commented
> Also, should [this line](https://github.com/mongodb/snooty/blob/master/src/html.js#L37) be deleted?

That line should already have been deleted in one of the more recent [commits](https://github.com/mongodb/snooty/pull/352/files#diff-023eb4be0e5096f5a778ef1dfee421162b529c473ad2c2c7f3e12534eeaa44b7L37)!

2021-02-25 18:43 UTC, merged