DOP-1935: Implement Kicker directive and landing project/template
mongodb/snooty pull request #362
Opened 2021-02-25 22:47 UTC by mango-db

[PLP-POC staging](https://docs-mongodbcom-staging.corp.mongodb.com/plp-poc/compass/cgoecknerwald/DOP-1935/).

2021-02-26 17:02 UTC, sophstad requested changes
Re: the `package-lock.json` commits, can you update to npm 7? That release introduced a new package-lock.json format which is what is in use now in Snooty. The lockfile shouldn't have changed here since there's no `package.json` update.

2021-02-26 17:02 UTC, sophstad commented on src/utils/get-template.js
> +      return project === 'landing' ? Landing : Document;
To me, this seems to convolute the straightforward approach that the `:template:` page option currently uses. Would it be reasonable to omit the `:template: landing` option entirely?

2021-03-01 15:03 UTC, sophstad requested changes

2021-03-01 15:03 UTC, sophstad commented on src/components/landing/Kicker.js
> +    {children.map((child, i) => (
This PR originally rendered the `argument` field of the node and I believe that is what the `rstspec.toml` implies too? Just want to make sure we're rendering the content correctly!

2021-03-01 15:03 UTC, sophstad commented on src/layouts/index.js
> +          <Template {...props}>{project === 'landing' ? [children] : children}</Template>
Ooh just wondering, what were your findings about this?

2021-03-01 15:03 UTC, sophstad commented on src/templates/document.js
> +  const isLanding = project === 'compass' && slug === '/';
Given that landing pages are going to be added to multiple repositories (and we don't want to require a Snooty release in order to deploy them), I don't think this condition is flexible enough. It would be ideal to avoid hardcoding repo names altogether!

2021-03-01 19:50 UTC, mango-db commented on src/layouts/index.js
> +          <Template {...props}>{project === 'landing' ? [children] : children}</Template>
It appears to be a way to work around required PropType warnings - I've modified the PropType of the Landing component to accept children as an object, as well as an array.

2021-03-02 19:12 UTC, mango-db commented
Staging has been updated to reflect changes.

2021-03-02 19:59 UTC, mango-db commented
Staging has been updated to reflect changes.

2021-03-02 20:05 UTC, sophstad approved these changes
LGTM, just some GitHub Actions warnings to fix!

2021-03-02 20:05 UTC, sophstad commented on src/components/landing/Kicker.js
> +    children: PropTypes.arrayOf(PropTypes.object).isRequired,
Should be `argument`

2021-03-02 20:05 UTC, sophstad commented on src/layouts/index.js
> +          <Template {...props}>{children}</Template>
Nice 👍

2021-03-02 20:25 UTC, merged