DOP-2004: Apply global grid layout
mongodb/snooty pull request #363
Opened 2021-02-26 21:58 UTC by rayangler

[[Jira Ticket](https://jira.mongodb.org/browse/DOP-2004)]
[[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/landing/raymundrodriguez/DOP-2004/)]
[[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-2004/)]
[[Atlas Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/raymundrodriguez/DOP-2004/)]

Summary:
* Used `grid` to create top level layout for header (navbar), sidebar, and content. This should allow the major templates to generally look the same as the current site.
* Refactored choosing active heading for `Contents` using `Intersection Observer API`. Allows `Contents` to work with new layout (and I think it's supposed to be more modern than relying on `scroll` events).

2021-03-03 21:38 UTC, sophstad reviewed
A few questions! There's a lot to untangle in our layouts, I suppose 😩

2021-03-03 21:38 UTC, sophstad commented on src/layouts/index.js
> +                >
Do you think this outer `<div>` can be removed when we start using LG's `SideNav`? (just for my own clarification!)

2021-03-03 21:38 UTC, sophstad commented on src/components/MainColumn.js
>        max-width: 800px;
I feel like `display: inline-block;` doesn't make sense here? Perhaps some legacy code we can nix! The `flex-grow`, `justify-content`, and `-ms-flex-*` rules are also maybe vestiges of the flexbox implementation that we can nix now that `MainColumn` is a part of a grid

2021-03-03 21:38 UTC, sophstad commented on src/templates/document.js
>        <MainColumn>
Just wondering: is there any reason the `.content` classname can't be applied to `MainColumn`? That could knock out a bit of extra cruft.

2021-03-05 22:43 UTC, rayangler commented on src/templates/landing.js
> -const Wrapper = styled('main')`
Changed this back since this was actually something I left by mistake! I meant to keep the `Wrapper` as `main` and its container as a `div`

2021-03-05 22:47 UTC, rayangler commented on src/components/sidebar-context.js
> -const SidebarContextProvider = ({ children }) => {
I decided that I'd prefer to keep the current implementation as is. I was getting a random error when I tried to do something like you suggested, but I think it also makes sense to keep this as-is since we directly use `isMobileMenuOpen`'s state in `index.js`. This would also follow the pattern that `SearchContext` follows. Open to future changes for conformity though!

2021-03-05 22:48 UTC, rayangler commented on src/layouts/index.js
> +  const renderStatus = isBrowser ? style.postRender : '';
I’m not exactly sure. I kept this around when I transferred this code over from [document.js](https://github.com/mongodb/snooty/blob/master/src/templates/document.js#L25). It was brought in to fix the issue seen in [DOP-873](https://jira.mongodb.org/browse/DOP-873).   

Since `isBrowser` would typically be true after being rendered on a browser, it makes sense that this boolean would be used for a styling meant for a post-render. (Removing it didn’t seem to cause any issues though.) My hope was that this styling would be unnecessary with the implementation of the new sidebar and we could just decide to remove it then.

2021-03-05 22:50 UTC, rayangler commented on src/layouts/index.js
> +                >
Yes, for sure! It seems like it only exists to contain the current `Sidebar` that we have.

2021-03-05 22:56 UTC, rayangler commented on src/templates/document.js
>        <MainColumn>
Good point! I decided to move the class's styling for font and line height to [body](https://github.com/mongodb/snooty/pull/363/files#diff-fe6b5f1430d78777f1dcebf229294971ed452eb6f104e8d526df0f082fb7a684R18-R20) to allow `MainColumn` and `RightColumn` and any other children of the different templates to utilize that styling. But maybe it's something we should keep to `MainColumn` and add to `RightColumn` specifically? I'd like to get your opinion on this.

2021-03-05 23:00 UTC, rayangler commented
Updated the staging links to separate all of the templates!

I decided to pass `className` instead of using `...props` to the templates because (1) we specifically want the `className` for the containing div of each template to be used for the purpose of css anyways, and (2) adding `{...props}` to a `div` like that would cause all props from `layouts/index.js` to be passed unnecessarily.

2021-03-08 15:18 UTC, sophstad requested changes

2021-03-08 15:18 UTC, sophstad commented on src/templates/blank.js
> +const Blank = ({ children, className }) => (
I recently spoke to Allison M about the [`/legacy` page](https://docs.mongodb.com/legacy/), which uses the `blank` template. I think we want to preserve the total blankness of these pages (i.e. no sidebar). It looks like your staging link's /legacy page still has the sidebar ([here](https://docs.mongodb.com/legacy/)), so would appreciate moving this to total blank behavior! Sorry for the lack of clarity there.

2021-03-08 15:32 UTC, rayangler commented on src/templates/blank.js
> +      display: flex;
This was an attempt at realigning the contents within the `blank` template to be more like how they are on the live site. I'll change this up with some padding/margins instead!

2021-03-08 15:35 UTC, rayangler commented on src/templates/blank.js
> +const Blank = ({ children, className }) => (
So we want to keep the sidebar for `/search` and not `/legacy`, right?

2021-03-08 15:40 UTC, sophstad commented on src/templates/blank.js
> +const Blank = ({ children, className }) => (
Yeah! I think we ultimately ought to change the `:template:` field for the search page ([source](https://github.com/mongodb/docs-landing/blob/master/source/search.txt#L1)) as it's not truly "blank" anymore. It seems like it's going to be using more or less the `landing` template, don't you think?

(I wish we had a better naming system for our templates 😁)

2021-03-10 21:52 UTC, sophstad requested changes

2021-03-10 21:52 UTC, sophstad commented on src/components/Searchbar/ExpandedSearchbar.js
> +  transition: background-color 150ms ease-in;
This line applies the fade-in fade-out animations you see when navigating between pages on legacy. It doesn't seem to be working on next gen (and imo feels slightly slow on legacy), so maybe we could just remove it?

2021-03-10 21:52 UTC, sophstad commented on src/components/Navbar.js
>    z-index: 9999;
I couldn't find a side-effect of removing this—unless you know of one, let's get rid of it so as to avoid extraneous z-indexes!

2021-03-10 21:52 UTC, sophstad commented on src/components/Navbar.js
> +  position: relative;
Interesting, where did you notice the shadow issue? I can't reproduce.

2021-03-10 21:52 UTC, sophstad commented on src/components/Navbar.js
> +  isBlankTemplate: PropTypes.bool,
Did you mean `isSidebarEnabled`?

2021-03-10 21:52 UTC, sophstad commented on src/components/SidebarMobileMenuButton.js
> +        <Icon glyph={isSidebarMenuOpen && isBrowser ? 'X' : 'Menu'} size="large" />
Interesting, did this fail without an `isBrowser` check? That seems unexpected!

2021-03-10 21:52 UTC, sophstad commented on src/components/contents-context.js
> +    let defaultActiveSectionId = window.location.hash.slice(1) || headingNodes[0]?.id;
[nit] The ultimate safest way to do this would be:
```suggestion
    let defaultActiveSectionId = window.location.hash.slice(1) || headingNodes?.[0]?.id;
```

2021-03-10 21:52 UTC, sophstad commented on src/layouts/index.js
> +  const isSidebarEnabled = template !== 'blank';
Interesting approach... I like how this allows us to not repeat the sidebar code in each template, but also worry that perhaps it obfuscates the actual behavior of each template (i.e. what's included in the template file is not necessarily what you get via render). What was your thinking here?

2021-03-11 15:05 UTC, rayangler commented on src/components/Searchbar/ExpandedSearchbar.js
> +  transition: background-color 150ms ease-in;
This transition is for the `ExpandedSearchbar` in particular. It's used when hovering over the searchbar itself. I realized that I needed to move where the transition [previously was](https://github.com/mongodb/snooty/pull/363/files/670c9174bbae7a54ee92ee5c2b37213e51f859d6#diff-fc8ec9a68dc65b81d0503a31a47c094dd2f7c0a57fcd8fc2d89681d4b042713eL18) after the previous `docs-nav` ticket rearranged some searchbar stuff. The change is subtle but I decided to just keep it anyways.

Could [this](https://github.com/mongodb/snooty/pull/363/files/670c9174bbae7a54ee92ee5c2b37213e51f859d6#diff-e79e4c2c4c39a8e639b6c2f0d78c7717e5d614c1aa095500ed80e02d223a3ba7L18) be the transition you were referring to?

2021-03-11 15:08 UTC, rayangler commented on src/components/Navbar.js
> +  position: relative;
If you remove the `z-index` and/or `position: relative`, the box shadow of the navbar can sometimes be covered by other components while scrolling down. This is most noticeable with LG components such as a code block. Here is an example page: ([link](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-2004/c/)).

2021-03-11 15:09 UTC, rayangler commented on src/components/Navbar.js
>    z-index: 9999;
Please refer to the [other comment](https://github.com/mongodb/snooty/pull/363#discussion_r592440008) pertaining to the box shadow!

2021-03-11 15:10 UTC, rayangler commented on src/components/Navbar.js
> +  isBlankTemplate: PropTypes.bool,
Thanks for catching this! I meant to remove this after introducing `isSidebarEnabled` to this component as part of context

2021-03-11 15:16 UTC, rayangler commented on src/components/SidebarMobileMenuButton.js
> +        <Icon glyph={isSidebarMenuOpen && isBrowser ? 'X' : 'Menu'} size="large" />
In an attempt to [simplify](https://github.com/mongodb/snooty/pull/363/files/670c9174bbae7a54ee92ee5c2b37213e51f859d6#diff-a5373604f289396d47dac4670c26c970cea3ab77a0e9dd24c78c82b5484fa798R31) the [previous logic](https://github.com/mongodb/snooty/pull/363/files/670c9174bbae7a54ee92ee5c2b37213e51f859d6#diff-4ed84ff2669e916bd0ac773815d1678118db7bdc226291c85a0e7c4befa038abL43) for showing the sidenav, this causes a side-effect due to the `useScreenSize` we use to determine whether to show the sidenav by default or not on desktop vs. mobile. Without checking to see if `isBrowser` now, the glyph ends up flashing as `X` before becoming `Menu`.

I wonder if it might even be better to just return the logic the way it was since `isMobileMenuOpen` didn't need to depend on `useScreenSize` previously.

2021-03-11 15:28 UTC, rayangler commented on src/components/contents-context.js
> +    let defaultActiveSectionId = window.location.hash.slice(1) || headingNodes[0]?.id;
Despite being the ultimate safest way to do this, I wonder if this is necessary. `headingNodes` should be expected to exist because we get it from [`findHeadings`](https://github.com/mongodb/snooty/pull/363/files/670c9174bbae7a54ee92ee5c2b37213e51f859d6#diff-b45effd2f2fad9df3bc7f776ee52abfa2b52a8f9a73ea8648d4ba355fd383a7fR13), which at the very least should return an empty array.

2021-03-11 16:03 UTC, rayangler commented on src/layouts/index.js
> +  const isSidebarEnabled = template !== 'blank';
My thinking was to follow a pattern of having the content (template), the navbar, and the sidenav in the same layout since that is what was expected of the high level grid layout we have/would expect for the site. I was also thinking that if we wanted to expand disabling the sidebar for more templates in the future, we could have some sort of array to keep track of them all.

I saw the template as more of a template for the actual content on the page as opposed to the overall layout of the page. I'm not opposed to moving the sidebar/sidenav component into each template though. It was more of a choice based on how I saw layout vs. template 😅

2021-03-11 16:23 UTC, sophstad commented on src/components/Searchbar/ExpandedSearchbar.js
> +  transition: background-color 150ms ease-in;
Ah yep totally! My bad!

2021-03-11 21:18 UTC, sophstad commented on src/components/Navbar.js
> +  position: relative;
Ah I see now 😭 good catch!

2021-03-15 20:32 UTC, sophstad approved these changes
LGTM! I'm happy to go with this approach for templates, we can always change it in the future if need be. Thanks Raymund!!

2021-03-15 21:43 UTC, merged