DOP-2027: Split Landing template, add Procedure and Step components
mongodb/snooty pull request #366
Opened 2021-03-05 19:59 UTC by mango-db

[Compass](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/plp/).

2021-03-19 19:16 UTC, sophstad requested changes

2021-03-19 19:16 UTC, sophstad commented on src/templates/product-landing.js
> +            font-size: 21px;
It'd be nice to stay within our theme values here — is `24px` too big?

2021-03-19 19:16 UTC, sophstad commented on src/components/Tabs.js
> +const useTabStyling = (screenSize, size) => {
[nit] Starting a function name with `use` is a convention associated with React Hooks (i.e. is related to component state), so would be preferable to rename this.

2021-03-19 19:16 UTC, sophstad commented on src/components/Tabs.js
> +  `;
Is there any reason to include this component in the function? I think it would be clearer if it were independent.

2021-03-19 19:16 UTC, sophstad commented on src/components/Tabs.js
>  import { css } from '@emotion/core';
Probably preferable to no longer import this and use LeafyGreen's `css` prop throughout the file.

2021-03-19 20:33 UTC, allisonmui9 commented on src/templates/product-landing.js
> +            font-size: 21px;
Yeah - 24px is a bit too big & conflicts with the main title styling. Is there a size between 24px and 16px?

2021-03-19 21:05 UTC, mango-db commented on src/templates/product-landing.js
> +            font-size: 21px;
No, there is not:

```
const fontSize = {
  xsmall: '11px',
  tiny: '12px',
  small: '14px',
  default: '16px',
  h1: '36px',
  h2: '24px',
  h3: '18px',
  h4: '16px',
};
```

2021-03-19 23:05 UTC, rayangler reviewed
The page looks great! Just left a few comments on some small things

2021-03-23 16:40 UTC, mango-db commented on src/components/Tabs.js
> +  `;
`StyledTabs` depends on `LandingTabsStyling`, which depends on `screenSize` and `size` information, which can only be accessed via the `useTheme` hook, so I have to leave it in

2021-03-25 03:41 UTC, mango-db commented
Thanks for the feedback, all! Staging has been updated to reflect changes.

2021-03-25 20:51 UTC, sophstad requested changes
Just some minor notes!

2021-03-25 22:43 UTC, rayangler requested changes
Added a couple more comments. Thanks for taking the time to work with all of the theme stuff I keep bringing up! 😅

Side notes: When resizing the width of page of the PLP, I see the feedback heading appearing at the top of the page, and the text in the cards at the bottom are highlighted blue. Is that expected? The homepage looks fine though

2021-03-25 22:43 UTC, rayangler commented on src/templates/product-landing.js
> +  const Wrapper = getWrapper(useTheme());
Is `getWrapper` necessary as a function here? It may be possible to just use your previous implementation of:
```
const Wrapper = styled('main')`
  // css
`;
```

2021-03-26 00:53 UTC, mango-db commented on src/components/Tabs.js
> +  const { styleTab } = getTabStyling(theme);
Reworked them a little to simplify

2021-03-26 00:54 UTC, mango-db commented on src/templates/product-landing.js
> +      </Helmet>
Removed since it wasn't doing anything anyways - title is "What is MongoDB Compass? - MongoDB Compass", per usual.

2021-03-26 01:10 UTC, mango-db commented
> PLP, I see the feedback heading appearing at the top of the page, and the text in the cards at the bottom are highlighted blue. Is that expected? The homepage looks fine though

The Card text will be handled in the next PR (for ease of CSS application here - the Cards are wrapped in an `<a>` tag, so they are catching the new blue font color)

2021-03-26 02:06 UTC, mango-db commented on src/templates/product-landing.js
> +  const Wrapper = getWrapper(useTheme());
Cleaned up - thanks for the suggestion!

2021-03-26 02:06 UTC, mango-db commented on src/templates/product-landing.js
> +const getWrapper = ({ fontSize, screenSize, size }) => {
Done - thanks for pointing that out! I standardized it in Procedure as well

2021-03-26 02:07 UTC, mango-db commented
Staging has been updated to reflect changes.

2021-03-29 14:45 UTC, rayangler approved these changes
LGTM! Thanks for addressing my comments!

2021-03-29 18:50 UTC, mango-db commented
Staging has been updated to reflect changes.

2021-03-30 15:10 UTC, sophstad approved these changes
Woohoo!!!

2021-03-30 15:10 UTC, sophstad commented on src/components/landing/Kicker.js
> +  `;
Looks like this can be moved outside of the component now!

2021-03-31 20:15 UTC, merged