DOP-1939: Add Button component and tests, with styling in Introduction
mongodb/snooty pull request #374
Opened 2021-03-25 17:31 UTC by mango-db

[[DOP-2027]](https://jira.mongodb.org/browse/DOP-1939): Handle and render the new button directive.
[[Figma]](https://www.figma.com/file/BJLheYUTCPkY7KoiaumVHA/PLP-Template?node-id=0%3A1).
[[docs-compass with PLP]](https://github.com/mongodb/docs-compass/tree/DOP-1979)

### Changes:

- Add Button component and test
- Add Button styling to Introduction class (

### Staging:
[Compass with PLP](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/DOP-1939/).

### .env vars
```
GATSBY_SITE=compass
GATSBY_PARSER_USER=cgoecknerwald
GATSBY_PARSER_BRANCH=DOP-1979
GATSBY_SNOOTY_DEV=true
```

2021-03-26 02:20 UTC, mango-db commented
Staging has been updated to reflect changes.

2021-03-30 15:48 UTC, sophstad requested changes

2021-03-30 15:48 UTC, sophstad commented on src/components/landing/Introduction.js
> +  const StyledIntroduction = styled('div')`
This can be moved outside of the component

2021-03-30 15:48 UTC, sophstad commented on src/components/landing/Introduction.js
> +        font-family: 'Fira Mono';
I believe Fira Mono is a default font included with Firefox; we don't reliably load it with docs. If you want to enforce a monospace font, perhaps you could include the monospace `fontFamilies` token from LeafyGreen [here](https://www.mongodb.design/component/tokens/example/).

2021-03-30 15:48 UTC, sophstad commented on src/components/landing/Introduction.js
> +      margin-right: ${theme.size.default};
[nit] Could use `margin` shorthand
```suggestion
      margin: ${theme.size.medium} ${theme.size.default} ${theme.size.default} 0;
```

2021-04-01 17:05 UTC, rayangler requested changes

2021-04-02 17:21 UTC, mango-db commented on src/components/landing/Introduction.js
> +        font-family: 'Fira Mono';
Resolved - going to use default Unicode "heavy wide-headed rightwards arrow" U+2794

2021-04-02 17:58 UTC, rayangler approved these changes
The issue I was running into with the button link mysteriously disappeared! LGTM

2021-04-07 14:18 UTC, sophstad requested changes

2021-04-07 14:18 UTC, sophstad commented on src/components/landing/Button.js
> +    <LeafyButton className="button" as={Link} variant="primary" href={withPrefix(uri)}>
I think the `as={Link}` prop should make `withPrefix()` redundant? Using it could also introduce other problems—e.g. if the `uri` refers to an absolute URL and we try to append the prefix before `https://`. `Link` handles all of this logic for us.

2021-04-07 16:28 UTC, sophstad approved these changes
LGTM, just one design note!

2021-04-07 16:28 UTC, sophstad commented on src/components/landing/Introduction.js
> +    a:after {
Do we want a hover state on this link?

2021-04-07 17:12 UTC, mango-db commented on src/components/landing/Introduction.js
> +    a:after {
No, hover state was requested removed by design!

2021-04-07 17:26 UTC, merged