Dop 1620
mongodb/snooty pull request #375
Opened 2021-03-26 23:29 UTC by casthewiz

### Stories/Links:
[DOP-1620](https://jira.mongodb.org/browse/DOP-1620)

### Staging Links:
https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/cassidy.schaufele/DOP-1620/

### Notes:
- Replaces native html `abbr` with `inline-definition` component from LeafyGreen inside of `Abbr` component implementation
- ridealong adds a pull request template to the repo

#### New Implementation:
<img width="715" alt="Screen Shot 2021-03-26 at 4 58 47 PM" src="https://user-images.githubusercontent.com/3813528/112702333-c2b77000-8e58-11eb-917b-e2f805c3e6d5.png">

2021-03-29 14:51 UTC, casthewiz commented on package.json
> +    "*": [
We currently run both 
```
"npm run format:fix",
"npm run lint:fix"
```
in `.github/workflows/test.yml` on every pull request - it makes sense to me to run the pre-commit hook for any file format changes then - this way other formats don't slip through the cracks (.md files, for example)

Totally open for discussion 😄

2021-03-29 14:53 UTC, casthewiz commented on .eslintrc.js
> +  ignorePatterns: ['docs-tools/', 'node_modules/', 'public/', '*.json'],
With precommit hooks enabled, we were running eslint on `.json` files. We could take a closer look at the file format matching rules in the package.json, but this seemed like the quickest way to stop them from being false negatives.

2021-03-29 14:59 UTC, casthewiz commented
The changes I've made in package.json allow husky to run linting as a pre-commit hook - essentially, we won't be able to commit unless the linting rules run and succeed, similar to our current linting in CI via github actions. 

**Failure State**
<img width="505" alt="Screen Shot 2021-03-29 at 8 58 03 AM" src="https://user-images.githubusercontent.com/3813528/112856331-e9e68b00-906c-11eb-803b-2193f5437ede.png">

**Success State**
<img width="511" alt="Screen Shot 2021-03-29 at 8 43 32 AM" src="https://user-images.githubusercontent.com/3813528/112854781-67a99700-906b-11eb-87c9-424c91330988.png">

Very open to discussion & thoughts around this 😄

2021-03-29 18:05 UTC, sophstad approved these changes
Sweet, thanks for adding the PR template! Also just fyi, titling the PR with the ticket name at the beginning (e.g. "DOP-1620 [Optional details]") will allow the JIRA webhook to pick it up.

2021-03-29 18:05 UTC, sophstad commented on .github/pull_request_template.md
> +[Story Number](Url of Story)
We use GitHub's [autolinked references](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls) for our JIRA project, so only the ticket number is really necessary. Maybe something like this?
```suggestion
DOP-NNNN
```

2021-03-29 18:13 UTC, rayangler requested changes

2021-03-29 18:53 UTC, casthewiz commented on src/components/Roles/Abbr.js
> +  return <InlineDefinition definition={expansion}>{abbr}</InlineDefinition>;
Mmh, good catch

I'll add a test around that as well 👍

2021-03-30 14:08 UTC, rayangler commented on src/components/Roles/Abbr.js
>    return <abbr title={expansion}>{abbr}</abbr>;
The last commit seems to have removed the LeafyGreen component!

2021-03-30 15:16 UTC, rayangler approved these changes
LGTM!

2021-03-31 21:01 UTC, merged