DOP-1846: Add ProductsList component
mongodb/snooty pull request #381
Opened 2021-04-12 19:09 UTC by rayangler

### Stories/Links:

DOP-1846

### Staging Links:

[Drivers Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/drivers/raymundrodriguez/DOP-1846/)
[Landing Staging](https://docs-mongodbcom-staging.corp.mongodb.com/docs-nav/landing/raymundrodriguez/DOP-1846/)

### Notes:
* Removed usage of `Sidebar` and replaced with empty LG `SideNav` for demo of new component.
* Added `ProductsList` component ("View all Products").
* Added page option to show `ProductsList` on specific pages only: `index` and `search` of `docs-landing`. ([Example commit](https://github.com/rayangler/docs-landing/commit/6ad23868a3deb6238907842742a4abb94f64ab71))

2021-04-12 20:10 UTC, sophstad requested changes
This is looking awesome, Raymund!

2021-04-12 20:10 UTC, sophstad commented on src/components/ProductsList.js
> +  }, [database, setProducts]);
I think this data ultimately should not be fetched client-side. The spec says

> Upon build of the docs-landing repo, Realm will be used to query for all of the documents in the collection.

and I think since the component is not used across repos, situating it in `gatsby-node.js` would optimize the user experience (i.e., this data is included in the static HTML). A great approach here may be to [create GraphQL nodes](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createNode) to query with a [static query](https://www.gatsbyjs.com/docs/how-to/querying-data/use-static-query/). [This](https://www.gatsbyjs.com/docs/conceptual/data-fetching/) is another doc I find helpful—let me know if you'd like to hop on a call to discuss any of this!

2021-04-12 20:10 UTC, sophstad commented on src/components/ProductsList.js
> +    font-weight: bold;
I think applying `font-weight: bold` here is causing some layout shifts across the other list items. This is kinda surprising because it is usually a pattern seen with horizontal layouts ([source](https://css-tricks.com/bold-on-hover-without-the-layout-shift/)). Perhaps it has to do with the `line-height` of each `<li>`?

https://user-images.githubusercontent.com/9298431/114454925-222bb480-9ba9-11eb-9bcb-4af06e3a8dcd.mov

2021-04-12 20:10 UTC, sophstad commented on src/layouts/index.js
> -                {isSidebarEnabled && <Sidenav pageContext={pageContext} />}
This seems like the right call to me 👍

2021-04-12 20:10 UTC, sophstad commented on src/components/Sidenav.js
> +  const showAllProducts = pageContext?.page?.options?.['nav-show-all-products'];
This is a great approach! 💯

2021-04-13 15:06 UTC, rayangler commented on src/components/ProductsList.js
> +    font-weight: bold;
Thanks for noticing the shifting! I switched around where the padding was being added so that hovering over a product shouldn't cause other list items to shift

2021-04-13 15:06 UTC, rayangler commented on src/components/ProductsList.js
> +  }, [database, setProducts]);
Thanks for the docs! Super helpful

2021-04-13 15:50 UTC, sophstad requested changes

2021-04-13 15:50 UTC, sophstad commented on gatsby-node.js
> +    });
AFAICT `children` and `parent` are required properties:
```suggestion
      parent: null,
      children: [],
    });
```

2021-04-13 15:50 UTC, sophstad commented on src/components/ProductsList.js
> +  color: ${(props) => (props.isOpen ? uiColors.gray.dark3 : uiColors.gray.dark1)};
[nit] Could tidy up 🧹 
```suggestion
  color: ${({ isOpen }) => (isOpen ? uiColors.gray.dark3 : uiColors.gray.dark1)};
```

2021-04-13 15:50 UTC, sophstad commented on src/components/Sidenav.js
> +    <StyledLeafygreenSideNav aria-label="Side navigation">
So much simpler! *chef's kiss*

2021-04-13 15:50 UTC, sophstad commented on src/templates/document.js
> +      <Sidenav pageContext={pageContext} />
We can probably get away with just passing the `page` property of `pageContext` here, since only the `page.options` object is used by `Sidenav`.

2021-04-13 15:50 UTC, sophstad commented on src/templates/landing.js
> +  }).isRequired,
[nit] Maybe extraneous since none of these props are used by this component

2021-04-13 15:50 UTC, sophstad commented on tests/unit/Banner.test.js
> +
This is probably unnecessary after moving the Realm call to the server!

2021-04-13 18:17 UTC, sophstad commented on src/components/SidebarMobileMenuButton.js
> +      <MenuButton aria-label="View sidenav" onClick={clickMenu}>
It looks like the menu button has kinda lost control of the side nav. Is this something worth addressing later/with LeafyGreen, or should it be working now?

https://user-images.githubusercontent.com/9298431/114600675-98d8b880-9c62-11eb-8c75-f84caad9f067.mov

2021-04-13 18:17 UTC, sophstad commented on src/components/ProductsList.js
> +  :hover {
I think this hover state looks slightly awkward when it causes an entry to break onto a new line on hover. This may also be addressed by the wider `SideNav` component, so let's keep an eye on it.

2021-04-13 18:17 UTC, sophstad commented on src/components/ProductsList.js
> +  ${({ isOpen }) => !isOpen && 'display: none;'}
Nice 💯

2021-04-13 18:55 UTC, rayangler commented on src/components/SidebarMobileMenuButton.js
> +      <MenuButton aria-label="View sidenav" onClick={clickMenu}>
I think this could be one of the potential asks for LeafyGreen. It would be nice to have a way to pass a collapsed/expanded state to the LG `SideNav`. (This would also help with the design for screen sizes ≤ 767px that have the `SideNav` closed by default)

It would be possible to have that menu button control the `display` of the `SideNav` as it currently is, but the following scenario might make it buggy:
1) Close/collapse the `SideNav` on a screen size > 420px using the `SideNav`'s collapse button.
2) Change the screen size to ≤ 420px.
3) Use the menu button to control the `display` of the `SideNav`.
4) The items in the `SideNav` will not be visible unless hovering over them because the `SideNav` would still be in its closed state.

An alternative solution (that just came to mind) to the above scenario may be to have our `Sidenav` component use a completely different parent element instead of the LG `SideNav` when on mobile screen size! (But having a way to control the state for screen sizes > 420px and ≤ 767px would still be good)

2021-04-13 18:57 UTC, rayangler commented on src/components/SidebarMobileMenuButton.js
> +      <MenuButton aria-label="View sidenav" onClick={clickMenu}>
I'm happy to continue looking into other options in the meantime, but I'm also good with addressing all sidenav-related stuff in DOP-1839

2021-04-13 18:59 UTC, rayangler commented on src/components/ProductsList.js
> +  :hover {
Yeah, I'm not too sure what to do about it at the moment or how it could be handled to make it less awkward. I'm hoping a wider component will help

2021-04-13 19:54 UTC, sophstad commented on src/components/SidebarMobileMenuButton.js
> +      <MenuButton aria-label="View sidenav" onClick={clickMenu}>
Yup I think this makes perfect sense, so let's raise with them. Thanks!

2021-04-13 20:19 UTC, sophstad approved these changes

2021-04-13 21:15 UTC, merged