DOP-2063: Compact Card addition
mongodb/snooty pull request #386
Opened 2021-04-20 00:22 UTC by mango-db

### Stories/Links:

[DOP-2063](https://jira.mongodb.org/browse/DOP-2063).

### Staging Links:

[Docs-compass](https://docs-mongodborg-staging.corp.mongodb.com/DOP-1979/compass/cgoecknerwald/DOP-2063/).

### Notes:

- Am I handling icons intelligently?
- Note the difference in card height upon resizing. Is this acceptable? If not, what is a suggested fix?

2021-04-20 17:15 UTC, sophstad requested changes

2021-04-20 17:18 UTC, mango-db commented on src/components/landing/Card.js
> +  box-shadow: 0px 0px ${theme.size.tiny} ${uiColors.gray.light2};
@allisonmui9 What is desired border / box styling here (1/2)?

2021-04-20 17:18 UTC, mango-db commented on src/components/landing/Card.js
> +const CompactCardText = styled('div')`
@allisonmui9 What is desired hovering behavior here (2/2)?

2021-04-20 17:24 UTC, allisonmui9 commented on src/components/landing/Card.js
> +const CompactCardText = styled('div')`
Agree with Sophie

2021-04-20 17:27 UTC, allisonmui9 commented on src/components/landing/Card.js
> +  box-shadow: 0px 0px ${theme.size.tiny} ${uiColors.gray.light2};
Sorry! I'm not sure what I should be paying attention to here. Regardless, we should stick with the LG card!

2021-04-20 21:41 UTC, sophstad commented on src/components/landing/Card.js
> +      <>
Cassidy recently made an update to this component in #373 to avoid nested anchor links. `Box` is also removed. Let's make sure those updates are properly merged in and functional here.

2021-04-21 21:21 UTC, mango-db commented on src/components/landing/CardGroup.js
> +      {isCompact ? (
Based on our conversation, in the future we will be adding a layout option to `CardGroup` to differentiate `CardGroup` layouts and `Card` styles.

2021-04-22 18:09 UTC, rayangler commented on src/components/landing/CardGroup.js
> +  page,
What is `page` being used for in this component?

2021-04-24 13:01 UTC, mango-db commented on src/components/landing/CardGroup.js
> +  page,
Great question! Pruning...

2021-05-05 16:29 UTC, sophstad commented on src/components/landing/CardGroup.js
> +  page,
Just flagging this, could be removed!

2021-05-05 16:31 UTC, sophstad approved these changes

2021-05-05 16:31 UTC, sophstad commented on src/components/landing/Card.js
> +        >
Is there any need to split this out separately from the conditional on line 89? Seems like we have one layout for `isCompact` and another for other cards and would be nice to have the logic in one place.

2021-05-06 17:26 UTC, allisonmui9 approved these changes

2021-05-06 17:37 UTC, mango-db commented on src/components/landing/Card.js
> +        >
Yes - the `compact` Icon has a green surrounding circle that the `extra-compact` Icon does not.

2021-05-06 17:39 UTC, merged