DOP-1840: Add Sidebar back link
mongodb/snooty pull request #393
Opened 2021-04-28 16:39 UTC by sophstad

### Stories/Links:

DOP-1840

### Staging Links:

- [BI Connector](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/sophstad/DOP-1840/)
- [Landing](https://docs-mongodbcom-staging.corp.mongodb.com/nav/landing/sophstad/DOP-1840/)

### Notes:

- Use `realm-web` rather than `mongodb-stitch-browser-core` because the latter package was exhibiting some bugs when used with `@loadable/component`. Switching over was easy enough!
- Lift Realm `fetchProjectParents` call into context so that results are accessible to breadcrumbs and sidenav
- Move all providers into one component for the sake of tidiness

2021-04-28 20:08 UTC, rayangler requested changes

2021-04-28 20:08 UTC, rayangler commented on src/components/SidebarBack.js
> +  const titleNodes = title.map((child, i) => <ComponentFactory key={i} nodeData={child} />);
Would we be able to use `formatText()` instead? Or do we leave it like this because the title is never expected to just be a string?

2021-04-28 20:22 UTC, sophstad commented on src/components/Sidenav.js
> +      <SideNavGroup>
Oh, I thought that the group was supposed to add the horizontal line to the bottom of the div, but I just looked through the code more closely and that only occurs with a collapsible group. I'll remove this!

2021-04-28 20:25 UTC, sophstad commented on src/components/SidebarBack.js
> +    return <Placeholder />;
These pages will just be integrated in the TOC, so no back button required! Designs are [here](https://mongodb.invisionapp.com/console/V4-Docs-Nav-cknazadbo8mf9010xel4kjnym/cknazr3jx5w49010i3ltgn8y2/play).

And I am using it to avoid any CLS related jostling in the sidebar! Once we are rendering the full TOC, I think those contents would be bumped downwards by the back button loading.

2021-04-28 20:30 UTC, rayangler commented on src/components/SidebarBack.js
> +    return <Placeholder />;
That design link takes me to the docs homepage. I'm referring to the category pages for `view-analyze`, `launch-manage`, etc. ([design](https://mongodb.invisionapp.com/console/V4-Docs-Nav-cknazadbo8mf9010xel4kjnym/cknazr3waa57d01xlulch1ht2/play))

2021-04-29 13:59 UTC, rayangler approved these changes
LGTM!

2021-04-29 14:15 UTC, merged