DOP-1436 Use LeafyGreen Modal in Lightbox component
mongodb/snooty pull request #432
Opened 2021-06-16 21:02 UTC by carooobregon

### Stories/Links:

DOP-1436

### Staging Links:
[Docs Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP-1436/indexes/)

### Notes:
Changed the current `Lightbox` modal to the `LeafyGreen` modal, still unsure about how to test it though since it was previously using `Lightbox` CSS classes to test but those are not needed anymore.

2021-06-17 16:00 UTC, rayangler requested changes
Changes look good so far! I left some comments that might be worth looking into before merging

2021-06-21 19:55 UTC, carooobregon commented on src/components/Lightbox.js
> -          className="lightbox__modal"
Deleted classes relating to lightbox that were only used in this component and applied styles using Emotion

2021-06-21 21:40 UTC, rayangler reviewed
Thanks for updating the css to use Emotion for the Lightbox component! Also, great work on getting the tests to pass.

I left a few nitpicky comments that may help to maintain the current style of our code. Also left a couple comments on the behavior of modals for different screen sizes

2021-06-21 21:40 UTC, rayangler commented on src/styles/mongodb-docs.css
> +.deluge-vote-button:hover{
[nit] We can add a space between the selector and the curly brace here to keep it the same form

2021-06-21 21:40 UTC, rayangler commented on tests/unit/Lightbox.test.js
> +    const lightboxwrapper = wrapper.find('LightboxCaption');
[nit] We can use camelCase for this variable

2021-06-21 21:40 UTC, rayangler commented on src/components/Lightbox.js
> +      width: 40%;
It seems like the media query works well for smaller images when the screen size is very large, but not as well on smaller screen sizes. [Example](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/carolinao/DOP-1436/tutorial/geospatial-tutorial/): an already large image gets significantly smaller.

<img width="848" alt="Screen Shot 2021-06-21 at 5 20 08 PM" src="https://user-images.githubusercontent.com/27821750/122830177-f8cc8a80-d2b5-11eb-8500-0039c19ac4c0.png">

Is there another possible approach we could take for more varying screen sizes?

2021-06-22 16:28 UTC, carooobregon commented on src/components/Lightbox.js
> +      width: 40%;
We could leave the modal size 80% for screen sizes large and up (the same way we had it in the last PR) and 100% for screen sizes smaller than that so they can take up the maximum amount of space (considering they don't have a lot of space to expand into), what do you think?

2021-06-22 17:38 UTC, rayangler commented on src/components/Lightbox.js
> +      <LightboxWrapper nodeData={nodeData}>
We could pass in a prop for the figure width as `nodeData?.options?.figwidth` instead of passing the entire `nodeData` object here

2021-06-22 17:38 UTC, rayangler commented on src/components/Lightbox.js
> +  width: '${(props) => props.nodeData?.options?.figwidth || 'auto'}'
It seems like the `width` isn't being applied here on staging. Adding the semicolon at the end may fix this

2021-06-22 17:38 UTC, rayangler commented on src/components/Lightbox.js
> +      width: 80%;
This is a reasonable approach and it seems to work well!

2021-06-24 15:25 UTC, rayangler reviewed
This looks good! Just a couple comments on the unit test

2021-06-24 15:25 UTC, rayangler commented on tests/unit/Lightbox.test.js
> +    <div className="lightbox_imagewrapper">
Is this container still necessary since we're relying on clicking on `LightboxCaption` for clicking outside of the modal?

2021-06-24 15:25 UTC, rayangler commented on tests/unit/Lightbox.test.js
>    it('clicking the photo', () => {
Can we update this test name to be more specific? Maybe something like 'clicking the photo opens the modal'

2021-06-24 15:48 UTC, carooobregon commented on tests/unit/Lightbox.test.js
> +    <div className="lightbox_imagewrapper">
Good catch! Not necessary at all, just deleted it :)

2021-06-24 15:48 UTC, carooobregon commented on tests/unit/Lightbox.test.js
>    it('clicking the photo', () => {
Updated it!

2021-06-24 15:51 UTC, merged