DOP-2198: Update PLP template to accommodate large hero image
mongodb/snooty pull request #438
Opened 2021-07-02 22:06 UTC by rayangler

### Stories/Links:

DOP-2198
[Realm PLP Design](https://www.figma.com/file/hPTwMb9uHOypYLckYDg072/Realm-PLP?node-id=2%3A965)
[New Realm PLP rst](https://github.com/rayangler/docs-realm/commit/31acd674a51bc12275b59b841a5c9c3676611838)

### Staging Links:

[Realm](https://docs-mongodbcom-staging.corp.mongodb.com/DOP-2198/realm/raymundrodriguez/DOP-2198/)
[Compass](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/raymundrodriguez/DOP-2198/)

### Notes:
* Had to get rid of the padding on the side and add additional grid columns to act as padding. This allows the large hero image to span the whole main column. The grid column for existing components were adjusted to compensate for the new columns. Positioning should be the same overall.
* Added a small fix for the `Contents` component appearing under every heading on mobile/tablet sizes.
* Since the new Realm PLP really uses a layout more similar to the new docs-nav's landing template ([design](https://www.figma.com/file/cGgCI13jIX4XwWwFETopNZ/Docs-Nav-Copy?node-id=116%3A225)), it might be worth either consolidating the `landing` and `product-landing` templates together in the future? Maybe a discussion worth having post-docs-nav / as we add more product landing pages to look for any major differences.

2021-07-06 13:35 UTC, allisonmui9 requested changes
Hey Raymund! For the most part looks great! The only thing is that at a larger screen size, 1440px+, white space increase on the left and right side of the hero image. Is there any way we can make the picture stretch? 
<img width="1673" alt="Screen Shot 2021-07-06 at 9 33 18 AM" src="https://user-images.githubusercontent.com/57725481/124609333-87581480-de3d-11eb-9d1c-71641037243b.png">

2021-07-07 17:19 UTC, allisonmui9 approved these changes
Beautiful! Thank you!

2021-07-07 17:26 UTC, schmalliso approved these changes

2021-07-07 18:17 UTC, mango-db approved these changes
> Added a small fix for the Contents component appearing under every heading on mobile/tablet sizes.

Bless up 🚀 

Staging on Realm and Compass LGTM

2021-07-07 18:23 UTC, merged