DOP-2322 & DOP-2323 -  Implement QuizChoice component layout
mongodb/snooty pull request #449
Opened 2021-07-20 15:52 UTC by carooobregon

apologies for the long PR 😭  but this is a fun one 👍 😄 

### Stories/Links:

DOP-2322 
DOP-2323

### Staging Links:

[Random article I added a quiz widget to
](https://docs-mongodbcom-staging.corp.mongodb.com/master/cloud-docs/carolinao/dop-2322/mongodb-logs/)
### Notes:

Implemented QuizChoice with their respective styling depending on different states: Hovered, Selected, Submitted wrong question, Submitted right question
Sent setState callback functions as props to pass state between components

2021-07-20 15:54 UTC, carooobregon commented
github exposing all my commits 😭

2021-07-20 17:39 UTC, casthewiz commented on src/components/QuizChoice.js
> +      }`}
I would look to unravel this nested ternary, or otherwise move some of the statements out of this block - it's a little hard to read and keep straight which styles are applied with which combo of boolean states

2021-07-20 17:39 UTC, casthewiz commented on src/components/QuizChoice.js
> +  const isCurrentChoiceCorrect = options?.['is-true'] ? true : false;
total nitpick

but we can shorthand cast to a boolean with
`!!options?.['is-true']`

2021-07-20 17:59 UTC, carooobregon commented on src/components/QuizWidget.js
> +  );
nice i didn't know i could do that thank you!

2021-07-20 18:52 UTC, rayangler commented on src/components/QuizChoice.js
> +  ${(props) => (props.hasSubmitted ? `pointer-events: none; ` : ``)}
(Nit) Instead of returning an empty string, we could do something like:
```
${(props) => props.hasSubmitted && 'pointer-events: none;'}
```

2021-07-20 19:20 UTC, carooobregon commented on src/components/QuizChoice.js
> +      }`}
separated them into different statements! lmk if those are good enough

2021-07-20 19:21 UTC, carooobregon commented on src/components/QuizChoice.js
> +  const isCurrentChoiceCorrect = options?.['is-true'] ? true : false;
looks so much better!

2021-07-20 19:57 UTC, carooobregon commented
fixed ternary ops and @allisonmui9 did some styling changes! [figma](https://www.figma.com/file/yYJuLvrlU1JGfiX1kvJrOW/Quiz-Widget?node-id=0%3A1)

2021-07-21 12:56 UTC, allisonmui9 requested changes
Hi Caro! This is looking great. Thanks for making those changes! Some minor comments: 
- When an answer is correct, can we please remove the incorrect answer label at the bottom of the screen? We won't need that! 
- When choosing an answer and hitting submit, there's a slight pause where the stroke flickers. Do you know why that might be? 
- Similarly, when user hits submit, there's a brief lag / flicker and the x position of the text changes by maybe 1 / 2 pixels.  
- When the explanations are shown, can you make only the correct answer at full opacity? Looks like it's getting the same opacity treatment as the incorrect answers. 

Otherwise, looks amazing. :)

2021-07-21 15:26 UTC, carooobregon commented
> Hi Caro! This is looking great. Thanks for making those changes! Some minor comments:
> 
> * When an answer is correct, can we please remove the incorrect answer label at the bottom of the screen? We won't need that!
> * When choosing an answer and hitting submit, there's a slight pause where the stroke flickers. Do you know why that might be?
> * Similarly, when user hits submit, there's a brief lag / flicker and the x position of the text changes by maybe 1 / 2 pixels.
> * When the explanations are shown, can you make only the correct answer at full opacity? Looks like it's getting the same opacity treatment as the incorrect answers.
> 
> Otherwise, looks amazing. :)

thanks for your comments ! removed the incorrect answer label, changed opacity and was able to fix the border flicker w @rayangler 's help ! lmk if there's any additional styling changes to be done

2021-07-21 17:24 UTC, rayangler reviewed
Just a couple of nitpicky comments and one question!

2021-07-21 17:27 UTC, carooobregon commented on src/components/QuizWidget.js
> +            idx={i + 1}
Ahh it's `i+1` bc when I was doing `const selectedThisChoice = selectedResponse === idx;` on `QuizChoice.js` it was returning false when idx was 0, open to suggestions tho!

2021-07-21 18:20 UTC, rayangler commented on src/components/QuizWidget.js
> +            idx={i + 1}
Definitely weird! I would expect 0 === 0 to equal true 😅 . If this way works, I think it's fine then

2021-07-21 18:20 UTC, rayangler commented on src/components/QuizChoice.js
> +};
Should we include the other props for `QuizChoice` here?

2021-07-21 18:43 UTC, carooobregon commented on src/components/QuizWidget.js
> +            idx={i + 1}
You're right ! I think the issue was more when I was sending just the 0 in 
```
      onClick={() =>
        !selectedThisChoice ? callback({ index: idx, isCurrentChoiceCorrect: isCurrentChoiceCorrect }) : callback()
      }
```
but since I'm now sending an object it doesn't negate when it's 0. thanks for the catch :)

2021-07-22 17:25 UTC, carooobregon commented on src/components/QuizChoice.js
> +      iscurrentchoicecorrect={iscurrentchoicecorrect ? 1 : 0}
I was receiving this warning when i just sent it as `iscurrentchoicecorrect={iscurrentchoicecorrect}` 
```
Warning: Received `false` for a non-boolean attribute `comingsoon`.

If you want to write it to the DOM, pass a string instead: 
comingsoon="false" or comingsoon={value.toString()}.
```
and i found this solution in [StackOverflow](https://stackoverflow.com/questions/49784294/warning-received-false-for-a-non-boolean-attribute-how-do-i-pass-a-boolean-f), does that sound right?

2021-07-22 18:45 UTC, rayangler commented on src/components/QuizChoice.js
> +      iscurrentchoicecorrect={iscurrentchoicecorrect ? 1 : 0}
Styling an existing React component and then passing props to conditionally style it can get kind of tricky because the props are still passed to the original component, and the prop can potentially make its way down to the html elements that make up the component (either intentionally or unintentionally).

To keep the camelCase for props and to prevent all of these errors and warnings of passing props and attributes to html elements, it might be worth just using emotion's `css` prop instead of `styled` for this case

2021-07-22 19:10 UTC, carooobregon commented on src/components/QuizChoice.js
> +      iscurrentchoicecorrect={iscurrentchoicecorrect ? 1 : 0}
great idea! using css instead of styled solved the problem :)

2021-07-23 19:03 UTC, carooobregon commented
Opened a new PR for this bc staging link was having some troubles. [Link to new PR](https://github.com/mongodb/snooty/pull/452)

2021-07-23 19:03 UTC, closed without merging