(DOP-2393) Fix permalinks to copy url and add tooltip when copied
mongodb/snooty pull request #516
Opened 2021-12-02 16:26 UTC by gjchong25

### Stories/Links:

[DOP-2393](https://jira.mongodb.org/browse/DOP-2393)

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

2021-12-02 20:03 UTC, rayangler reviewed
Looks good so far and it seems to work fine on the staging link! Just a nitpick and a couple of things to consider

2021-12-02 20:03 UTC, rayangler commented on src/components/Heading.js
> +  const url = isBrowser ? window.location.href.split('#')[0] : null;
Instead of making the alternative value `null`, should we turn this into an empty string? I'm afraid of `null` turning into the string `"null"` when it's concatenated with a string, as in:
```
null + "#" === "null#"
```

2021-12-02 21:14 UTC, allisonmui9 requested changes
hello! looking good so far! I think the visual and style looks great! Only comment is that when the permalink is clicked, it jumps quite far into that section. Could we still jump down to that section but keep the header still in view? 

Let me know if that needs clarifying! Thanks :)

2021-12-03 17:42 UTC, casthewiz approved these changes
I think this looks structurally fine, I just have two minor nitpickish comments 😄

2021-12-03 17:42 UTC, casthewiz commented on src/components/Heading.js
> +  useCopyClipboard(copied, setCopied, headingNode, url + '#' + id);
nitpick: since we don't use `url` in the file outside of these two lines, can we take the `url + '#' + id` statement and put it into the assignment on line 38? We could then pass just `url` as the last argument in `useCopyClipboard`.

2021-12-03 17:42 UTC, casthewiz commented on src/hooks/useCopyClipboard.js
> +};
It might be useful to indicate (either through variable name or comment) that `component` is expected to be a `ref` - at least, that's my understanding. If I'm off-base, feel free to ignore 😆

2021-12-03 17:56 UTC, rayangler approved these changes
LGTM!

2021-12-03 20:08 UTC, allisonmui9 approved these changes
LGTM thank you Grace!

2021-12-03 20:21 UTC, merged