DOP-2503: Expose ContentsList component for guides usage
mongodb/snooty pull request #529
Opened 2022-01-21 22:23 UTC by rayangler

### Stories/Links:

DOP-2503

### Staging Links:

[Guides Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/test-guides/guides/raymundrodriguez/DOP-2503/index.html)
[Compass Staging]() (to see the "On This Page"/Contents component in the docs)

### Notes:
* This PR exposes the internal components that `Contents` was using for the "On This Page" component. The styling and behavior should remain unchanged, especially for the docs pages that currently uses this component.

2022-01-21 22:37 UTC, rayangler commented on src/hooks/useActiveHeading.js
> -      }
Deleted this because:

(1) Keeping this in was causing the active id to never change when the hook was used in a single component instead of within a context.

(2) I haven't been able to reproduce the behavior described by the comment. The behavior may be obsolete now but happy to add this back in if needed.

2022-01-24 17:02 UTC, allisonmui9 approved these changes
lgtm. Thanks Raymund!!! 🔥

2022-01-25 14:45 UTC, gjchong25 requested changes
Great job, just a few questions and suggestions that you can feel free to use! It looks really nice UI-wise!

2022-01-25 14:45 UTC, gjchong25 commented on src/components/Chapters/Chapter.js
> +  const chapterNumber = currentChapter.chapter_number;
Do we not want to define chapterNumber with `currentChapter?.chapter_number`? Since isn't it still possible that `currentChapter` is undefined?

2022-01-25 14:45 UTC, gjchong25 commented on tests/unit/Chapters.test.js
> +    jest.spyOn(useActiveHeading, 'default').mockImplementation(() => 'atlas');
Just curious, what is the reasoning behind this line and how is it being used for testing? And what is the function `() => 'atlas'` accomplishing?

2022-01-25 14:45 UTC, gjchong25 commented on src/hooks/useActiveHeading.js
>        for (let entry of entries) {
Since we're not changing the entry, could it be `const entry` instead of `let`?

2022-01-25 22:27 UTC, rayangler commented on tests/unit/Chapters.test.js
> +import * as useActiveHeading from '../../src/hooks/useActiveHeading';
While attempting to mock the hook, the tests were still trying to use the function's original implementation. This way of importing the hook allows us to import it as an object, and then we spy on the object's default function to mock the hook. We perform similar patterns in some of our other tests to mock things

2022-01-25 22:27 UTC, rayangler commented on tests/unit/Chapters.test.js
> +    jest.spyOn(useActiveHeading, 'default').mockImplementation(() => 'atlas');
The `useActiveHeading` hook uses the `IntersectionObserver` API, which is implemented for a browser. Since we don't have access to a browser that implements this API while testing, we mock the hook here to bypass making calls to the non-existent `IntersectionObserver`. This will prevent errors from the hook being called by the component we're testing.

In this case, the mock function will just return the string "atlas" immediately because the original hook is supposed to return the id of the active heading/node being observed by the `IntersectionObserver`. Realistically, the mock function here could return anything since we're only using it here to prevent errors from occurring.

2022-01-26 14:23 UTC, gjchong25 commented on tests/unit/Chapters.test.js
> +import * as useActiveHeading from '../../src/hooks/useActiveHeading';
Oh gotcha, thanks for clarifying!

2022-01-26 14:26 UTC, gjchong25 commented on tests/unit/Chapters.test.js
> +    jest.spyOn(useActiveHeading, 'default').mockImplementation(() => 'atlas');
Makes sense!

2022-01-26 14:48 UTC, gjchong25 approved these changes
LGTM once Cassidy takes a second look!

2022-01-26 18:59 UTC, casthewiz commented on src/components/Chapters/RightColumn.js
> +  const chapterValues = Object.values(chapters);
I would default `chapters` to `{ }` here - if `chapters` is nullish, then this will throw `Uncaught TypeError: Cannot convert undefined or null to object`

2022-01-26 19:24 UTC, casthewiz approved these changes
lgtm! 🚀

2022-01-26 22:34 UTC, merged