DOP2400
mongodb/snooty pull request #659
Opened 2022-07-22 17:53 UTC by anabellabuckvar

### Stories/Links:

[DOP-2400
](https://jira.mongodb.org/browse/DOP-2400)
### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

2022-07-25 14:08 UTC, gjchong25 reviewed
Just a few notes, suggestions and nits for now! Overall the first view looks good. It might be helpful to add comments for yourself and for other reviewers about certain code that will need to be refactored / removed later on as you work through each of the views. 

Also, currently you have your `base` branch set to `master`, it should be set to the `feedback-widget-v3` feature branch you created, since we don't want to merge anything into master until all the views are complete.

2022-07-25 14:29 UTC, allisonmui9 commented on src/components/Widgets/FeedbackWidget/FeedbackTab.js
> +  right: 15px;
Hm - in the designs, it says 16px. But I agree with Grace in that it would look less squished with more spacing. Can we keep the right hand spacing the same as that of the Share feedback button?

2022-07-25 14:50 UTC, allisonmui9 approved these changes
First screen looks great - left one minor nit with Grace's comment on the right hand side spacing.

2022-07-25 16:06 UTC, rayangler reviewed
Great work so far! Mostly just clarifying questions from me for now

2022-07-25 17:29 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/context.js
>    async function setRating(ratingValue) {
You can feel free to add those comments directly in the code, since they'll be addressed and deleted later once you get to them! It's just a good reminder for your future self :)

2022-07-25 18:11 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +};
Yes, that makes sense to me! Should it still have a default sentiment?

2022-07-25 18:55 UTC, rayangler commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +};
I don't think it would need a default sentiment since it's expected that every sentiment in `sentimentChoices` will be rendered into a choice component. There will always be a 1:1 mapping of sentiment and copy

2022-07-26 17:26 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    setProgress([false, true, false]);
Changed it to that, thanks for catching this!

2022-07-26 17:27 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +    <StyledSentiment onClick={() => setSentiment()}>
I was originally going to do that in a separate PR so I intentionally hadn't worked on that yet, but now I am.

2022-07-26 17:28 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackCard.js
>        <Floating>
Rename FeedbackCard to FloatingContainer?

2022-08-03 13:41 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +};
I made this change, let me know if it's what you had in mind!

2022-08-03 19:32 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    setView('comment');
Completed this as part of the rest of the ticket!

2022-08-04 16:03 UTC, rayangler reviewed
FW screens looking great! Just wanted to flag some additional things I noticed:

1) The content on the 3rd screen looks like it's squished on the upper half of the card. (It looks like the bottom of the card feels empty.) The design seems to show the content more centered. Not sure if this is intentional or should be addressed?

~~2) Are the screens also implemented for mobile screen sizes? I couldn't figure out how to leave feedback, so I wasn't sure if I was just missing something 😅 ~~ Mobile intentionally not present atm

2022-08-04 17:04 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    // Route the user to their "next steps"
It refers to the line of code above, setting the feedback

2022-08-04 17:04 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    /**{
They are intended to be kept for now as a reference when constructing the feedback document on the front end

2022-08-04 17:05 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  //const label = screenshot ? 'Screenshot Saved' : loading ? 'Taking Screenshot' : 'Take a Screenshot';
I kept it in because the screenshot functionality, part of a separate ticket, is not yet integrated/finalized.

2022-08-04 17:10 UTC, allisonmui9 requested changes
It's looking great! 

Couple comments:
- The 'did this page helpful' header doesn't seem centered. The text itself I mean seems a little off to the left. Can we center this? Or am I going crazy? 
- The green dots at the top. This looks too bright (probs a change in the brand or not pulling from LG). Can we use green dark 1? 
- When I change the emojis at the top of the second screen, there is a small flicker. 
- The input field is not the most updated version. Can you use the latest version of the component? 
- The send button is not using the latest version. Can you use the latest version of the component? 
- The gray X at the top right corner, can we change this to a lighter color? gray light 1 
- I really like how the second and third screen are a consistent height. Can we adjust the first screen to match the same height? This will reduce the jumpyness of that first state. 

Attached photos. 
<img width="122" alt="send button update" src="https://user-images.githubusercontent.com/57725481/182910279-36a9608d-f4f5-4561-90d5-94e39dc32882.png">
<img width="263" alt="input field update" src="https://user-images.githubusercontent.com/57725481/182910282-9be7ee09-9388-4a12-a320-61e0cb990f12.png">
<img width="278" alt="change to consistent size" src="https://user-images.githubusercontent.com/57725481/182910283-e4b310b1-480f-4918-8d40-f7542c7ac6c6.png">
<img width="61" alt="change to gray light1" src="https://user-images.githubusercontent.com/57725481/182910285-cc0deec0-7722-454e-bebc-29d7a610ca4a.png">
<img width="261" alt="flicker of emojis" src="https://user-images.githubusercontent.com/57725481/182910286-d04e64e1-f8de-46d0-9dbd-57fb55ba8789.png">
<img width="184" alt="change to green dark1" src="https://user-images.githubusercontent.com/57725481/182910287-051fc5da-0187-4493-8cc3-6d4b8c12e845.png">
<img width="400" alt="center header" src="https://user-images.githubusercontent.com/57725481/182910288-aeb8189b-c8da-4f2b-9be6-ec95ac4107a3.png">


Here's a relevant slack thread for bumping the component versions: https://mongodb.slack.com/archives/C03SCJ87TNV/p1659628715218119

2022-08-04 17:10 UTC, anabellabuckvar commented on package.json
> +    "@leafygreen-ui/segmented-control": "^3.0.0",
It isn't being used. I installed it when I first began working on view 2 and wasn't sure how to remove it

2022-08-04 17:26 UTC, rayangler commented on package.json
> +    "@leafygreen-ui/segmented-control": "^3.0.0",
Ah, okay. I think you can just try doing

```
npm uninstall @leafygreen-ui/segmented-control
```

Lemme know if that works or not!

2022-08-04 17:27 UTC, rayangler commented on src/components/Widgets/FeedbackWidget/context.js
> +    /**{
Makes sense! Thanks!

2022-08-04 17:28 UTC, rayangler commented on src/components/Widgets/FeedbackWidget/context.js
> +    // Route the user to their "next steps"
Ah, gotcha. Is it possible to move that comment above the line of code then? Our general pattern is to leave a comment explaining the code below it. That way, a developer reading the code can read the comment before it and have an idea of what the code will be doing

2022-08-04 18:45 UTC, anabellabuckvar commented on package.json
> +    "@leafygreen-ui/segmented-control": "^3.0.0",
It worked! I pushed those changes, thank you

2022-08-04 18:47 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    // Route the user to their "next steps"
Ok will change

2022-08-04 18:59 UTC, gjchong25 reviewed
Looks great so far!! Just have a few small comments about organization and modularity.

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +import TextInput from '@leafygreen-ui/text-input';
Nit: reorder external imports at the top when applicable

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +   border-color: ${hasEmailError ? palette.red.base : palette.gray.base} !important
Nit: Missing a semicolon and indenting here

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +      ></StyledCommentInput>
If there's no content nested inside `StyledCommentInput` you can just use a closing tag like `/>` here instead of `</StyledCommentInput>`. Same with `StyledEmailInput`

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +  //position: fixed;
Should this be removed?

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +  positiion: absolute;
Typo here, should be `position`

2022-08-04 18:59 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/stitch.js
> +/**
Nit: not sure if you just forgot to un-comment this out, but since you'll be handling the backend in a different PR I think it's fine to keep it as is for now

2022-08-04 19:19 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  const [setIsHovered] = React.useState(false);
This should be `const [isHovered, setIsHovered]`; however, this was really only necessary for the Tooltip. If we no longer want a Tooltip to appear when the Screenshot button is hovered then we can remove this since it's not being used anywhere.

2022-08-05 14:22 UTC, seungpark commented
getting an error when running this locally: 
```
There was an error in your GraphQL query:

Cannot query field "parserUser" on type "SiteSiteMetadata".
```

should be resolved by merging master

2022-08-05 17:56 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FloatingContainer.js
> +  background: #ffffff;
Removed it.

2022-08-05 18:02 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +  //position: fixed;
Yes, removed it

2022-08-05 18:03 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +   border-color: ${hasEmailError ? palette.red.base : palette.gray.base} !important
fixed!

2022-08-05 19:35 UTC, seungpark requested changes

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +    setView('submitted');
should this be called after async function has resolved. there needs to be some error catching involved in the stitch module, however. there seems to be no error catching in the await functions..

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackTab.js
> +  font-weight: 500;
seeing font-weight 400, color #09804C in figma, also font-size 14px in figma vs 16px in page

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FloatingContainer.js
> +  border-radius: 7px;
nit, repeated border-radius from LG card. but may be necessary with card component update, would add a comment here

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import StarRating, { RATING_TOOLTIPS, StarRatingLabel } from './components/StarRating';
missing ProgressBar here and CloseButton is off center

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
> +  background: ${palette.gray.light3};
seeing header styled as background #FFFFFF in figma

2022-08-05 19:35 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import StarRating, { RATING_TOOLTIPS, StarRatingLabel } from './components/StarRating';
also, how do we get to this feedback widget on mobile? seems like there is a different feedback (on page, 1-5 star points)
![image](https://user-images.githubusercontent.com/13054820/183147415-0f8dc81b-2954-45dc-9ac1-c54ec2b5a83a.png)

2022-08-05 20:17 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +      ></StyledCommentInput>
getting this error in console:

```
label or aria-labelledby must be provided to TextInput. 
```

2022-08-05 20:26 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/views/SubmittedView.js
>        <Subheading>
minor warning `Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

Subheading converts to <p> and are nesting <div> inside. 

would adopt the styling to the outer container of the SubmittedView, so it trickles down to elements inside. ie:

```
    <Layout> // SET STYLING HERE
      <Heading>{finalHeading}</Heading>
      <Subheading>Your input improves MongoDB's Documentation.</Subheading>
      <Subheading>
        <span>Looking for more resources? </span>
        <a href="https://developer.mongodb.com/community/forums/">MongoDB Community </a>
        <a href="https://www.mongodb.com/developer/">MongoDB Developer Center</a>
      </Subheading>
      <SupportCase selectedSentiment={selectedSentiment}>
        {'Have a support contract?'}
        <a href="https://support.mongodb.com/">Create a Support Case</a>
      </SupportCase>
      {isMobile && <Button onClick={() => abandon()}>Return to the Documentation</Button>}
    </Layout>
```

2022-08-05 20:57 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import StarRating, { RATING_TOOLTIPS, StarRatingLabel } from './components/StarRating';
The different screensizes, tablet, and mobile are not included in this PR

2022-08-08 13:54 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import StarRating, { RATING_TOOLTIPS, StarRatingLabel } from './components/StarRating';
Supporting all screen sizes isn't included in the scope of this ticket

2022-08-08 14:08 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    // Route the user to their "next steps"
Got it, thanks. That comment actually referred to some deleted code and is no longer relevant so I just deleted it.

2022-08-08 14:08 UTC, anabellabuckvar commented on package.json
> +    "@leafygreen-ui/segmented-control": "^3.0.0",
This worked, thank you

2022-08-08 14:09 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FloatingContainer.js
> +  background: #ffffff;
Nope it was unnecessary! Deleted

2022-08-08 14:10 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
> +  background: ${palette.gray.light3};
Supporting all screen sizes isn't included in the scope of this ticket, so I haven't made changes to this file yet.

2022-08-08 14:26 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FloatingContainer.js
> +  border-radius: 7px;
Seems unnecessary to me, I deleted it.

2022-08-08 14:41 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackTab.js
> +  font-weight: 500;
Updated this except for font-weight; for some reason a font-weight of 400 instead of 500 makes the text much too thin

2022-08-08 15:46 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/FeedbackCard.js
>        <Floating>
Sorry should've clarified, I meant change the `Floating` div tag to `FloatingContainer` - you can keep it as FeedbackCard!

2022-08-08 20:47 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +    setView('submitted');
discussed offline. will not be relaying error messages in UI

2022-08-08 22:18 UTC, seungpark requested changes
new text input package requires an update to lg/provider package as well

2022-08-08 22:18 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
>        <StyledEmailInput
this new text input is throwing an error:

```
index.js:81 Uncaught TypeError: Object(...) is not a function
    at eval (index.js:formatted:279:100)
```

seems like this has a dependency for leafy green provider v2.3 https://github.com/mongodb/leafygreen-ui/blob/main/packages/text-input/package.json#L31 while we are on 2.2 and this dependent function is from 2.3:

https://github.com/mongodb/leafygreen-ui/blob/main/packages/leafygreen-provider/CHANGELOG.md#minor-changes

2022-08-10 16:24 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/PageIndicators.js
> +  background-color: ${(props) => (props.isActive ? `${palette.green.dark1}` : `${palette.gray.light2}`)};
@allisonmui9 requested that I use green dark 1 in an earlier comment on this PR

2022-08-12 13:11 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +const ErrorIcon = () => (
Made these changes

2022-08-12 18:25 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/App.js
>  import React from 'react';
Yup, I removed it

2022-08-15 13:20 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SubmittedView.js
>        <Subheading>
Changed this, thanks

2022-08-15 13:20 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +      ></StyledCommentInput>
Those errors should be fixed now!

2022-08-15 13:21 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
>        <StyledEmailInput
I updated the component and the LG provider so it should be fixed now

2022-08-16 17:23 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackHeading.js
>          <StarRating size="lg" />
Discussed this offline, but leaving it in for now because other screen sizes use StarRating so it is not part of the scope of this ticket

2022-08-16 17:23 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/FeedbackTab.js
> +  right: 15px;
Resolved offline

2022-08-16 21:03 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +import Tooltip from '@leafygreen-ui/tooltip';
Done

2022-08-16 21:03 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/stitch.js
> +  //const { snootyEnv } = useSiteMetadata();
Removed it

2022-08-16 21:04 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    //const segment = getSegmentUserId();
Removed it

2022-08-16 21:09 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SubmittedView.js
> +        <Subheading></Subheading>
I was using it for spacing purposes but fixed it so now there's a top margin instead

2022-08-16 21:10 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SubmittedView.js
> +        <SupportCase selectedSentiment={selectedSentiment}>
It's necessary now because I added a top margin and removed the unnecessary <subheading/> line mentioned in your previous comment

2022-08-16 21:10 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SubmittedView.js
> +  margin-bottom 16px !important;
fixed

2022-08-17 14:33 UTC, seungpark requested changes
minor comments below, but looks great! skimmed over design changes as inconsistencies with figma have already been approved. and thanks for giving me a chance to learn about realm app services :)

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +  async function initializeFeedback(nextView = 'sentiment') {
why are these async functions without any awaits within block, or the callers?

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +  async function setRating(ratingValue) {
remove if not called

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
>  export function useFeedbackState() {
minor. would rename to useFeedbackContext. this is returning current context value(s), not a pair of state/setState

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +  async function initializeFeedback(nextView = 'sentiment') {
similar for setSentiment and abandon functions

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +      open="true"
this should be a boolean, being read as a string

2022-08-17 14:33 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +import button from '@leafygreen-ui/button';
minor nitpick. why did we use lower case here? should be Title for component

2022-08-17 14:44 UTC, rayangler approved these changes
LGTM! No more comments from my end (seems like the other reviewers got things covered 😎). Great work!

2022-08-17 18:17 UTC, gjchong25 reviewed
Generally looks good! Just a few cleanup things here and there, but great work on this overall!! Just want to take a look at the Staging link once that's working again before approving (also would like to take a last look once you resolve various commented-out code). Additionally the Atlas App function doesn't seem to be updated with the latest changes involving `snootyEnv` on my end, but not sure if this is a me issue or if the latest changes still need to be deployed.

2022-08-17 18:17 UTC, gjchong25 commented on tests/unit/FeedbackWidget.test.js
> +  //stitchFunctionMocks,
Remove comment

2022-08-17 18:17 UTC, gjchong25 commented on tests/unit/FeedbackWidget.test.js
> +          //sentiment: Positive
There's a bunch of sentiment-related comments in this file that can be uncommented if you want to include them as part of the current feedback state

2022-08-17 18:17 UTC, gjchong25 commented on tests/unit/FeedbackWidget.test.js
> +          //expect(stitchFunctionMocks['submitAllFeedback']).toHaveBeenCalledTimes(1);
Uncomment this line?

2022-08-17 18:17 UTC, gjchong25 commented on tests/unit/FeedbackWidget.test.js
> +    /*
This commented out section should be resolved, you can remove unnecessary tests and uncomment out the "Submitted" view tests

2022-08-17 22:34 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +      open="true"
what should be? I'm not sure exactly what you're referring to

2022-08-17 22:59 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +      {' '}
Deleted

2022-08-17 23:00 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +    //const dbName = snootyEnv === 'production' ? 'quiz_prod' : 'quiz_dev';
Removed

2022-08-17 23:03 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/StarRating.js
>  import styled from '@emotion/styled';
reordered

2022-08-19 13:46 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/SentimentView.js
> +      {sentimentChoices.map((path) => (
This should be updated now

2022-08-19 13:46 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/PageIndicators.js
> +        {progress.map((value) => (
Same as earlier reply, this should be updated now

2022-08-19 13:47 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +      open="true"
Nevermind, fixed this

2022-08-19 13:48 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/context.js
> +  async function setRating(ratingValue) {
removed

2022-08-19 13:48 UTC, anabellabuckvar commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +import button from '@leafygreen-ui/button';
Updated to uppercase

2022-08-19 15:56 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +      open="true"
ah sorry for the late reply, fixed with `{true}` change

2022-09-09 16:10 UTC, seungpark approved these changes
minor styling comment on validation error. otherwise LGTM. tested locally on different pages with varying comments + sentiments

2022-09-22 14:31 UTC, merged