DOP-2583: type now uses the typography component
mongodb/snooty pull request #662
Opened 2022-08-02 20:32 UTC by schmalliso

### Stories/Links:

Rebased off #660 so includes the card updates.

### Current Behavior:

[Landing](http://www.mongodb.com/docs/) 
[Compass](http://www.mongodb.com/docs/compass)
[Ecosystem / drivers](http://www.mongodb.com/docs/drivers/))
[Atlas](http://www.mongodb.com/docs/atlas/)

### Staging Links:

[Landing](https://docs-mongodbcom-integration.corp.mongodb.com/foo/landing/allison/branding/)
[Compass](https://docs-mongodbcom-integration.corp.mongodb.com/foo/compass/allison/branding/)
[Ecosystem / drivers](https://docs-mongodbcom-integration.corp.mongodb.com/foo/drivers/allison/branding/)
[Atlas](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/allison/branding/)

### Notes:

(Drivers) Cards on its landing look bizarre. Specifically, the Go, Node.js and Ruby cards are using different styling/classes than the rest. THE DIFFERENCE IS: relative links vs. links to other properties -- not sure if this is a typography thing or a cards thing.

(Landing) The base typography style in LeafyGreen [unsets margins](https://github.com/mongodb/leafygreen-ui/blob/main/packages/typography/src/styles.tsx#L7). I'm not super clear on what margins we want around headings / paragraphs / callouts, given the permutations and combinations that are out there, so we may need to dig into that a bit more. (e.g. page that illustrates some of the issues is [here](https://docs-mongodbcom-integration.corp.mongodb.com/foo/compass/allison/branding/upgrade).

2022-08-03 13:04 UTC, schmalliso commented
@allisonmui9 There's some weird spacing caused by LG unsetting margins in various contexts on various components. That said, I'm not sure we want to preserve 100% of our existing margin behavior? I'm thinking specifically about our squishy ordered/unordered lists and table elements. It might be practical to take a moment at this point to standardize, is what I'm saying. Thoughts?

2022-08-03 13:13 UTC, schmalliso commented on package.json
>      "@leafygreen-ui/checkbox": "^6.0.3",
dangit this dealphabetized. will fix on next patch.

2022-08-03 15:07 UTC, seungpark requested changes
component specific comments left below. still need to flesh out typography margins. haven't verified for components outside of these touched files

2022-08-03 15:07 UTC, seungpark commented on src/components/Link.js
> +  &:focus & {
also not sure what this underline is coming from. text decoration is from LG to underline but seems like line 31 is preventing that and adding a border bottom?

2022-08-03 15:20 UTC, schmalliso commented on src/components/Link.js
> +  &:focus & {
We use the GatsbyLink component for links within a Gatsby project and the LG Link component for (almost) all our other links. Because of that, we have to steal the styling from LG so that GatsbyLink components looks like LG despite being a different component. @casthewiz indicated this was probably the best solution for this use case.

2022-08-03 15:21 UTC, schmalliso commented on src/components/Heading.js
> +  if (sectionDepth === 1) {
LG's H1 is comically large. Allison's designs therefore use the LG H2 component as our H1 and so on, so we're mapping the "correct" component to the section depth here, and then using `as` to make sure that our h1 remains an h1 tag despite using the H2 component.

2022-08-03 15:59 UTC, allisonmui9 requested changes
Looking nice but also crazy haha :) 
Good call on the margin standardizing. 

For margins: 
- Here are some [guidelines](https://www.figma.com/file/PctpWXNmlv0khZahanOsU7/FY22-New-Brand?node-id=911%3A17120). Lmk what you think! 

some notes: 
For PLPs
- Can we change the top header to H3? 
- I need to change the icons at the bottom of the page. It also involves removing the colored circle in the card. How should I go about this? Making tickets for the content team? 

For Drivers: 
- oh yes, it's looking bizarre. I think the link in the card is causing some of the problems. What do you think the change could be? Would taking the link style out of the card do anything? 

For the landing page: 
- The card is auto pulling some font styles. The header in the card should be just body bold. 

Overall: 
- Is the breadcrumb 13px? It looks bigger than that but my eyes could be going crazy. 

Thank you! I'm sure I might have missed things :( Lmk if anything stands out to you.

2022-08-05 14:10 UTC, gjchong25 reviewed
Just a few comments for now! Forgive me if these were already pointed out somewhere already, but in summary it seems like the `line-height` for certain sections like sidenav items, TOC, and links in Cards makes the content look a bit crowded, unless this is fine by Allison Mui. The arrow displayed with on some links also wrap strangely as shown on the "Learn more about Atlas Search" link [here](https://docs-mongodbcom-integration.corp.mongodb.com/master/cloud-docs/allison/branding/atlas-search/#what-is-mongodb-fts-).

2022-08-10 14:30 UTC, schmalliso commented on src/components/Link.js
> +  line-height: 13px;
I don't have strong opinions here, but I am trying to duplicate what LG is doing for consistency with the LG-styled links, so I have a preference to just use whatever they have in their code.

2022-08-10 14:32 UTC, schmalliso commented on src/components/Link.js
> +  text-decoration: none;
ooh really good point - I stole this directly from the LG source and totally didn't notice 😁

2022-08-16 15:27 UTC, schmalliso commented on src/components/Sidenav/Sidenav.js
> +    line-height: 16px;
resolved by bumping sidenav component

2022-08-16 19:55 UTC, seungpark reviewed
minor comments below. Buttons are not working as intended, and a few places we could use theme vars instead of px values. as discussed, will branch off to finish cards and tabs

2022-08-16 19:55 UTC, seungpark commented on src/components/Figure/Lightbox.js
> +  margin-top: 24px;
docsTheme.size.medium

2022-08-16 19:55 UTC, seungpark commented on src/components/Figure/index.js
> +          margin-top: 24px;
similar for here, `margin: ${docsThemes.size.medium} 0`

2022-08-16 19:55 UTC, seungpark commented on src/templates/product-landing.js
> +  h1 {
seems like we would want PLP headings to be theme.black

2022-08-16 19:55 UTC, seungpark commented on src/components/Introduction.js
> +    margin: ${theme.size.small} ${theme.size.default} ${theme.size.default} 0;
top margin should be 0, barring this follows an intro paragraph with 16px margin bottom

2022-08-16 19:55 UTC, seungpark commented on src/components/Button.js
> +    <LeafyButton className="button" as="a" hideExternalIcon={true} variant="primary" to={uri}>
also getting this warning since we are not using Links:

`React does not recognize the `hideExternalIcon` prop on a DOM element.`

2022-08-16 20:16 UTC, schmalliso commented on src/templates/product-landing.js
> +  h1 {
oh dang! missed that -- good catch

2022-08-17 17:00 UTC, schmalliso commented on src/components/Contents/ContentsListItem.js
>  const ContentsListItem = ({ children, depth = 0, id, isActive = false }) => {
suggest we handle with the contents update

2022-08-17 18:31 UTC, seungpark approved these changes

2022-08-17 18:33 UTC, seungpark commented
can we change the target to rebranding-master?

2022-08-17 18:55 UTC, seungpark approved these changes
minor comment on PLP headings, but otherwise LGTM.

also would have to follow up with sidenav component update, and possibly include version control with that ticket

2022-08-17 18:55 UTC, seungpark commented on src/templates/product-landing.js
> +  h1 {
h1 on landing is not styled properly.

these margins should be removed, margins from heading.

also would have to overwrite the h1 color from LG

2022-08-18 12:52 UTC, gjchong25 approved these changes
LGTM, thank you for making all of these changes - it looks great! Just a few tiny things but otherwise things are looking good :)

2022-08-18 13:34 UTC, gjchong25 reviewed
<img width="490" alt="Screen Shot 2022-08-18 at 9 29 58 AM" src="https://user-images.githubusercontent.com/21082640/185407187-b3665ff2-3462-406a-a6f7-464182a1fa56.png">
<img width="436" alt="Screen Shot 2022-08-18 at 9 33 26 AM" src="https://user-images.githubusercontent.com/21082640/185408027-d47e257d-b671-4938-a35b-573d2cad293f.png">

Just wanted to raise a small issue I didn't catch earlier - It seems like the internal page links at the bottom display a long underline on hover, and that the size of the `<a>` doesn't match the length of the text as shown in the second image.

2022-08-18 17:17 UTC, seungpark commented
> 

seems like LG team is aware of this issue and should be addressed by time. in the mean time, can we implement the changes as outlined in the ticket for LInks?

2022-08-18 17:55 UTC, seungpark commented on src/styles/mongodb-docs.css
> -a:hover {
there is an text-decoration: underline on a:hover that seems to be missed on line 935

2022-08-19 15:57 UTC, casthewiz reviewed
There's a weird offset on the feedback widget button I observed on Chrome - it goes away when applying a `bottom: -24px` offset to it's styles. 

This was the only spot I saw a weird offset - it's probably just a minor conflict w/ leafygreen styles, but we should probably address in this PR 😅 

<img width="132" alt="Capture" src="https://user-images.githubusercontent.com/3813528/185659056-55de1f50-2430-405a-bec1-471d07ed30f3.PNG">

vs

<img width="640" alt="-24" src="https://user-images.githubusercontent.com/3813528/185659081-b309ac2f-66a9-4351-8444-9454120360ee.PNG">

2022-08-19 17:35 UTC, seungpark commented
> 

this should be addressed in the Card component PR here https://github.com/mongodb/snooty/pull/673

2022-08-19 19:35 UTC, allisonmui9 requested changes
two last comments: 
- around the side nav font size on landing pages 
- line height on footer links 

thanks!
https://docs.google.com/document/d/1wxg9lqbiuFzM7Huo5ccEb05PhX_9uYT0KcOv1dZttbc/edit?usp=sharing

2022-08-22 15:17 UTC, merged