DOP-2410: Updated screenshot functionality
mongodb/snooty pull request #669
Opened 2022-08-11 13:57 UTC by gjchong25

### Stories/Links:

[DOP-2410](https://jira.mongodb.org/browse/DOP-2410)

### Current Behavior:

[Compass Prod](https://www.mongodb.com/docs/compass/current/)

### Staging Links:

[Compass Staging](https://docs-mongodbcom-integration.corp.mongodb.com/testing/compass/grace.chong/DOP-2410/)

### Notes:

This does not include Anabella's UI updates from DOP-2400, so some of the code is outdated but this should be resolved upon rebasing once 2400 is merged. Also for testing purposes, once the "Send" button is clicked, the screenshot taken automatically gets downloaded for viewing. In addition, some of the submit logic has been commented out to avoid sending feedback to docs feedback Slack channels. 

Some additional notes:

- The original screenshot user flow was that upon clicking the screenshot button, the screenshot of the entire page would be captured automatically. Now, clicking on the screenshot button prompts a user to select a component of the page, and re-select if they mistakenly choose a component or if they want to change their selection.
- `CommentView` was made into a loadable component to resolve Webpack issues caused by the `rasterizehtml` library.
- Both states and refs are used in conjunction to ensure that within the eventListener, changes to the hovered/selected element are picked up and trigger re-renders of the page. 
- Currently, the FW "Give Feedback" tab displays on the last view, though it shouldn't be shown until the FW Modal is closed. This is because a null id is temporarily replacing the actual feedback document id for the submitFeedback function (so that slack channels don't get flooded during testing & FW tests still pass). Once the null id is replaced the tab should only appear once the modal is closed.

2022-08-24 18:26 UTC, seungpark requested changes
there seems to be a mix use of states and refs within ScreenshotButton component as well as feedbackwidget context. bit of redundancy we can clean up here. the calculations on overlays and positions are on point! TIL getElementsFromPoint exists

2022-08-24 18:26 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +    if (!!pos) {
when would this be false? the interpolated string will always have value

2022-08-24 18:26 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  const isFWSelected = useCallback((listOfElements) => {
is this required? seems like feedbackCard is hidden with `display: none` style when taking screenshot

2022-08-24 18:26 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  ${baseStyle(position, top, left, width, height)};
minor. if already highlighted, should remove cursor:pointer

2022-08-24 18:30 UTC, allisonmui9 requested changes
Looking very cool! Couple comments: 
- The 'please select an element' text is very large. This can just be our standard body 16px. I don't think it is right? I wasn't able to inspect. 
- Occasionally, the X button to redo your screenshot is underneath the widget (today's version). I'm not sure how much of an issue this is for the new version but just wanted to call it out. Thinking off my head, we could change the X button to the top left instead and it should reduce the possibilities that this would happen. Lmk what you think.

2022-08-24 18:51 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
>    const { rating } = feedback || { rating: 3 };
Hm this should no longer be relevant since ratings will be removed and replaced with sentiments. Will be deleted anyway once this work is incorporated with 2400

2022-08-25 14:20 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +    document.body.style.overflow = 'hidden';
was looking through what we had installed in our package list and seems like we also use [no scroll](https://github.com/davidtheclark/no-scroll#usage)

2022-08-25 15:22 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  const isFWSelected = useCallback((listOfElements) => {
It is hidden, but if an element right underneath it is clicked, the feedbackCard sometimes gets selected as an aftereffect.

<img width="188" alt="Screen Shot 2022-08-25 at 10 44 09 AM" src="https://user-images.githubusercontent.com/21082640/186696130-a1eb8097-30bf-4bcb-8bca-ef4ffdb30fdb.png">

2022-08-25 16:23 UTC, casthewiz commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +    if (isValidEmail && isBrowser) {
I'm assuming this is a check for ssr, and a codepath within this block isn't ssr safe, but will defer to @gjchong25 👍

2022-09-06 15:49 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +  const screenshotButtonClicked = useRef(false);
Removed

2022-09-06 19:04 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +    setCurrDOMState(currDOM.current);
Removed the unnecessary line. I don't think using `setScreenshotTaken` as the dependency works here since `currDOMState` should be set every time the current hovered element changes, whereas `screenshotTaken` only gets set when an element is clicked.

2022-09-07 15:03 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +    if (isValidEmail && isBrowser) {
Turns out there's already a duplicate `isBrowser` check in `handleScreenshot.js` when getting the `dataUri` so removing this one!

2022-09-07 15:07 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/FeedbackCard.js
>    bottom: 256px;
Changed it for now to the updated Card placement from DOP-2400 which was design-approved (the rest of the UI changes will also be incorporated once 2400 is merged)

2022-09-07 18:46 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/components/ScreenshotButton.js
> +            <div className="overlayInstructions" css={instructionsBorderStyling} />
Which container are you referring to?

2022-09-08 20:17 UTC, seungpark approved these changes
these changes LGTM. one bug i did notice was that it would persist the absolute size/position of selection on window resize. can take this as a follow up feature if need be

2022-09-08 20:17 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/context.js
> +    document.body.style.overflow = 'visible';
can remove. no scroll hook turns off on component unmount

2022-09-09 16:59 UTC, allisonmui9 approved these changes
looks super cool! lgtm - thank you!

2022-09-13 14:08 UTC, merged