DOP-3238: style ul in plp
mongodb/snooty pull request #700
Opened 2022-09-21 14:41 UTC by seungpark

### Stories/Links:

[DOP-3228](https://jira.mongodb.org/browse/DOP-3238)

### Current Behavior:

[prod realm](https://www.mongodb.com/docs/realm/)
[prod server docs](https://www.mongodb.com/docs/manual/)

### Staging Links:

[staged realm docs](https://docs-mongodbcom-integration.corp.mongodb.com/42d5ec303ec60950a7fa78150c25572394e31562/master/realm/seung.park/DOP-3228/)
[staged server docs](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/seung.park/DOP-3228/)

### Notes:
minor change to add grid-column and max-width to ul's as same as paragraph tags in PLP

2022-09-21 15:58 UTC, allisonmui9 requested changes
I think the Realm PLP first paragraph content is cutting off awkwardly. 
Is it possible to let it stretch the width of who normal content pages would stretch? 
<img width="1449" alt="Screen Shot 2022-09-21 at 11 58 32 AM" src="https://user-images.githubusercontent.com/57725481/191553405-1c32efd5-393b-4bf3-98cb-b0042ecdfc33.png">

2022-09-21 18:15 UTC, seungpark commented
> 

@allisonmui9 here's the change requested: https://docs-mongodbcom-integration.corp.mongodb.com/42d5ec303ec60950a7fa78150c25572394e31562/master/realm/seung.park/DOP-3228/

discussed offline, this paragraph for realm only should be extendable to regular content width ie https://www.mongodb.com/docs/manual/tutorial/getting-started/

2022-09-21 19:10 UTC, allisonmui9 approved these changes

2022-10-04 14:56 UTC, rayangler approved these changes

2022-10-04 15:14 UTC, merged