DOP-3128: Add support for FWv3 across viewport sizes
mongodb/snooty pull request #705
Opened 2022-09-30 14:40 UTC by gjchong25

### Stories/Links:

[DOP-3128](https://jira.mongodb.org/browse/DOP-3128)

### Current Behavior:

[Compass Current Behavior ](https://docs-mongodbcom-integration.corp.mongodb.com/testing/compass/grace.chong/DOP-2400/)

### Staging Links:

[Compass Staging](https://docs-mongodbcom-integration.corp.mongodb.com/testing/compass/grace.chong/DOP-3128/)

### Notes:

This PR handles displaying the feedback widget across multiple viewports and screensizes (mobile, tablet, desktop, etc). There are 5 total screensizes supported: 1920px, 1440px, 1024px, 768px, 320px. This PR also ensures that the card does not float around the screen unexpectedly when the screen size changes.

2022-10-04 14:47 UTC, allisonmui9 requested changes
Looking great! Few comments: 

For tablet size:
- Can we increase the width of the text area and email input? We can reuse the same margins 16px on each side.
<img width="486" alt="Screen Shot 2022-10-04 at 10 33 45 AM" src="https://user-images.githubusercontent.com/57725481/193848684-8723e0bb-2336-40a2-aa91-f67d9503ddaa.png">
-  The first screen categories, can we have the hover state stretch width of the modal? 
<img width="466" alt="Screen Shot 2022-10-04 at 10 34 04 AM" src="https://user-images.githubusercontent.com/57725481/193849414-a8e61de3-14ec-4cab-876e-76be76bbee66.png">

Mobile view:
- The widget should be fixed at the bottom of the docs page. Vs. how it is floating at the bottom left right now. 
<img width="474" alt="Screen Shot 2022-10-04 at 10 34 56 AM" src="https://user-images.githubusercontent.com/57725481/193849534-1970378e-14e1-4383-b376-a0208ba6ce39.png">
- For the first screen, can we decrease the width and center the categories? Looks like the margins should be 56px on each side. Here is the related [design](https://www.figma.com/file/JSybVUxIme1IeEg5jCI9Fv/Feedback-Widget-3.0?node-id=508%3A20187). 
<img width="516" alt="Screen Shot 2022-10-04 at 10 39 48 AM" src="https://user-images.githubusercontent.com/57725481/193850810-61d3cf1f-375e-4927-9ac9-8d6821e60a0f.png">
- For the third screen, can we decrease the with center align the text? Looks like the margins should be 56px on each side. Here is the related [design](https://www.figma.com/file/JSybVUxIme1IeEg5jCI9Fv/Feedback-Widget-3.0?node-id=508%3A20609)
<img width="530" alt="Screen Shot 2022-10-04 at 10 40 10 AM" src="https://user-images.githubusercontent.com/57725481/193850838-d457baf1-9a82-4719-b2ed-7c671b85cfc2.png">
- The second screen, can we increase the width of the text area and email input? margins should be 16px on left and right side. 
<img width="483" alt="Screen Shot 2022-10-04 at 10 40 05 AM" src="https://user-images.githubusercontent.com/57725481/193851027-7374ef8c-c451-4c3c-afd1-e83f230b70f9.png">

Thanks!

2022-10-04 16:46 UTC, seungpark approved these changes
LGTM. looks clean on all viewports! minor comments on screenshot avail, and possible refactoring

2022-10-04 16:46 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/views/CommentView.js
> +        {!isTabletOrMobile && <ScreenshotButton />}
@allisonmui9 verifying this is disabled for tablet. referring to figma and seeing a screenshot selector on tablet
https://www.figma.com/proto/JSybVUxIme1IeEg5jCI9Fv/Feedback-Widget-3.0?page-id=495%3A11970&node-id=508%3A19487&viewport=-147%2C-1325%2C0.17317235469818115&scaling=min-zoom&starting-point-node-id=495%3A16972

2022-10-04 16:46 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import React, { useContext } from 'react';
not required but would ideally have one container object, and apply responsive styling on the component, as opposed to the three container components. there is a new container opened when changing screen size and new CommentView component, therefore loses the comment content

2022-10-10 19:37 UTC, gjchong25 commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import React, { useContext } from 'react';
After speaking with Cassidy, we decided that the use case for resizing the window while writing a comment would be pretty uncommon, so this can be an add-on in the future.

2022-10-11 13:48 UTC, seungpark commented on src/components/Widgets/FeedbackWidget/FeedbackFullScreen.js
>  import React, { useContext } from 'react';
sounds good we can have a follow up ticket for this minor issue 👍

2022-11-17 05:57 UTC, merged