DOP-3267
mongodb/snooty pull request #714
Opened 2022-10-20 13:49 UTC by seungpark

### Stories/Links:

[DOP-3267](https://jira.mongodb.org/browse/DOP-3267)

### Staging Links:

(atlas docs with embedded version testing data)[https://docs-mongodbcom-integration.corp.mongodb.com/3573c5c93d9797fb08a8d0dd288404ea55fe28cf/master/cloud-docs/seung.park/DOP-3267/]

### Notes:
- ToC does not refresh on initial load. may have to refresh the page. this will be addressed in [DOP-3309](https://jira.mongodb.org/browse/DOP-3309)
- currently, if you are on atlas-cli docs and switch the version, it does not refresh the page (only refreshes ToC). this logic should be shared from[ associated version dropdown PR](https://github.com/mongodb/snooty/pull/710)
- if you want to check out the spoofed data, using test data from snooty_dev.metadata with object id 632dfa069ef0f101150750d9

2022-10-21 14:56 UTC, casthewiz reviewed
Staging link looks really good in general - it's so exciting to see this working live!

I think we'll need to set the default selection on a user first visiting the page (seems like active version behavior is correct, it's just not displaying `stable` in the dropdown when visiting the page for the first time in incognito)

2022-10-21 14:56 UTC, casthewiz commented on src/components/Sidenav/TOCNode.js
> +  const hasVersions = !!(options?.versions?.length > 1); // in the event there is only one version, do we show version selector?
If there's only one version, no need to show the version selector afaik 👍

2022-10-21 14:56 UTC, casthewiz commented on src/components/Sidenav/VersionSelector.js
> +    }
Do we want to remove the console.log here before merge?

2022-10-21 16:24 UTC, seungpark commented on src/components/Sidenav/VersionSelector.js
> +    }
this actually requires some elements from [DOP-3266](https://github.com/mongodb/snooty/pull/710/files#diff-0e4db20c7678504170e62381114917943edbd8739de8c5442b32acf9535fec01) as they share logic in parsing from git branch to target url slug

2022-10-21 17:16 UTC, seungpark commented
> Staging link looks really good in general - it's so exciting to see this working live!
> 
> I think we'll need to set the default selection on a user first visiting the page (seems like active version behavior is correct, it's just not displaying `stable` in the dropdown when visiting the page for the first time in incognito) edit: not sure if this is what you meant by "ToC does not refresh on initial load. may have to refresh the page"

it's a bug with setting the default version if not found. this has been addressed with https://github.com/mongodb/snooty/pull/716

discussed offline and merged that logic into this pr

2022-10-21 20:59 UTC, seungpark commented
@casthewiz i made a feature branch for the two issues DOP-3267 and DOP-3266 since they rely on each other. can merge to main branch after verifying both features + unit tests

2022-10-26 15:57 UTC, sandynguyenn commented
For [atlas docs with embedded version testing data](https://docs-mongodbcom-integration.corp.mongodb.com/35a40e54609f1a5d7f4da7564184d68385cfe7a6/master/cloud-docs/seung.park/DOP-3267/)

- In the design prototype, the selector input is only supposed to show on hover but its in active state in staging. Is this one of the constraints you mentioned @seungpark ? With the current active selector state in the TOC, I worry that it will be distracting to users when scanning other category titles -- hence why the original design has the selector in an inactive state that is less distracting.

2022-10-26 17:09 UTC, seungpark commented
> For [atlas docs with embedded version testing data](https://docs-mongodbcom-integration.corp.mongodb.com/35a40e54609f1a5d7f4da7564184d68385cfe7a6/master/cloud-docs/seung.park/DOP-3267/)
> 
> * In the design prototype, the selector input is only supposed to show on hover but its in active state in staging. Is this one of the constraints you mentioned @seungpark ? With the current active selector state in the TOC, I worry that it will be distracting to users when scanning other category titles -- hence why the original design has the selector in an inactive state that is less distracting.

good catch @sandynguyenn ! last commit addresses this and i updated the staging links above

2022-10-26 17:18 UTC, sandynguyenn approved these changes
lgtm

2022-10-26 19:01 UTC, allisonmui9 requested changes
Thanks Seung for moving so quick! Just a few comments: 

- Sorry for the inconvenience, but can we change the button to what you had before? where it showed the button right away? I think it looks more clean, but having the button and its hover state blend in with the rest of the menu (especially when being hovered on) take away from the usability. I think having it show the button style is ultimately better for the user's usability. 
- When the user clicks the button and the menu expands, can we have the caret in the button change to caret up? 

Thank you!

2022-10-26 20:15 UTC, seungpark commented
> Thanks Seung for moving so quick! Just a few comments:
> 
> * Sorry for the inconvenience, but can we change the button to what you had before? where it showed the button right away? I think it looks more clean, but having the button and its hover state blend in with the rest of the menu (especially when being hovered on) take away from the usability. I think having it show the button style is ultimately better for the user's usability.
> * When the user clicks the button and the menu expands, can we have the caret in the button change to caret up?
> 
> Thank you!

@allisonmui9  sounds good! thank you for the catch on accessibility 👍 
as for the caret, this is default behavior from LG/select components https://www.mongodb.design/component/select/example/ i'll open a request ticket for this caret feature if that works with you

2022-10-27 15:36 UTC, allisonmui9 approved these changes
lgtm thank you!

2022-10-28 21:12 UTC, rayangler approved these changes
This looks really cool! Just one question about whether we should remove some commented code

2022-10-31 13:32 UTC, merged