DOP-3355: fix LG component styling
mongodb/snooty pull request #739
Opened 2022-11-23 22:43 UTC by seungpark

### Stories/Links:

DOP-3355

### Current Behavior:

cloud-docs
https://www.mongodb.com/docs/atlas/

docs-landing
https://www.mongodb.com/docs/

guides
https://www.mongodb.com/docs/guides/

### Staging Links:

cloud-docs
https://docs-mongodbcom-integration.corp.mongodb.com/3ad86d933dd19e725d34d779fc43702ac26319c1/master/cloud-docs/seung.park/DOP-3355/import/

docs-landing
https://docs-mongodbcom-integration.corp.mongodb.com/3ad86d933dd19e725d34d779fc43702ac26319c1/master/landing/seung.park/DOP-3355/

guides
https://docs-mongodbcom-integration.corp.mongodb.com/3ad86d933dd19e725d34d779fc43702ac26319c1/master/guides/seung.park/DOP-3355/

### Notes:
there seems to be a clash of style rules for links still. since we use a mix of gatsby and leafygreen Link components, we should be using a combination of css from emotion/react and css prop, or classname with cx+css from leafygreen/emotion

2022-11-29 21:03 UTC, allisonmui9 approved these changes
Heading styling LGTM. Answering your question in the notes, the caret should be top aligned (what's live today).

2022-11-30 16:51 UTC, rayangler requested changes
Pretty much LGTM! Will formally approve once the extra console log is removed

> when components are rendered "as" something else, which styling should take precedence?

In general, I think this would be case by case, depending on the components being used. For something like the side nav items, we'd probably want `SideNavItem`'s styling to take precedence over the `Link` component's styling, since the main goal of the `as` prop in this case is using `Link`'s functionality

2022-11-30 17:38 UTC, casthewiz commented on src/components/Sidenav/GuidesTOCTree.js
> +  console.log('GuidesTOCTree');
I just pushed a commit to remove this 👀

2022-11-30 18:50 UTC, rayangler approved these changes

2022-11-30 19:14 UTC, casthewiz commented on src/components/Link.js
> +    <LGLink className={cx([LGlinkStyling])} href={to} hideExternalIcon={hideExternalIcon} {...other}>
I want to assume that any iterable args passed in would be spread, but 🤔

2022-12-06 16:20 UTC, merged