DOP-3367: Override LG Select mobile font-size styles
mongodb/snooty pull request #756
Opened 2023-01-26 15:28 UTC by mmeigs

### Stories/Links:

[DOP-3367](https://jira.mongodb.org/browse/DOP-3367)

### Current Behavior:

[Current](https://www.mongodb.com/docs/manual/tutorial/query-documents/)

### Staging Links:

[Staging Link with error message and description added](https://docs-mongodbcom-integration.corp.mongodb.com/master/docs/matt.meigs/DOP-3367-select-mobile/tutorial/query-documents/)

### Notes:

LG Select (along with all children) have mobile font-sizes of 16px. Our site's baseFontSize is 13px. This leads to all fonts in our Select to actually get larger as screensize transitions below 1024px.

This PR overrides the font-size for Select's label, description, error message, and options.

2023-01-27 21:10 UTC, seungpark requested changes
think we need to scope this broader than Tab Selectors here ie. our Select component

2023-01-27 21:10 UTC, seungpark commented on src/components/Tabs/TabSelectors.js
> +        @media ${screenSize.upToLarge} {
not sure if we want to only target TabSelectors.

seems like this also affects version selector in docs menu in mobile view.

would suggest using the `size` prop from [LG Select ](https://www.mongodb.design/component/select/documentation/)

tested this locally but seeing weird behavior -> `small` is good on mobile but large on desktop? `default` looks good on desktop but large on mobile? weird... we can use media query to determine this value though

2023-01-30 18:46 UTC, mmeigs commented on src/theme/docsTheme.js
> +  large: 1024,
I added a note for this in the PR description, but I realized LG breakpoints are one pixel off from ours. This closes that gap so we don't have awkward stylings at 1024px width screensize.

2023-02-01 15:55 UTC, seungpark approved these changes
minor. we can do the styling outside of the component fn and pass it to the cx fn. otherwise LGTM 👍

2023-02-01 15:55 UTC, seungpark commented on src/theme/docsTheme.js
> +  large: 1024,
good catch! tested with the breakpoint definitions below, ie. upToLarge

2023-02-01 16:15 UTC, mmeigs commented
> minor. we can do the styling outside of the component fn and pass it to the cx fn. otherwise LGTM 👍

I do think that looks cleaner and usually has a lot of benefits that way. But I don't know of a way to still utilize the `screenSize` property from `useTheme` outside the component unless:
-  I use `styled` instead of `css` but also prop-drill `screenSize` into `Select` just so that emotion can access it? 
- Or I could hard code the media query. 

But both of those seem to be less clean than the current solution.
Do you know of a different way to handle this?

2023-02-01 23:01 UTC, seungpark commented
> 

we can import theme from the module itself ([example](https://github.com/mongodb/snooty/blob/master/src/components/Card/index.js#L37-L41)) and write a media query for mobile sizes. when working with LG components (in this case LG select), we should try to follow their pattern and use their emotion package ie.

```
const styling = css`
  some styling here
`;
.
.
.
<Leafygreencomponent
     className={cx(styling)} />
```

2023-02-02 17:02 UTC, seungpark approved these changes
thanks for the update!

2023-02-02 18:38 UTC, merged