Dop 3290
mongodb/snooty pull request #763
Opened 2023-02-06 18:03 UTC by branberry

### Stories/Links:

DOP-NNNN

### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

2023-02-23 13:50 UTC, schmalliso commented
Question! Is this applying only for drivers sites, or if I searched from https://www.mongodb.com/docs/atlas/ would we also default to search Atlas?

2023-02-23 15:26 UTC, branberry commented
Hi Allison! From my understanding, we only do this for driver sites. I could be mistaken of course

2023-02-23 19:28 UTC, seungpark requested changes
A/C states general mechanism for all docs, but seems like this is targeted towards a hardcoded drivers set. not sure how stable that `status` page is (from the Jira issue) but it doesn't seem like a bad idea to cross check with that response and current project/branch info from snooty metadata

2023-02-23 19:28 UTC, seungpark commented on src/utils/drivers-set.js
> +export const driversSet = new Set(['golang', 'ruby', 'php', 'csharp', 'java', 'node']);
extending @schmalliso 's question, can we fetch this async via https://docs-search-transport.mongodb.com/status and only include this from the response? as for staging we can append a result to the response ie `node-v5.0` (and get branch from useSnootyMetadata() )

2023-02-23 19:28 UTC, seungpark commented on src/components/Header/index.js
> +  // For some branches, such as master, the gitBranchName in the MongoDB collection differs
per comment below in drivers-set.js, we can call useSnootyMetadata for branch info here (since it can be not in active versions)

2023-02-23 19:42 UTC, branberry commented on package.json
> +    "@mdb/consistent-nav": "1.2.32",
I needed to bump the version because there was a bug in the unified nav that was addressed in the [latest release](https://github.com/10gen/consistent-nav/pull/146/files)

2023-02-23 20:36 UTC, seungpark commented on package.json
> +    "@mdb/consistent-nav": "1.2.32",
gotcha 👍 https://github.com/10gen/consistent-nav/pull/142

2023-02-24 15:58 UTC, branberry commented
Converting this back to draft as I work on addressing issues discussed in standup. Namely, the issue with mapping to manifest values from the docs-search-transport

2023-02-24 17:16 UTC, branberry commented
@seungpark @schmalliso I reached out to Rachelle and she confirmed that this change should be for all docs sites, and not just the drivers sites.

2023-02-27 23:28 UTC, rayangler reviewed
I wanted to touch base on an edge case first to check what the ideal behavior is. Otherwise, looks good to me

2023-02-28 00:35 UTC, branberry commented on src/components/Header/index.js
> +  const projectManifest = `${project}-${branch}`;
Hi Raymund! Thank you for pointing this out. I actually updated the atlas app services function that returns the search manifest mapping to account for these variations in the search manifest name. We can discuss some time tomorrow, and I'll update the PR to reflect this change.

2023-02-28 15:41 UTC, rayangler commented on src/components/Header/index.js
> +  const projectManifest = `${project}-${branch}`;
Makes sense! Taking a look at the change

2023-02-28 18:09 UTC, rayangler commented on src/components/Header/index.js
> +  if (project in searchPropertyMapping.projectToSearchMap) {
It might be good to include a check if `searchPropertyMapping.projectToSearchMap` exists. Otherwise, building might result in an error when `searchPropertyMapping` is still an empty object by default

2023-02-28 18:09 UTC, rayangler commented on src/components/Header/index.js
> +   * called "propertyToSearchMap". This map contains a mapping from
(Nit) Should probably update `propertyToSearchMap` to `projectToSearchMap` in this comment

2023-02-28 18:09 UTC, rayangler commented on src/components/Header/index.js
> +   * is currently in the DRAFT state, and is not included at this time.
Small reminder that we can remove this note from the comment now!

2023-02-28 18:16 UTC, rayangler approved these changes
LGTM! I like how the custom mapping for edge cases is in the Atlas App Services function so we can easily alter if needed

2023-02-28 18:18 UTC, merged