Feature/DOP-3501
mongodb/snooty pull request #781
Opened 2023-03-13 16:47 UTC by caesarbell

### Stories/Links:

DOP-3501

### Current Behavior:

N/A

### Staging Links:

N/A

### Notes:

The ask for the ticket [DOP-3501](https://jira.mongodb.org/browse/DOP-3501), was to provide the ability to handle a certain query param to be used which would force certain elements to not render. The goal is to use this for PathFactory, in hopes they can use the new URL + query param and hide the side nav and header to reduce the distraction or navigation away from the content that will be in focus.

2023-03-14 17:23 UTC, seungpark requested changes
AC mentioned using query-string to parse the Location object properties. is this not part of the requirements?

2023-03-14 17:23 UTC, seungpark commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
do we have the differentiate for the flag?

seems like we can useLocation and use query-string as in the [searchResults](https://github.com/mongodb/snooty/blob/master/src/components/SearchResults/SearchResults.js#L276), unless i'm missing something here

2023-03-14 19:59 UTC, caesarbell commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
@seungpark good call out. I was unaware of these methods that already exist in the codebase. With the search can we limit the value? For our requirement, this should be locked down to a particular query value i.e. `? presentation` or whatever value is agreed on for use of PathFactory.

2023-03-14 20:42 UTC, caesarbell commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
@seungpark just out of curiosity, why are we pulling in a 3rd party library for parsing query strings when we can use native JS methods to handle the parsing?

2023-03-14 20:49 UTC, caesarbell commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
I might have typed before looking at the full question so from lines 95 - 98 I have this logic in place to handle the difference between prod & stag vs dev. The URL structure on dev has the hash trailing at the end of the routes i.e. http://localhost:8000/node/caesarbell/master/quick-start/#install-node-and-npm. So to handle the hashing and not force the developer to add the query param in between the trailing `/` and `#`  I added this logic for presentation development mode.  Pls let me know if that makes sense.

2023-03-14 21:38 UTC, seungpark commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
discussed offline diffs on anchors and query params. useLocation is preferred because it's [used by gatsby](https://www.gatsbyjs.com/docs/reach-router-and-gatsby/) under the hood

2023-03-14 22:29 UTC, caesarbell commented on src/layouts/index.js
> +    return process.env.GATSBY_SNOOTY_DEV ? forPresnetationModeLocalDev() : forPresentationMode();
@seungpark good point. I pushed up the changes.

2023-03-15 13:44 UTC, seungpark approved these changes
think we missed a few spots to sport "presentation mode" ie. feedback widget and footer. these can be found in DocumentBody component

2023-03-15 13:44 UTC, seungpark commented on src/layouts/index.js
> +  const { search } = useLocation();
this works well! tested locally and able to get the preview 👍

2023-03-15 14:02 UTC, caesarbell commented
> think we missed a few spots to sport "presentation mode" ie. feedback widget and footer. these can be found in DocumentBody component

Totally missed this. Thanks for catching that.

2023-03-15 14:45 UTC, seungpark commented
as for current behavior vs staging links, we have an [npm script](https://github.com/mongodb/snooty/blob/master/package.json#L33) that builds and stages the changes to S3, and the link provided should give us a preview of the changes.

2023-03-15 22:30 UTC, seungpark commented on src/components/Sidenav/Sidenav.js
> +        {!isInPresentationMode && (
can we call this on the layout file? can omit <Sidenav entirely

2023-03-15 22:31 UTC, seungpark commented on src/components/Widgets/index.js
> +      {!isInPresentationMode && (
similar here, we can omit from <Widgets> from DocumentBody

2023-03-15 22:34 UTC, seungpark commented on src/layouts/index.js
> +  location: PropTypes.shape({
can remove if using the hook for location

2023-03-16 02:06 UTC, caesarbell commented on src/components/Sidenav/Sidenav.js
> +        {!isInPresentationMode && (
The grid layout focuses on two areas, side-nav, and content, if we have the logic in the layout and omit the `<Sidenav` entirely it breaks the grid layout. i.e.

```
const GlobalGrid = styled('div')`
  display: grid;
  grid-template-areas:
    'header header'
    'sidenav contents';
  grid-template-columns: auto 1fr;
  grid-template-rows: auto 1fr;
`;
```

2023-03-16 02:08 UTC, caesarbell commented on src/components/Widgets/index.js
> +      {!isInPresentationMode && (
Similarly here, if we omit on the entire DocumentBody i.e. 

```
<Widgets
        location={location}
        pageOptions={page?.options}
        pageTitle={pageTitle}
        publishedBranches={getNestedValue(['publishedBranches'], metadata)}
        slug={slug}
        isInPresentationMode={isInPresentationMode}
      >
        <FootnoteContext.Provider value={{ footnotes }}>
          <Template {...props}>
            {pageNodes.map((child, index) => (
              <ComponentFactory key={index} metadata={metadata} nodeData={child} page={page} slug={slug} />
            ))}
          </Template>
        </FootnoteContext.Provider>
      </Widgets>
```

The site will not build correctly. Good suggestion, I did think about this approach at first. Let me know if you have any more questions about this.

2023-03-17 13:52 UTC, seungpark commented on src/components/Widgets/index.js
> +      {!isInPresentationMode && (
see responded comment above regarding grid

2023-03-17 14:06 UTC, caesarbell commented on src/components/Widgets/index.js
> +      {!isInPresentationMode && (
This one is a little different than the one above. This had to do with the Widget Provider not rendering crashing the site build, but if you prefer for it to be `one hook / one template` I can look more into refactoring this as well.

2023-03-17 14:11 UTC, caesarbell commented on src/components/Sidenav/Sidenav.js
> +        {!isInPresentationMode && (
That is fine, I can make the changes to the grid rather than passing the boolean via props and hiding the side nav content.

2023-03-17 18:57 UTC, seungpark approved these changes
this LGTM 👍 
thanks for putting this all together !

2023-03-17 18:57 UTC, seungpark commented on src/components/Sidenav/Sidenav.js
> +                  to={isGuidesTemplate ? slug : '/'}
minor. i think this change was unintentional

2023-03-17 22:05 UTC, merged