Dop 3566
mongodb/snooty pull request #792
Opened 2023-04-06 18:02 UTC by caesarbell

### Stories/Links:

DOP-3566

### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

This PR focuses on the testing for https://github.com/mongodb/snooty/pull/781

![Screenshot 2023-04-06 at 1 42 55 PM](https://user-images.githubusercontent.com/5807473/230459294-b57ff2b8-028f-4f01-8a09-37c54c240fda.png)

2023-04-07 17:51 UTC, seungpark requested changes
this looks great 👍 mocking location.search works as expected. requesting to add snapshots in the two cases

2023-04-07 17:51 UTC, seungpark commented on tests/unit/Presentation.test.js
> +    it('renders the footer', () => {
minor nitpick. since we are using the same rendered tree for each test, we can combine these assertions into a single test.

also would add a snapshot in the two cases

2023-04-10 21:27 UTC, rayangler reviewed
Looks good! Just wanted to bring up one thing that may be helpful for these tests. Feel free to let me know if it's not a good idea. Otherwise LGTM

2023-04-10 21:27 UTC, rayangler commented on tests/unit/Presentation.test.js
> +          <DocumentBody location={window.location} pageContext={mockPageContext} />
The [SearchResults test](https://github.com/mongodb/snooty/blob/90eed3bc7600a9e0fd763109fee49bec6c6badd4/tests/unit/SearchResults.test.js#L79) has a mock of `useLocation` that we can probably turn into a generalized util function for something like this. 

Do you think that mocked hook would be useful for this case? It might help with minimizing some of the setup here + would be nice to have since we're introducing more tests with query strings

2023-04-17 15:41 UTC, caesarbell commented on tests/unit/Presentation.test.js
> +    it('renders the footer', () => {
I will condense the assertions into a single test.

2023-04-17 17:56 UTC, caesarbell commented on tests/unit/Presentation.test.js
> +          <DocumentBody location={window.location} pageContext={mockPageContext} />
@rayangler good call. Turning the `mockLocation` into a reusable utility help reduce the steps needed for the presentation test. In another PR we can update the [SearchREsults Test](https://github.com/mongodb/snooty/blob/90eed3bc7600a9e0fd763109fee49bec6c6badd4/tests/unit/SearchResults.test.js#L79) to use the new utility function.

2023-04-17 19:34 UTC, rayangler approved these changes
LGTM!

2023-04-19 15:48 UTC, merged