DOP-3599
mongodb/snooty pull request #801
Opened 2023-05-01 19:51 UTC by caesarbell

### Stories/Links:

DOP-3599

### Current Behavior:

The page nodes contain a `position` field which isn't needed anymore.

```js
page nodes {
  type: 'root',
  position: { start: { line: 0 } },
  children: [
    {
      type: 'target',
      position: [Object],
      children: [Array],
      domain: 'std',
      name: 'label',
      html_id: 'std-label-python-language-center'
    },
    { type: 'section', position: [Object], children: [Array] }
  ],
  fileid: 'python.txt',
  options: { headings: [ [Object] ] }
}
```

### Staging Links:

After adding the new utility we have the ability to remove the `position` field

```js
page nodes {
  type: 'root',
  children: [
    {
      type: 'target',
      children: [Array],
      domain: 'std',
      name: 'label',
      html_id: 'std-label-python-language-center'
    },
    { type: 'section', children: [Array] }
  ],
  fileid: 'python.txt',
  options: { headings: [ [Object] ] }
}
```

### Notes:

2023-05-01 20:25 UTC, i80and commented on src/utils/remove-nested-value.js
> +    Object.entries(entry).forEach(([key, val]) => {
What do we get by iteratomg over each key/value pair rather than inspecting `entry[t]` and `entry[k]` directly?

e.g.

```
if (entry.hasOwnProperty(t)) {
    delete entry[t];
}

if (entry.hasOwnProperty(k)) {
    const children = entry[k];
    if (Array.isArray(children) && children.length > 0) {
        removeNestedValue(t, k, children);
    }
}
```

2023-05-01 20:25 UTC, i80and commented on src/utils/remove-nested-value.js
> +const removeNestedValue = (t, k, arr) => {
Long descriptive variable names would preferable; e.g. `deletionKey`, `arrayChildrenKey`, and `arr`

2023-05-01 22:45 UTC, caesarbell commented on src/utils/remove-nested-value.js
> +    Object.entries(entry).forEach(([key, val]) => {
Good point. After reviewing, we don't get any extra benefits from iterating over each key/value. Thanks for sharing an example as well.

2023-05-01 22:58 UTC, i80and requested changes
Just one change needed from me!

2023-05-01 22:58 UTC, i80and commented on src/utils/remove-nested-value.js
> + * - t: the target to have deleted
Comment needs to be updated! 😸

2023-05-01 23:14 UTC, caesarbell commented on src/utils/remove-nested-value.js
> + * - t: the target to have deleted
💯  how did I miss that? In my mind, I was cleaning that up already. 🤣

2023-05-01 23:18 UTC, caesarbell commented on src/utils/remove-nested-value.js
> + * - t: the target to have deleted
@i80and done. Thank you again for catching that.

2023-05-02 21:02 UTC, i80and approved these changes
:shipit:

2023-05-03 20:36 UTC, seungpark approved these changes
very clean! LGTM

2023-05-03 21:44 UTC, schmalliso approved these changes
:shipit:

2023-05-04 15:14 UTC, caesarbell commented on src/utils/remove-nested-value.js
> +  if (!arr) return undefined;
@i80and making this change before merging.

2023-05-04 15:29 UTC, merged