DOP-3785: adding a persistent search bar
mongodb/snooty pull request #843
Opened 2023-06-21 20:52 UTC by bianca-laube

### Stories/Links:

DOP-3785

### Current Behavior:

https://www.mongodb.com/docs/search/?q=test
![Screenshot 2023-06-21 at 4 42 22 PM](https://github.com/mongodb/snooty/assets/135655735/060f0cd5-202f-4344-bd82-37950beca883)

### Staging Links:

https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/bianca.laube/DOP-3785/search/index.html?q=test
![Screenshot 2023-06-21 at 4 49 14 PM](https://github.com/mongodb/snooty/assets/135655735/6f6dd6cc-ec15-42ef-bff5-ea601e475298)

### Notes:

Things Changed:
- Updated header
- The staging link goes automatically to the search page since if you try to go the search page through the home page it leaves the staging link. However, the first word given is taken from that search bar, from the header and automatically loaded to the new persistent search bar. 
- was able to add the new leafygreen-ui search-input for the search bar

2023-06-28 14:51 UTC, seungpark requested changes
looks great!! thanks for putting this together @bianca-laube

a couple comments on persisting the search bar on empty results. will need to consult with Product team to verify base case scenarios

2023-06-28 14:51 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +              <H1 style={{ color: '#00684A', paddingBottom: '40px' }}> Search Results</H1>
and a final note, we should put this behind the feature flag from @mmeigs 's [PR](https://github.com/mongodb/docs-worker-pool/pull/845) for feature flags :)

2023-06-28 19:51 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +              <H1 style={{ color: '#00684A', paddingBottom: '40px' }}> Search Results</H1>
- updated it so on empty search the header and search bar will stay
- placeholder of the search input changed to "Search"
- Using H1 from leafy green
new staging link to view changes : 
https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/bianca.laube/DOP-3785/search/index.html?q=$test

2023-06-29 19:22 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +              <H1 style={{ color: '#00684A', paddingBottom: '40px' }}> Search Results</H1>
new features are pushed behind a feature flag now and old features will show if feature flag is set to false

2023-06-29 22:11 UTC, seungpark requested changes
some minor differences in behavior from whats on prod vs this branch (with flag set to "false") PTAL !

2023-06-29 22:11 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                <EmptyResultsContainer>
this should be separate of SearchResultsContainer to prevent the grid layout taking over. as an alternative, we can style this to be `grid-area: results;` as well

2023-06-29 22:11 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                    setSearchTerm(event.target[0].value);
minor nitpick. we should prevent users from entering cleared searches, or if we do allow, show the empty placeholder:

(ss below shows entering cleared input after initial load)
![image](https://github.com/mongodb/snooty/assets/13054820/11ac06ff-5c89-49e1-9dbc-dae196081ebf)

2023-07-05 14:37 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +              <HeaderText>Search results for "{searchTerm}"</HeaderText>
Just pushed a commit that when flag is false, gets rid of the header if search is empty and added proper grid layout

2023-07-05 14:39 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                <EmptyResultsContainer>
Added css with correct grid styling, had to add the css to this instance of EmptyResultsContainer so it wouldn't mess up the css for the emptyResultsContainer on line 409

2023-07-05 14:40 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                    setSearchTerm(event.target[0].value);
now on empty search result for the new persistent search bar is will show the empty result container instead of nothing

2023-07-06 13:39 UTC, seungpark requested changes
some minor styling nitpicks to keep prod untouched. also not seeing loading states with the new component state variables. PTAL! 🙏

2023-07-06 13:39 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                <SearchInput
minor nitpick on styling.
mockup shows search bar horizontally extends over the search results, out into the search filters on desktop:

![image](https://github.com/mongodb/snooty/assets/13054820/d2ba705a-ada3-4c08-94fa-1aa69585bede)

but on branch, ends with the width of the search results:

![image](https://github.com/mongodb/snooty/assets/13054820/5b0c4787-d026-442d-a703-3069d71fcdb3)

i actually prefer the second but would verify this is passable or not with design

2023-07-06 13:39 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                      <StyledSearchResults>
these loading skeletons are not being rendered since `!!searchTerm` always validates to true with the updated logic of searchTerm and searchField

2023-07-06 13:39 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                    grid-area: results;
now this is taking up a different grid space vs prod (with `GATSBY_TEST_SEARCH_UI` flag set to false)

![image](https://github.com/mongodb/snooty/assets/13054820/710fed0c-d1a1-41c2-b6e9-8185669a4dc1)

vs prod

![image](https://github.com/mongodb/snooty/assets/13054820/760d6a38-d95b-45a5-9fa0-beb76af1bf85)

2023-07-06 17:53 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                <SearchInput
Confirmed with Iz that the search-bar ending in line with the search results is okay, so no changes needed :)

2023-07-06 17:54 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                      <StyledSearchResults>
updated so now when feature flag is true loading skeleton will show up.  (lines 454-455)

2023-07-06 17:58 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                    grid-area: results;
fixed this issue! took the empty results container out of the search Results container. Then for when the feature flag is TRUE re-put the headercontainer in that section. Not the perfect solution but couldn't find another way for it to work correctly for the grid and the feature flag simultaneously.

2023-07-06 20:12 UTC, seungpark reviewed
this overall LGTM. one minor functional catch below (onSubmit function for SearchInput)

thanks again for putting this together @bianca-laube !

2023-07-06 20:12 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +                      setSearchResults([]);
this is causing a infinite load when searching for same term, due to useEffect not firing

```suggestion
                      const newValue = event.target[0]?.value;
                      if (newValue === searchTerm) return;
                      setSearchResults([]);
```

can also setSearchTerm(newValue) here

2023-07-07 14:04 UTC, mmeigs reviewed
Looks great! I believe there are a couple unused conditionals! Check me on it though, because there are so many layers to unpack.

Also, I feel like I may have found a bug with our search, but it's not a part of this ticket. Any one letter search seems to hang in loading state oddly. Something to keep an eye on. Bonus points!

2023-07-07 15:01 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
>          {!!searchTerm ? (
You're right! I was able to get rid of the double redundancy checks. Forgot to get rid of them after I switched up the format for the empty container. Thanks for checking that !

2023-07-10 22:14 UTC, seungpark approved these changes
this looks great! minor styling issue below and a possible refactor (not blocking). besides that LGTM !

2023-07-11 14:40 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
>                <EmptyResultsContainer>
Took notes of this comment! Will be implementing in DOP-3786

2023-07-11 14:42 UTC, merged