Dop 3786: updating no search results modal
mongodb/snooty pull request #854
Opened 2023-07-13 20:24 UTC by bianca-laube

### Stories/Links:

DOP-3786

### Current Behavior:

https://www.mongodb.com/docs/search/?q=%22failed%20to%20find%20a%20plan%22*
![Screenshot 2023-07-13 at 4 10 23 PM](https://github.com/mongodb/snooty/assets/135655735/5db65c1d-c2ef-4194-9e7c-65d6fe08b263)

### Staging Links:

https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/bianca.laube/DOP-3786/search/index.html?q=%22failed%20to%20find%20a%20plan%22*
![Screenshot 2023-07-13 at 4 12 01 PM](https://github.com/mongodb/snooty/assets/135655735/fc3af012-b356-482b-ad72-a86317b271c4)

### Notes:
#### Changes

The four different states for empty/no results search (and what to look for when testing)
confirmed by Iz

1. Empty search input from the top nav search bar
    - PROD
        https://www.mongodb.com/docs/search/?q=
![Screenshot 2023-07-13 at 4 09 46 PM](https://github.com/mongodb/snooty/assets/135655735/e8c6c46c-541c-4966-92f1-0912cb5769e1)
        
    - NEW UI (we don't want the modal to show)
        https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/bianca.laube/DOP-3786/search/index.html?q=
![Screenshot 2023-07-13 at 4 15 53 PM](https://github.com/mongodb/snooty/assets/135655735/b01de05c-4bd3-4dc3-9e73-0cdfec0822fb)

2. Empty search input from persistent search bar
    - if after they input something from the top nav search and they delete it in the persistent search bar and then hit enter, it should show the ************************no results module************************  and not null

![Screenshot 2023-07-13 at 4 21 48 PM](https://github.com/mongodb/snooty/assets/135655735/7ac2aa66-eba0-4f70-b30b-f6a2c94222a6)
3. Non-empty search input but no search results 
    - should show **********************************no results module**********************************
    ![Screenshot 2023-07-13 at 4 12 01 PM](https://github.com/mongodb/snooty/assets/135655735/fc3af012-b356-482b-ad72-a86317b271c4)
4. Non-empty search input but when filter selected, no results
    - should show ****************************no results module****************************
![Screenshot 2023-07-13 at 4 18 15 PM](https://github.com/mongodb/snooty/assets/135655735/2032766b-7ce4-4c9f-8cba-1158afcb6779)

* everything else should work correctly as before
* when feature flag is false, prod should work the exact same as before

2023-07-14 14:00 UTC, seungpark requested changes
seeing a pending loading screen when entering /search page https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/bianca.laube/DOP-3786/search/index.html

seems to be stemming from searchResults changes atm

2023-07-14 18:22 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +                      if (!!newValue) setSearchFinished(false);
thanks for catching that error! fixed now the value is init set to empty string

2023-07-17 18:06 UTC, rayangler commented on src/components/SearchResults/SearchResults.js
> +    if (q === '') setSearchFinished(true);
If there is no search query (such as when navigating to `/search`), these if statements may never be resolved since `q` is undefined. Would checking for `!q` work for this use case?

2023-07-17 19:09 UTC, bianca-laube commented on src/components/SearchResults/EmptyResults.js
> +  color: var(--gray-dark-1-new, #5c6c75);
thanks for noticing that! now all fixed :)

2023-07-17 19:14 UTC, bianca-laube commented on src/components/SearchResults/SearchResults.js
> +    if (q === '') setSearchFinished(true);
yes thanks for catching that !

so the reason i didn't notice this before is because I was testing init loading state with `/search/?q=` since that is the extension that occurs when you empty search from the top nav. but you're correct that if someone just deletes the `?q=` portion from the url that it should not stay in a constant loading state so that is now fixed! 
(also just want to @seungpark since he also noticed this bug)

2023-07-18 16:40 UTC, seungpark commented
what is the expected behavior when landing on search page? from figma, i am seeing just the title and the search bar:
![image](https://github.com/mongodb/snooty/assets/13054820/82b74e49-53be-47d2-8f98-fc835ec0a464)

but on branch, i am seeing the filters and the result count:
![image](https://github.com/mongodb/snooty/assets/13054820/b47acb26-5365-44c4-97e8-66857413ab95)

if this is out of scope, please link the ticket that will address this issue.
also for case 2, (user deletes input and hit enter) should this result in a "no search results"? google search does not allow for empty input, and results in nothing happening on UI end if no input

2023-07-18 19:24 UTC, rayangler approved these changes
LGTM!

2023-07-18 20:15 UTC, seungpark approved these changes
this LGTM. thanks for cleaning it up!

2023-07-18 20:26 UTC, merged