DOP-3938 Search Results Padding and font changes
mongodb/snooty pull request #878
Opened 2023-08-31 19:47 UTC by anabellabuckvar

### Stories/Links:

[DOP-3938](https://jira.mongodb.org/browse/DOP-3938)

### Current Behavior:
"Search Results" heading is currently H1, and the padding between the heading and the search results bar is 40px. Font was changed to H3 and bottom padding to 24px as requested.

_Put a link to current staging or production behavior, if applicable_
https://www.mongodb.com/docs/search/?q=atlas

### Staging Links:

[Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-3938/search/index.html)

### Notes:
UI element listing the number of search results is currently not included in master branch because the master branch currently has unreleased changes related to the search UI. Once the search result count is added, margins must be adjusted again accordingly

2023-09-05 14:04 UTC, schmalliso requested changes

2023-09-05 14:04 UTC, schmalliso commented on src/components/SearchResults/SearchResults.js
> +          <H3 style={{ color: '#00684A', paddingBottom: '24px' }}> Search Results</H3>
So, this isn't clear from the ticket / Figma, but this needs to be *styled* as an H3 while claiming to be an H1 (so that the page still has an H1 and SEO is happy). 

You can use the `as` prop ([docs](https://www.mongodb.design/component/typography/documentation/)) to achieve this goal 😁.

2023-09-06 14:23 UTC, schmalliso commented on src/components/SearchResults/SearchResults.js
> +            {' '}
What's this line for?

2023-09-19 14:03 UTC, rayangler commented on src/components/SearchResults/SearchResults.js
> +          <H3 as="h1" style={{ color: '#00684A', paddingBottom: '24px' }}>
This looks pretty good to me. I'd recommend pulling in the latest changes from `master` first, updating the css since https://github.com/mongodb/snooty/pull/908 touches these same lines, and then updating the staging link to ensure things look okay

2023-09-19 17:01 UTC, anabellabuckvar commented on src/components/SearchResults/SearchResults.js
> +          <H3 as="h1" style={{ color: '#00684A', paddingBottom: '24px' }}>
@schmalliso @rayangler I pulled in the latest changes from master. However, even though I didn't change how the heading is rendered from the changes I made previously, now the header is styled as an H1 if the `as="h1"` prop is included
```
          <H3 as="h1" style={{ color: '#00684A', paddingBottom: '24px' }}>
```

2023-09-19 18:07 UTC, anabellabuckvar commented on src/components/SearchResults/SearchResults.js
> +          <H3 as="h1" style={{ color: '#00684A', paddingBottom: '24px' }}>
Done

2023-09-19 18:25 UTC, schmalliso commented on tests/unit/__snapshots__/Button.test.js.snap
> +  font-family: 'Euclid Circular A',Akzidenz,'Helvetica Neue',Helvetica,Arial,sans-serif;
Where did this little scamp come from?!

2023-09-19 18:26 UTC, casthewiz commented on tests/unit/__snapshots__/CodeIO.test.js.snap
> +  font-family: 'Euclid Circular A',Akzidenz,'Helvetica Neue',Helvetica,Arial,sans-serif;
This font-family change seems odd without a version bump to any of the LG components in the package.json. Can we figure out where it came from? 👀

2023-09-19 18:45 UTC, anabellabuckvar commented on tests/unit/__snapshots__/CodeIO.test.js.snap
> +  font-family: 'Euclid Circular A',Akzidenz,'Helvetica Neue',Helvetica,Arial,sans-serif;
@schmalliso I think somehow just running the snapshot tests added it back in?? I certainly didn't intend to include that. Per [DOP-3783](https://github.com/mongodb/snooty/pull/845), some snapshot tests might still have mentions of `akzidenz`, but " but these are from leafygreen components that will not have access to the font and therefore will not occur."

2023-09-19 18:45 UTC, anabellabuckvar commented on tests/unit/__snapshots__/CodeIO.test.js.snap
> +  font-family: 'Euclid Circular A',Akzidenz,'Helvetica Neue',Helvetica,Arial,sans-serif;
should I just manually re-remove any mentions of `akzidenz` in the snapshot tests?

2023-09-20 14:37 UTC, rayangler commented on src/components/SearchResults/SearchResults.js
> +          <H3 as={H1} style={{ color: '#00684A', paddingBottom: '24px' }}>
(Nit) Is it possible to use a LG `css` variable with `cx` instead of relying on `style`? We have so many different ways to define css, it might be good to enforce some consistency.

Additionally, we can keep `color` as `palette.green.dark2`. We should try to use LG's predefined palette variables when possible for consistency as well.

2023-09-20 14:37 UTC, rayangler commented on tests/unit/__snapshots__/CodeIO.test.js.snap
> +  font-family: 'Euclid Circular A',Akzidenz,'Helvetica Neue',Helvetica,Arial,sans-serif;
I would recommend rerunning `npm ci --legacy-peer-deps` and rerunning the tests. I don't see references to `Akzidenz` in the snapshots locally when doing this

2023-09-20 17:35 UTC, rayangler approved these changes

2023-09-27 15:36 UTC, merged