Dop 4028
mongodb/snooty pull request #911
Opened 2023-09-18 21:15 UTC by anabellabuckvar

### Stories/Links:

[DOP-4028](https://jira.mongodb.org/browse/DOP-4028)

### Current Behavior:
The spacing for the caret dropdown icons on the side nav is slightly out of line
[staging] (https://preview-mongodbrayanglerstg.gatsbyjs.io/cloud-docs/gc-test-img/)
![image](https://github.com/mongodb/snooty/assets/41971124/9f5293dc-29e0-4b3e-a586-cd5740fce99c)

_Put a link to current staging or production behavior, if applicable_

[### Staging Links:](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/newhomepagewhodis/landing/anabella.buckvar/DOP-4028/index.html)

_Put a link to your staging environment(s), if applicable_

### Notes:

As part of [DOP-3989](https://jira.mongodb.org/browse/DOP-3989), some [css](https://github.com/mongodb/snooty/pull/888/files#diff-927f813ea3772395ca9598b2d8d6dda38e38460089aba25bffc443d4859b84cbR37-R39) was added to add a margin for svgs nested in links. It seems that it was necessary for correct spacing because the last link in the [products list](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/) didn't space the arrow correctly due to how the link was being generated. However, the margin fix ended up caused the spacing to change slightly for the caret dropdown icons on the side nav.

2023-09-19 14:26 UTC, rayangler requested changes

2023-09-19 14:26 UTC, rayangler commented on src/components/RefRole.js
> -  }
I'm not sure if removing this logic altogether is desired. This logic is used to help determine how internal references in the docs can be translated to an actual link. Without this, the rendered link doesn't resolve anywhere (the link in the staging link renders okay with the arrow icon, but clicking the link just brings you back to the current page)

Is there another solution we can take that won't affect the way these links are resolved?

2023-09-19 18:48 UTC, anabellabuckvar commented on src/components/RefRole.js
> -  }
I undid the changes to this logic and found the real reason that the last `ProductItem` was rendered with a different svg margin(and, a very slightly different arrow icon). Arrows should be standardized across all links now

2023-09-19 19:33 UTC, rayangler commented on src/components/Link.js
> +      </ArrowRightStyling>
It's not typical to use a `css` variable as an element. Did you mean to use a `styled` component?

As-is, I also don't see the left margin being applied (due to the use of the `css` variable). I'm curious if this means that we don't even need the css and some whitespace is all we need?

2023-09-19 19:33 UTC, rayangler commented on src/components/Link.js
> +      {decoration}
Is it possible to leave the `arrowAppearance` prop as-is? I think it might be preferable to use LG's built-in prop for this instance

2023-09-19 19:33 UTC, rayangler commented
Can you also please update the staging link @anabellabuckvar ? I think the previous changes (incorrect link) are still present.

2023-09-20 16:05 UTC, caesarbell reviewed
I left some suggestions.

2023-09-20 16:05 UTC, caesarbell commented on src/components/Link.js
> +      {decoration}
That might be the trade-off or I wonder if we could leverage the custom `className` and apply the `className` value in the ProductItem.js file 

```
<StyledArticle>
        <SectionHeader customStyles={customStyleHeader}>
          {argument.map((child, i) => (
            <ComponentFactory nodeData={child} key={i} />
          ))}
        </SectionHeader>
        {children.map((child, i) => (
          <ComponentFactory nodeData={child} key={i} showLinkArrow={true} className='some-custom-className' />
        ))}
      </StyledArticle>
```

Then we apply the style using that custom class name. This way it doesn't have an effect on the other links.

2023-09-20 16:52 UTC, caesarbell commented on src/components/Link.js
> +      {decoration}
For more clarity. 

**ProductItem**
```
const customStylesForArrows = css` // choose a better name
  > svg {
    margin-left: 3px;
  }
`;

// then pass it down as a prop
{children.map((child, i) => (
  <ComponentFactory nodeData={child} key={i} showLinkArrow={true} className={cx(customStylesForArrows)} />
))}
```

Then in `RefRole` we can pass that down to the Link in question

```
 const stylingClass = cardRef ? cardRefStyling : '';
  if (url) {
    return (
      <Link className={cx(stylingClass, className)} to={url} showLinkArrow={showLinkArrow}>
        {children.map((node, i) => (
          <ComponentFactory key={i} nodeData={node} />
        ))}
      </Link>
    );
  }
```
This should only allow the style to be applied from the ProductItem component as the style class is defined there.

2023-09-20 16:52 UTC, caesarbell commented on src/components/Link.js
> +      {decoration}
@rayangler thoughts? ☝️

2023-09-20 17:49 UTC, rayangler commented on src/components/Link.js
> +      {decoration}
I think both this and Anabella's current solution are reasonable. 

Ideally, we would just use the prop from LG's Link component, but unfortunately, since we use both LG Link and Gatsby Link, it makes things a little annoying and/or inconsistent. The benefit of the current solution is that it enforces consistency in both styling (even if the difference is subtle) and implementation while keeping the styling all within the component (big win in terms of readability and traceability).

Since the intention of this change is to prevent a cascading shift in styling for unintended elements, I think the current solution is fine for now. In the future, we should revisit if it's possible and/or desirable to render a Gatsby Link as a LG Link so that we can much more cleanly use the same shared prop.

2023-09-20 17:51 UTC, rayangler approved these changes
LGTM, as long as the `console.log` is removed

2023-09-20 17:51 UTC, rayangler commented on src/components/RefRole.js
> +  console.log(url);
Can we remove this?

2023-09-20 19:00 UTC, caesarbell commented
@anabellabuckvar outside of our convo, if it doesn't work this solution is okay as well. I will mark approved to not block or hold you up.

2023-09-20 19:00 UTC, caesarbell approved these changes

2023-09-20 19:29 UTC, anabellabuckvar commented on src/components/Link.js
> +      </ArrowRightStyling>
implemented these changes

2023-09-20 21:26 UTC, caesarbell commented
Another option could be adding the style changes in the `RefRole.js` if this spacing needs to be more globally acceptable.

2023-09-22 16:33 UTC, merged