DOP-3903: API Changelog Support to omit entries
mongodb/snooty pull request #919
Opened 2023-09-26 15:08 UTC by anabellabuckvar

### Stories/Links:

[DOP-3903](https://jira.mongodb.org/browse/DOP-3903)

### Current Behavior:

[Production API Changelog
](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/changelog/)

### Staging Links:

[Staging API changelog](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/cloud-docs/anabella.buckvar/DOP-3903-b/reference/api-resources-spec/changelog/index.html)

### Notes:
Atlas App Services Function [fetchOADiff](https://realm.mongodb.com/groups/5bad1d3d96e82129f16c5df3/apps/5d41ef5e2de84772fc7c2de2/functions/646cc47cf571983e9ce0671e) was updated in the process of completing this ticket, please review it as well before giving a LGTM!

2023-09-28 19:26 UTC, caesarbell reviewed
Is there a way you can provide a staging link to verify the success of this PR?

2023-09-28 19:27 UTC, caesarbell commented
I am sorry, I just noticed this PR is a Draff.

2023-10-03 13:53 UTC, branberry requested changes
Overall, this is really good! I left some comments about some of the checks, and a small concern I had about the updating of values in the map calls.

Also, I would recommend adding unit tests to ensure that it's working as expected.

2023-10-03 13:53 UTC, branberry commented on gatsby-node.js
> +        path.versions = path.versions.map(versionUpdate);
Mutating the current object that is provided in the `map` could lead to unintended side effects. Just to err on the side of caution, you can make a copy of `path` and update that. You can make a copy like so: 
```js
const updatedPath = {...path}
```

2023-10-03 13:53 UTC, branberry commented on gatsby-node.js
> +          (path) => path !== null && path.versions !== null && path.versions.length !== 0
We can omit `path !== null`, we'll want to also check if `path.versions` is also `undefined`

2023-10-03 13:53 UTC, branberry commented on gatsby-node.js
> +        (dateSection) => dateSection !== null && dateSection.paths !== null && dateSection.paths.length !== 0
We can omit `dateSection !== null`, we'll want to also check if `dateSection.paths` is also `undefined`

2023-10-03 13:53 UTC, branberry commented on src/components/OpenAPIChangelog/OpenAPIChangelog.js
> +  //console.log(changelog);
This can be removed

2023-10-03 15:02 UTC, mmeigs reviewed
Mainly a comment below agreeing and expanding on what Brandon mentioned!
Also, just reminding here that this merge with the latest master will be an odd one. This will mostly all go in `plugins/utils/openapi` I would guess.

2023-10-04 19:09 UTC, branberry approved these changes
LGTM!

2023-10-05 13:48 UTC, mmeigs commented on tests/unit/__snapshots__/OpenAPIChangelog.test.js.snap
> +      </section>
Hmm, this makes me slightly worried? I believe this is the change you added that has the hideFromChangelog flag as true? So, it shouldn't be in the snapshot

2023-10-05 13:48 UTC, mmeigs commented on tests/unit/__snapshots__/ChangeList.test.js.snap
> +    </section>
Same here

2023-10-05 13:48 UTC, mmeigs commented on plugins/utils/openapi.js
> +    };
Oh, and reminder to have this function somewhere where it can be exported so we can reuse it rather than declaring it twice!

2023-10-06 17:53 UTC, anabellabuckvar commented on plugins/utils/openapi.js
> +    };
Refactored the functions, let me know what you think!

2023-10-06 17:54 UTC, anabellabuckvar commented on tests/unit/__snapshots__/ChangeList.test.js.snap
> +    </section>
I redid the tests, the snapshots should be clearer now.

2023-10-06 18:44 UTC, mmeigs reviewed
Two main things about placement of hiding the changes!
1. You can/should use the hideChanges util function in gatsby-node! That way it only occurs once, server-side. 
2. We still need to use hideDiffChanges in gatsby-node as well. Otherwise, the most recent diff will not have the changes hidden.

2023-10-06 18:44 UTC, mmeigs commented on tests/unit/ChangeList.test.js
> +  // });
These can be removed, I believe

2023-10-06 18:45 UTC, mmeigs commented on src/components/OpenAPIChangelog/utils/filterHiddenChanges.js
> +export const hideChanges = (changelog) => {
Would also love a comment above this explaining what this first util function is doing (ie what field it's hiding and that it is meant to be used on the changelog rather than the diff

2023-10-06 18:47 UTC, mmeigs commented on tests/unit/filterHiddenChanges.test.js
> +describe(' ChangeList data', () => {
I think all of this is fine! I also think if you wanted, this could just be a utility function test, so no need to render any components. Just pass a changelog and a diff through the functions and make sure the output is correct. But I'm totally fine with leaving all this. It accomplishes the same goal!

2023-10-09 15:56 UTC, mmeigs reviewed
It looks good overall. But I am worried about using CommonJS exports in the frontend/react. Does this actually work? Especially if you comment out lines 17-20 in useFetchDiff?

2023-10-09 19:56 UTC, anabellabuckvar commented
> It looks good overall. But I am worried about using CommonJS exports in the frontend/react. Does this actually work? Especially if you comment out lines 17-20 in useFetchDiff?

Yes, it worked when I commented them out, and I used CommonJs exports only because I was following the format I saw in some of the other files. Would you like me to change it?

2023-10-10 15:32 UTC, mmeigs approved these changes
Ok, LGTM!

2023-10-10 20:04 UTC, merged