DOP-4060 adds language selector to unified footer on docs' pages.
mongodb/snooty pull request #928
Opened 2023-10-02 16:13 UTC by caesarbell

### Stories/Links:

DOP-4060

### Current Behavior:

[current behavior](https://www.mongodb.com/docs/)

### Staging Links:

[staged with hiding language selector](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/882f0e864792833928caca013c5b1f20bbad1662/master/atlas-cli/caesarbell/DOP-4060/)

[staged with showing language selector](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/66052e957abdf528b03838706b79da1d6c855be4/master/atlas-cli/caesarbell/DOP-4060/)

### Notes:

This enables the language selector for the unified footer on all docs pages and points the href to the A/C of the ticket. This feature is also hidden behind a feature flag that is enabled only for non-prod env at this time.

2023-10-02 18:18 UTC, seungpark requested changes
@caesarbell can you verify what the end result of selecting eng/chinese on the dropdown should be? i'm not sure if we should be navigating them to a certain production page, or just changing the footer language, etc.

2023-10-02 18:18 UTC, seungpark commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
can we update the A/C of this ticket? i'm pretty sure we don't want users going to preprd when they switch. should they be navigated to a different page at all? couldnt find a mongodb docs page in chinese. even this page https://www.mongodb.com/zh-cn the docs link goes back to our english docs page

2023-10-02 18:18 UTC, seungpark commented on src/components/DocumentBody.js
> +          <UnifiedFooter hideLocale={HIDE_UNIFIED_FOOTER_LOCALE} onSelectLocale={onSelectLocale} />
tested with passing in a `locale` prop here. changes the UnifiedFooter language, which i think would be desired

2023-10-02 18:18 UTC, seungpark commented on src/components/DocumentBody.js
> +        const en = footerUlElement.firstChild;
(assuming we only want eng and chinese) instead of assuming first and last, i would construct the children here (as same as in consistentnav) and pipe them in here

2023-10-02 18:18 UTC, seungpark commented on src/components/DocumentBody.js
> +      const footerUlElement = footer?.querySelector('ul');
seems like theres multiple `ul` in the footer, but there is only one with `'ul[role=listbox]'`

2023-10-02 18:19 UTC, seungpark commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
ah i see this is for testing in stage only for now 👍 however, i cannot access the link above. getting hit with a 502 err

2023-10-02 18:31 UTC, caesarbell commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
If we look at the A/C [ticket](https://jira.mongodb.org/browse/DOP-4060) it says says the href should point to the following URLs. They were provided in the ticket as well.

2023-10-02 18:31 UTC, caesarbell commented
> @caesarbell can you verify what the end result of selecting eng/chinese on the dropdown should be? i'm not sure if we should be navigating them to a certain production page, or just changing the footer language, etc.

This is from the ticket A/C

```
There is a way to swap between the english-language version of the site, located at https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/,  and the Chinese-language version, located at [https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/](https://mongodbcom-cdn.website.staging.corp.mongodb.com/%7B*%7Dzh-cn%7B*%7D/docs-qa/)
```

2023-10-02 18:32 UTC, caesarbell commented on src/components/DocumentBody.js
> +  const HIDE_UNIFIED_FOOTER_LOCALE = process.env['GATSBY_HIDE_UNIFIED_FOOTER_LOCALE'] === 'true';
That is fair. I can move this outside the component scope.

2023-10-02 18:33 UTC, caesarbell commented on src/components/DocumentBody.js
> +          <UnifiedFooter hideLocale={HIDE_UNIFIED_FOOTER_LOCALE} onSelectLocale={onSelectLocale} />
I might be a bit confused about the above, are you confirming it worked or saying it didn't work?

2023-10-02 18:35 UTC, caesarbell commented on src/components/DocumentBody.js
> +        const en = footerUlElement.firstChild;
@seungpark can you share an example when you say the same as in consistentnav? Yes, we would as of now only show those two options.

2023-10-02 18:38 UTC, caesarbell commented on src/components/DocumentBody.js
> +      const footerUlElement = footer?.querySelector('ul');
I could make that swap, even tho this one is the first one that appears and will only change if the design of the footer changes and `querySelector` returns the first match.

2023-10-02 18:54 UTC, caesarbell commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
@seungpark idk if that is on me or the reporter of the ticket. What is our process for that?

2023-10-02 18:55 UTC, caesarbell commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
As of now, I was told the 503 is okay, for the page we are sending them to. I can confirm if you prefer.

2023-10-02 18:58 UTC, seungpark commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
i think this is fine for now, since it is hidden behind a feature flag? but i'm personally confused if we:
1. want to make use out of the UnifedFooter prop `locale` or
2. navigate them to a potential(?) Chinese version of docs site

2023-10-02 19:06 UTC, seungpark commented on src/components/DocumentBody.js
> +        const en = footerUlElement.firstChild;
actually, i'm not sure how these elements are bringing back the values for the `onSelectLocale` so i will leave it as this... 🙏

2023-10-02 19:17 UTC, caesarbell commented on src/components/DocumentBody.js
> +      'zh-cn': 'https://mongodbcom-cdn.website.staging.corp.mongodb.com/zh-cn/docs-qa/',
I believe it is more #2 that they want. Something similar to the unified footer on the homepage. It allows us to select the language and navigates the user somewhere.

Correct, it is hidden behind a feature flag.

2023-10-02 19:45 UTC, caesarbell commented on src/components/DocumentBody.js
> +        const en = footerUlElement.firstChild;
No worries. I made the change anyways and it is bit more dynamic just incase they are swapped around from `localMap` or if we want to add a new one.

2023-10-03 13:46 UTC, seungpark approved these changes
changes LGTM ! will follow up with review for autobuilder changes

2023-10-03 13:46 UTC, seungpark commented on src/components/DocumentBody.js
> +        // For DOP-4060 we only want to support English and Simple Chinese (for now)
nice!

2023-10-03 17:24 UTC, rayangler approved these changes

2023-10-03 18:11 UTC, merged