DOP-3938: Update spacing on the search results page
mongodb/snooty pull request #930
Opened 2023-10-02 20:45 UTC by anabellabuckvar

### Stories/Links:

[DOP-3938](https://jira.mongodb.org/browse/DOP-3938)

### Current Behavior:

[Production search results](https://www.mongodb.com/docs/search/?q=atlas)

### Staging Links:

[Search staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-3938-b/search/index.html)

### Notes:

A [PR](https://github.com/mongodb/snooty/pull/878) was previously opened and merged for this same ticket, but was reverted as there was weird behavior observed. On hover at this [search staging link]( https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/search/?q=mongodb&page=1), the highlighting behavior is off and the borders regressed for the search results compared to those in [production]( https://www.mongodb.com/docs/search/?q=aggregate&page=1).

2023-10-03 14:43 UTC, seungpark approved these changes
header changes LGTM.

cleanup on removing `style` attribute can be made in a follow up PR.

slightly off tangent, but seems like search results in design do not match search results on page in terms of height, font sizing. we can handle this in a different ticket

2023-10-03 14:43 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +          <H3 as="h1"> Search Results</H3>
```suggestion
          <H3 as="h1">Search Results</H3>
```

2023-10-03 14:43 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
>              value={searchField}
can we remove those inline `style={}`  (except for the one that reads `display: none;`

for `ResultTag`, the styling is already done in line 222 (already styled div) 

and for LG components, we can use `<Overline className={ cx(css`` ) }>`  see example [here](https://github.com/mongodb/snooty/blob/master/src/components/Paragraph.js#L21)

2023-10-03 14:43 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
>              value={searchField}
we can combine padding for Overline and ResultTag

2023-10-03 17:36 UTC, casthewiz reviewed
I think it's worth consolidating some of the inline styles in this PR as well - the ResultTag style on line 355 of SearchResults.js can be moved to line 224 and placed within the `styled` definition, and likewise for [inline styles on line 444](https://github.com/mongodb/snooty/blob/e59148143a7db4a72b5520bcbe452e93d878fcc9/src/components/SearchResults/SearchResults.js#L444-L447)

2023-10-03 21:49 UTC, anabellabuckvar commented on src/components/SearchResults/SearchResults.js
>              value={searchField}
what do you mean by combine padding?

2023-10-05 13:16 UTC, seungpark requested changes
minor changes within the ResultTag! see screenshot below

2023-10-05 13:16 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +  padding-top: 21px;
```suggestion
  padding-top: ${theme.size.default};
  align-items: center;
```

seeing the tags a little off center:

![image](https://github.com/mongodb/snooty/assets/13054820/2b7fca5e-bd4c-4b7d-a46d-3b6004a5b485)

2023-10-05 13:16 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
> +  padding-top: 21px;
we should remove the lines 216-218 since ResultTag has the padding already

2023-10-05 13:16 UTC, seungpark commented on src/components/SearchResults/SearchResults.js
>              value={searchField}
you got it! but seems like it should be adjusted to 16px. left a suggestion above

2023-10-05 16:20 UTC, seungpark approved these changes
LGTM besides minor padding on res count

2023-10-06 14:46 UTC, merged