DOP-4174: Upgrade Chatbot to  v0.1.2
mongodb/snooty pull request #970
Opened 2023-12-11 20:51 UTC by anabellabuckvar

### Stories/Links:

[DOP-4174
](https://jira.mongodb.org/browse/DOP-4174)

### Current Behavior:
The chatbot currently being used in production is v0.0.6

[Prod chatbot](https://www.mongodb.com/docs/)

### Staging Links:

[Staging Link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/landing/anabella.buckvar/DOP-4174/index.html)

### Notes:

2023-12-13 18:47 UTC, seungpark requested changes
minor change request for removing margins

nice usage of lazy loading named exports 👍

2023-12-13 18:47 UTC, seungpark commented on src/components/ChatbotUi.js
>      grid-template-columns: minmax(${theme.size.xlarge}, 1fr) repeat(12, minmax(0, ${CONTENT_MAX_WIDTH / 12}px)) minmax(
think we can remove the `margin-left: -32px` since the padding is removed. staged site shows chatbot shifted a little left

![image](https://github.com/mongodb/snooty/assets/13054820/b8ee82db-bdf9-4216-a0be-2d6ce5bb7c5c)

2023-12-13 19:22 UTC, rayangler commented on src/components/ChatbotUi.js
> +            serverBaseUrl={CHATBOT_SERVER_BASE_URL}
Looks like `DocsChatbot` no longer has a `serverBaseUrl` and is instead in the `Chatbot` component. Should we move accordingly?

2023-12-14 20:00 UTC, seungpark approved these changes
LGTM 👍 

should note that the `CHATBOT_SERVER_BASE_URL` is not working in stage sites ie. https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/ due to CORS errors, but this is blocker to this ticket

2023-12-14 20:05 UTC, rayangler approved these changes

2023-12-18 23:35 UTC, merged