DOP-4152
mongodb/snooty pull request #982
Opened 2024-01-10 21:12 UTC by anabellabuckvar

### Stories/Links:

DOP-NNNN

### Current Behavior:

_Put a link to current staging or production behavior, if applicable_

### Staging Links:

_Put a link to your staging environment(s), if applicable_

### Notes:

2024-01-12 19:45 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +  }, [reposMap]);
Does the legacy dropdown selector page ever get accessed from a specific product? It seems to me that this code is no longer necessary but would like confirmation before deleting it.

2024-01-12 19:50 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +              value: version,
Each version value is set to an object, which is causing errors as shown in the screenshots below. Functionality is not affected but I'm wondering if I should change it and if so to what
<img width="1114" alt="Screenshot 2024-01-12 at 2 48 12 PM" src="https://github.com/mongodb/snooty/assets/41971124/46bb245b-217b-4f18-87cf-28f8750bbc7f">
<img width="1054" alt="Screenshot 2024-01-12 at 2 48 29 PM" src="https://github.com/mongodb/snooty/assets/41971124/a762c0a2-2dae-42d0-b64e-01248e0aeaa9">

2024-01-25 15:35 UTC, mmeigs commented on src/components/DeprecatedVersionSelector.js
> +              value: version,
Yes, `option` elements should only have `string` values. This also lines up with the `useState` for `version` that is initialized as a `string`. I might have missed something, but I think the only time you use the stored `version` object is simply to access its `urlSlug`. If so, then I would simply have the value be the `urlSlug`! That will get rid of any errors or inconsistencies.

2024-01-26 03:12 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +              value: version,
Thanks, it's fixed now! It ended up making more sense to use the `versionSelectorLabel` and not all of the slugs were unique (at least in the staging database), anyways

2024-01-31 17:58 UTC, schmalliso reviewed
Just a couple of questions! Looks great.

2024-01-31 17:58 UTC, schmalliso commented on src/components/DeprecatedVersionSelector.js
> +  const reposBranchesBuildData = useAllDocsets().filter((project) => !!project.hasEolVersions);
Why are we using the double bang here rather than just `project.hasEolVersions`? (This isn't a socratic method question, I'm legit curious.)

2024-01-31 17:58 UTC, schmalliso commented on src/components/DeprecatedVersionSelector.js
> +        .sort(alphabetize)
Will this alphabetize `v1.0`, `v1.2`, `v1.10` as 
```
1.0
1.10
1.2
```

And if so, do we have a workaround?

2024-01-31 18:44 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +  const reposBranchesBuildData = useAllDocsets().filter((project) => !!project.hasEolVersions);
I included it as an extra precaution in case a project in `reposBranches` doesn't have a `hasEolVersions` field; however, it's not strictly necessary and I could remove use of it if you think that would be better

2024-01-31 19:43 UTC, schmalliso commented on src/components/DeprecatedVersionSelector.js
> +  const reposBranchesBuildData = useAllDocsets().filter((project) => !!project.hasEolVersions);
Nope it's all good, I was just wondering - your rationale is very sound :)

2024-01-31 19:47 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +  const reposBranchesBuildData = useAllDocsets().filter((project) => !!project.hasEolVersions);
After chatting with @mmeigs, they are truly unnecessary here so I removed double bang instances

2024-01-31 19:48 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +        .sort(alphabetize)
We did not have a workaround. Now we do!

2024-02-01 18:29 UTC, mmeigs reviewed
Just a couple more comments! This is such an exciting change.

2024-02-01 18:29 UTC, mmeigs commented on src/components/DeprecatedVersionSelector.js
> +  }, [reposDatabase, reposBranchesBuildDataMap]);
I don't think we need the `reposBranchesBuildDataMap` as a dependency!

2024-02-01 18:29 UTC, mmeigs commented on src/components/DeprecatedVersionSelector.js
> +
nit: We could wrap both of these variable definitions in a `useMemo` to keep them updating only when necessary

2024-02-01 18:29 UTC, mmeigs commented on src/components/DeprecatedVersionSelector.js
>    };
Because there's a possibility of currentVersion being undefined, maybe we should check for that at the start of this generateUrl function and return `null` if that's the case to make sure that no odd url like `<hostname>/undefined` occurs

2024-02-01 18:29 UTC, mmeigs commented on src/components/DeprecatedVersionSelector.js
> +        )
Yay! Thanks for this

2024-02-01 18:33 UTC, seungpark requested changes
this looks great! a few minor changes below.

also, thanks for the comments! the links are not working but will assume pool_test.repos_branches entries are not cleaned. as for the third comment, not seeing any error on select components

2024-02-01 18:33 UTC, seungpark commented on src/components/DeprecatedVersionSelector.js
> +      if (site && Object.keys(reposMap).includes(site)) {
minor nitpick. instead of `Object.keys(reposMap).includes(site)`, can we use `reposMap[site]` ?

2024-02-01 18:33 UTC, seungpark commented on src/components/DeprecatedVersionSelector.js
> +        .sort((a, b) =>
nice sorting! good chance to pull into util and add some unit tests (not blocking!)

2024-02-01 18:33 UTC, seungpark commented on src/components/DeprecatedVersionSelector.js
> +        {version?.eol_type === 'download' ? 'Download Documentation' : 'View Documentation'}
think we should be checking `versionChoicesMap[version]?.eol_type` here. seems like `version` is a string CMIIW

2024-02-01 18:33 UTC, seungpark commented on tests/unit/DeprecatedVersionSelector.test.js
>    });
minor. possibly another test for EOL selectors

2024-02-06 15:03 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +        {version?.eol_type === 'download' ? 'Download Documentation' : 'View Documentation'}
You're right! good catch, thank you

2024-02-06 20:22 UTC, anabellabuckvar commented on src/components/DeprecatedVersionSelector.js
> +        .sort((a, b) =>
Added a test, lmk what you think!

2024-02-08 15:26 UTC, seungpark approved these changes
this LGTM. threw me off a little bit because it differs from prod data (by virtue of different sources of truth). 

with that said, would validate that pool_test and pool repos_branches entries are 1) in sync and 2) ready to be tested in preprd so we can promote to prod :)

2024-02-09 21:04 UTC, merged